Automated tests for system components and Istion envoy stats
verrazzano/verrazzano pull request #1212
Opened 2021-06-03 11:59 UTC by bhatpmk

# Description

This change adds the additional test cases to validate the metrics for system components and Istion envoy stats. This change required the stage which runs the multicluster/verify-install to be moved after the managed register registration. 

Contributes to VZ-2351

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-06-04 12:45 UTC, pfmackin commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +var excludePodsVS = []string{
why are we excluding these pods?  The exist on managed cluster and should have stats.

2021-06-04 12:52 UTC, markxnelson requested changes

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +		metricName := "envoy_server_stats_recent_lookups"
use a const?

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 1; i < clusterCount; i++ {
this will miss the last cluster - don't you mean `<=`?

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +			for i := 1; i < clusterCount; i++ {
<=

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 2; i <= clusterCount; i++ {
why start with two and then subtract one?

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/security/network-policies/network_policy_test.go
> +				err = testAccess(metav1.LabelSelector{MatchLabels: map[string]string{"app": "system-prometheus"}}, "verrazzano-system", metav1.LabelSelector{MatchLabels: map[string]string{"app.kubernetes.io/comp
magic numbers!

2021-06-04 12:52 UTC, markxnelson commented on tests/e2e/verify-install/prometheus/prometheus_test.go
> +			ginkgo.Context("Verify metrics from Container Advisor", func() {
what is container advisor, and why do we care about it?

2021-06-04 16:09 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	"istiocoredns",
I will remove istiocoredns and istiod from excludePodsVS. They are part of excludePodsIstio

2021-06-04 16:10 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +var excludePodsVS = []string{
These pods do not have envoy, so stats are not available.

2021-06-04 16:10 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +		metricName := "envoy_server_stats_recent_lookups"
Sure

2021-06-04 16:14 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 2; i <= clusterCount; i++ {
CI pipeline creates the cluster like this - 
admin (KUBECONFIG - <some directory>/1/kube_config
managed1 (KUBECONFIG - <some directory>/2/kube_config
managed2 (KUBECONFIG - <some directory>/3/kube_config
etc. Just to handle the directory containing the kube config and the suffix for the managed cluster, used a single variable.

2021-06-10 12:11 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +var excludePodsVS = []string{
Resolving this conversation based on a conversation with @pfmackin

2021-06-10 12:13 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 1; i < clusterCount; i++ {
No, clusterCount represents total number of clusters present in the test environment, including admin cluster. So clusterCount 3 indicates managed 1 and managed 2, so the loop should end at 2.

2021-06-10 12:33 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +			for i := 1; i < clusterCount; i++ {
No, clusterCount represents total number of clusters present in the test environment, including admin cluster. The condition is correct.

2021-06-10 15:58 UTC, bhatpmk commented on tests/e2e/verify-install/prometheus/prometheus_test.go
> +			ginkgo.Context("Verify metrics from Container Advisor", func() {
From the documentation, Container Advisor analyzes and exposes resource usage and performance data from running containers. Verrazzano has a scrape job for cAdvisor and this test validates that.

2021-06-10 15:58 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	"istiocoredns",
Done

2021-06-10 15:58 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +		metricName := "envoy_server_stats_recent_lookups"
Done

2021-06-10 15:59 UTC, bhatpmk commented on tests/e2e/security/network-policies/network_policy_test.go
> +				err = testAccess(metav1.LabelSelector{MatchLabels: map[string]string{"app": "system-prometheus"}}, "verrazzano-system", metav1.LabelSelector{MatchLabels: map[string]string{"app.kubernetes.io/comp
Added constants for the ports in the newly added ingress validations.

2021-06-10 16:19 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +package mc_prometheus_test
the package should match the directory name, shouldn't it?

2021-06-10 16:19 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 1; i < clusterCount; i++ {
that's too magical.  i don't like it. 
a much better approach imo would be to create a slice with just the things you want to look at, and then iterate (range) over that.

2021-06-11 09:09 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +package mc_prometheus_test
I am not aware of any such rule by the language, might be a convention.

2021-06-11 09:19 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	for i := 1; i < clusterCount; i++ {
I have updated the test to validate the metrics for single managed cluster. The Jenkinsfile used by the multi-cluster pipeline is updated to call the suite once per managed cluster.

2021-06-11 12:15 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +			for i := 1; i < clusterCount; i++ {
With the latest change, the test validates the the metrics for single managed cluster and the confusing logic is removed from the test file.

2021-06-11 12:21 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +package mc_prometheus_test
i wont approve this name, it violates the language's conventions and recommendations, and it creates unnecessary confusion. read https://blog.golang.org/package-names and https://golang.org/doc/effective_go#names

2021-06-11 12:21 UTC, markxnelson commented on ci/multicluster/Jenkinsfile
> +            for(int count=2; count<=clusterCount; count++) {
this is still magic - why 2? why subtract 1? 
how does the person who comes along six months from now know why you did this? 
you need to refactor so it is immediately obvious what the code is doing

2021-06-11 12:21 UTC, markxnelson commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	return true
did you mean to return true here or retValue?

2021-06-17 19:59 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +package mc_prometheus_test
For the newly added files, I have updated the package to reflect the name of the directory. I did not make the change for the other files touched in this PR. There are several test files having this issue. Also there are cases where package contains underscore. We can change all of them in a single change separately.

2021-06-17 20:03 UTC, bhatpmk commented on ci/multicluster/Jenkinsfile
> +            for(int count=2; count<=clusterCount; count++) {
The Jenkinsfile for the multicluster AT still requires something like below, I have put a comment to tell the reason for that.

`            for(int count=1; count<=clusterCount; count++) {
                // The first cluster created by this script is named as admin, and the subsequent clusters are named as
                // managed1, managed2, etc.
                if (count == 1) {
                    clusterName="admin"
                } else {
                    clusterName="managed${count-1}"
                }`

The name of the cluster is set in the environment so that the test suite can confirm the managed server metrics scraped from admin cluster contains an additional label managed_cluster with the name of the cluster as the value.

2021-06-17 20:10 UTC, bhatpmk commented on tests/e2e/multicluster/verify-install/prometheus/prometheus_test.go
> +	return true
The variable retValue is defined inside the inner loop, the intention is to return false on first failure with the verification. So we come to the last return statement only after all the validations return true.

2021-06-23 12:30 UTC, markxnelson approved these changes

2021-06-23 15:20 UTC, merged