WIP:  update example images
verrazzano/verrazzano pull request #1294
Opened 2021-06-24 17:16 UTC by guoyongzhang

# Description

Update example images with wls-exporter.war removed.

Fixes VZ-2706

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-06-24 17:17 UTC, markxnelson requested changes
must be from OCR

2021-06-24 17:19 UTC, guoyongzhang commented
WIP.  Wanna run tests with them first before publishing them to OCR.

2021-06-24 17:20 UTC, markxnelson commented
ok but you can do that in a branch without a pr

2021-06-25 16:08 UTC, markxnelson approved these changes

2021-06-29 19:50 UTC, mgianatagh approved these changes

2021-06-29 19:59 UTC, merged