WIP:Defined initial fields required in ImageBuildRequest
verrazzano/verrazzano pull request #1302
Opened 2021-06-29 16:35 UTC by muhilaru

# Description

Defined the initial fields required in the ImageBuildRequest based on WIT create image usage.

Fixes VZ-2906

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-06-29 17:49 UTC, mgianatagh commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
> +	BaseImage         string `json:"baseImage,omitempty"`
I would add a comment for each of the fields to describe what they are.

2021-06-29 17:49 UTC, mgianatagh commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
> +	Name       string `json:"name,omitempty"`
All the fields may be required.  I would lead with removing omitempty.

2021-06-29 18:58 UTC, muhilaru commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
> +	BaseImage         string `json:"baseImage,omitempty"`
Added comments for each field

2021-06-29 18:58 UTC, muhilaru commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
> +	Name       string `json:"name,omitempty"`
Removed

2021-06-29 19:20 UTC, bobdonat commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
>  	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
I think this kubebuilder generated comment can be changed/removed.  Does not seem to accurate any longer.

2021-06-29 19:52 UTC, muhilaru commented on image-patch-operator/api/images/v1alpha1/imagebuildrequest_types.go
>  	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
Removed

2021-06-29 23:02 UTC, bobdonat approved these changes

2021-06-30 09:30 UTC, mgianatagh requested changes

2021-06-30 09:30 UTC, mgianatagh commented on image-patch-operator/config/crd/bases/images.verrazzano.io_imagebuildrequests.yaml
> +              baseImage:
This file is out of date with your recent changes to the ImageBuildRequest, it needs to be regenerated.

2021-06-30 10:55 UTC, muhilaru commented on image-patch-operator/config/crd/bases/images.verrazzano.io_imagebuildrequests.yaml
> +              baseImage:
Ok, regenerated file

2021-06-30 11:21 UTC, mgianatagh approved these changes

2021-06-30 13:32 UTC, merged