Release 0.15.1
verrazzano/verrazzano pull request #1318
Opened 2021-07-01 15:39 UTC by kminder

# Description

Release 0.15.1

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-07-01 17:34 UTC, michael-cico approved these changes

2021-07-02 02:02 UTC, pfmackin approved these changes

2021-07-02 02:07 UTC, pfmackin requested changes
Where is the bom file change?

2021-07-02 02:20 UTC, michael-cico commented on platform-operator/helm_config/charts/verrazzano-platform-operator/Chart.yaml
> +appVersion: 0.15.1
I think `platform-operator/helm_config/charts/verrazzano/Chart.yaml` needs to be set to `0.15.1` also

2021-07-02 14:02 UTC, merged