Modifications to alleviate test failures and introduce additional logging
verrazzano/verrazzano pull request #1373
Opened 2021-07-22 20:23 UTC by jmaron99

# Description

Various modification to address current test failures, including:
- temporary removal of AP region from OKE related build due to historical and current issues with image pulling.  A story will be filed to track the need for better image pull resiliency
- Sockshop:  extend wait for namespace termination
- Todo-list:  additional logging to try to discern why the cert secret is intermittently not deleted and triggers a failure.  Also introduced a check to ensure the certificate resource has been deleted.
- dump cluster script fix to ensure the target namespace's resource description is save to namespace folder rather than all namespaces saved to each namespace folder

Fixes/Addresses VZ-3099, VZ-3101, VZ-3095

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-07-22 20:40 UTC, bobdonat submitted a review, later dismissed
Looks good

2021-07-22 20:41 UTC, fredtibbitts requested changes

2021-07-22 20:41 UTC, fredtibbitts commented on ci/oke-ocidns/Jenkinsfile
> +// see https://build.verrazzano.io/job/verrazzano-new-oci-dns-acceptance-tests/job/master/520/ for example
Remove this URL

2021-07-22 20:41 UTC, fredtibbitts commented on ci/uninstall/Jenkinsfile
> +// see https://build.verrazzano.io/job/verrazzano-new-oci-dns-acceptance-tests/job/master/520/ for example
Remove URL.

2021-07-22 20:41 UTC, fredtibbitts commented on tests/e2e/pkg/secrets.go
> +		Log(Info, fmt.Sprintf("GetSecretInCluster error: %s", err))
Shouldn't this return nil, err?

2021-07-22 20:48 UTC, fredtibbitts commented on tests/e2e/pkg/secrets.go
> +		Log(Info, fmt.Sprintf("GetSecretInCluster error: %s", err))
Oh, it'll fall through and return the right thing I guess, so this seems OK.

2021-07-22 20:56 UTC, fredtibbitts approved these changes

2021-07-23 02:01 UTC, gilbode approved these changes

2021-07-23 11:20 UTC, jmaron99 commented on tests/e2e/examples/socks/sock_shop_example_test.go
> +	for i := 0; i < 20; i++ {
This loop was originally created to try to gather more information about the failure.  The loop was iterating and pausing for 30 seconds (10*30 seconds), but observations of some tests indicated that the namespace may have completed deletion shortly after the 5 minutes lapsed.  The update to 20 is in hopes of allowing more time for the deletion to complete, though admittedly more of a data point rather than an ultimate solution.

2021-07-23 13:13 UTC, merged