BUG: CLI is using tests/e2e/pkg
verrazzano/verrazzano pull request #1375
Opened 2021-07-23 06:06 UTC by viswanathtadi

# Description

CLI is using tests/e2e/pkg
Removed the dependency tests/e2e/pkg for CLI
CLI now creates clientsets using helpers in cli/pkg/helpers
Made sure that all unit tests in CLI are passing.

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-07-23 09:48 UTC, lake-of-dreams commented on tools/cli/vz/cmd/app/helidon/list.go
> +	if err != nil {
return err, not nil

2021-07-23 11:42 UTC, lake-of-dreams submitted a review, later dismissed

2021-07-26 12:38 UTC, bobdonat submitted a review, later dismissed

2021-07-26 14:24 UTC, markxnelson submitted a review, later dismissed

2021-07-26 14:25 UTC, markxnelson commented on tools/cli/vz/pkg/helpers/kubernetes.go
> +func GetKubeConfig() (*restclient.Config, error) {
surely we have existing code that does this already?

2021-07-26 14:25 UTC, markxnelson reviewed
seems to be code duplication in here

2021-07-29 14:02 UTC, markxnelson requested changes

2021-07-29 14:02 UTC, markxnelson commented on THIRD_PARTY_LICENSES.txt
> +Copyright:    copyrightLine(),
you need to remove these lines that just have code in them

2021-07-30 09:13 UTC, lake-of-dreams commented on THIRD_PARTY_LICENSES.txt
> +Copyright:    copyrightLine(),
fixed

2021-07-30 12:27 UTC, lake-of-dreams commented
>seems to be code duplication in here
@markxnelson common code moved to pkg repo in https://github.com/verrazzano/pkg/pull/2, please if you can re-review

2021-08-03 10:40 UTC, lake-of-dreams commented on tools/cli/vz/pkg/helpers/environment.go
> +func GetHostnameFromGateway(namespace string, appConfigName string) (string, error) {
code moved to pkg

2021-08-03 10:40 UTC, lake-of-dreams commented on tools/cli/vz/pkg/helpers/kubernetes.go
> +func GetKubeConfig() (*restclient.Config, error) {
code moved to pkg

2021-08-04 13:05 UTC, lake-of-dreams commented
one of the mc test is failing, debugging

2021-08-06 08:33 UTC, lake-of-dreams commented
all the changes done and tests are passing

2021-08-12 12:39 UTC, markxnelson approved these changes

2021-08-12 12:43 UTC, merged