Pass base image to Image Tool
verrazzano/verrazzano pull request #1412
Opened 2021-08-03 16:30 UTC by marcogelle

# Description

Includes the `--fromImage` parameter to specify the base image in the call to `imagetool create`.
Adds resource limits and requests to the Pod running the Image Tool in order for this to work. Values for the resource limits and requests are specified as Helm values.

Fixes VZ-3185
# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-08-03 17:17 UTC, mgianatagh commented on image-patch-operator/helm_config/charts/image-patch-operator/values.yaml
> +    memory: "1073741824" # = 2^30. Units: Gibibytes
this unit looks like it would be cumbersome to set.  Can this unit instead be represented as the number of GB?  For example "1" or "2.5"?

2021-08-03 17:20 UTC, mgianatagh commented
The unit tests should also be updated to test that the contents of the job object contain the expected values for the limits and resources.  The tests are in image-patch-operator/controllers/imagebuildrequest_controller_test.go.  The function `TestNewImageBuildRequest` contains an example of checks against the job object created for an image build request.

2021-08-03 17:22 UTC, marcogelle commented on image-patch-operator/helm_config/charts/image-patch-operator/values.yaml
> +    memory: "1073741824" # = 2^30. Units: Gibibytes
Ok I can change that.
Also, I just noticed the description of the units I put was wrong according to that version. Making this change should make the comment accurate.

2021-08-05 21:29 UTC, mgianatagh requested changes

2021-08-05 21:29 UTC, mgianatagh commented on image-patch-operator/controllers/imagejob/job.go
> +								"cpu":    resource.MustParse(os.Getenv("WIT_POD_RESOURCE_LIMIT_CPU")),
I do not feel that MustParse is meant to be used in production code.  If the parse fails, it does a panic instead of throwing an error.  From looking at the comment header to the function, it appears it is meant for tests.

// MustParse turns the given string into a quantity or panics; for tests
// or others cases where you know the string is valid.

2021-08-05 21:29 UTC, mgianatagh commented on image-patch-operator/controllers/imagejob/job.go
> +	// If resource limit and request environment variables are not set, then use some default values
I am not sure we want to default the values of these parameters.  If we did, a couple of things I would suggest to do differently are to have the default values be stored in image-patch-operator/constants/constants.go.  You probably wouldn't set environment variables here either.  Instead you could have a function inline in the creation of the batch job that defaulted the value.  I suggest removing these two for loops for now.

2021-08-05 21:29 UTC, mgianatagh commented on image-patch-operator/controllers/imagebuildrequest_controller_test.go
> +	// Default values for resource limits and requests
As I looked as this more I think I want to rework the job.go code a bit more than we have time for at the moment.  Perhaps use a resource template like we do for some of the tests to generate the job struct.  But for now I think the quickest thing to do for testing is to do the os.SetEnv of the resource and limit values here (to any test value you want) and verify the job struct gets created with those values.  My concern in the long run of setting the environment variable is that may not work well for running tests in parallel.

2021-08-05 22:05 UTC, marcogelle commented on image-patch-operator/controllers/imagejob/job.go
> +	// If resource limit and request environment variables are not set, then use some default values
Ok. I am not defaulting these and just removed the two for loops.

2021-08-05 22:07 UTC, marcogelle commented on image-patch-operator/controllers/imagebuildrequest_controller_test.go
> +	// Default values for resource limits and requests
As you suggested, I first did the quick change of moving the os.SetEnv into imagebuildrequest_controller_test.go.

2021-08-05 22:11 UTC, mgianatagh commented on image-patch-operator/controllers/imagebuildrequest_controller_test.go
> +	assert.Zero(cpuLimit.Cmp(cpuValue))
the assert.Equal function will handle the comparison.  So these can be rewritten to be like below.  I feel that will be more readable.

assert.Equal(cpuValue, jb.Spec.Template.Spec.Containers[0].Resources.Limits["cpu"])

2021-08-05 22:25 UTC, marcogelle commented on image-patch-operator/controllers/imagebuildrequest_controller_test.go
> +	assert.Zero(cpuLimit.Cmp(cpuValue))
Changed

2021-08-06 15:32 UTC, mgianatagh approved these changes

2021-08-06 16:02 UTC, merged