Initial Checkin for VZ-3955 Kiali upgrade must update Keycloak redire…
verrazzano/verrazzano pull request #1924
Opened 2021-11-04 18:40 UTC by ddrechse

…ct URLs

# Description

Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another repository, please list those.

Fixes VZ-9999

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-11-09 18:44 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +	if ctx.ActualCR().Spec.Profile != vzapi.ManagedCluster {
This should probably be `EffectiveCR()`, but doesn't have to gate this merge.  We can fix it on another pass, if you can just maybe note it in the JIRA to move Keycloak install to the operator.

2021-11-09 18:50 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +	if ctx.ActualCR().Spec.Profile != vzapi.ManagedCluster {
I can fix it

2021-11-09 18:53 UTC, wmhopkins requested changes
Overall, looks good. Had a few comments on the code.

2021-11-09 18:53 UTC, wmhopkins commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +		cmd := execCommand("kubectl", "exec", "keycloak-0", "-n", "keycloak", "-c", "keycloak", "--",
This command hardwires the keycloak admin username -- why not pull it from the secret, along with the password?

2021-11-09 18:53 UTC, wmhopkins commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
This line and the next mis-characterize the ID -- it's not a user ID, it's an OIDC client ID.

2021-11-09 18:53 UTC, wmhopkins commented on platform-operator/scripts/install/update-kiali-redirect-uris.sh
> +  local KCADMIN_USERNAME=keycloakadmin
Same comment as for the go code above -- use the username from the secret, don't hardwire "keycloakadm".

2021-11-09 18:53 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +	if ctx.ActualCR().Spec.Profile != vzapi.ManagedCluster {
Done

2021-11-09 18:54 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
yeah, for that one, i didn't went to get to into the particulars for security reasons but your the guy so happy to be more specific

2021-11-09 18:56 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
idk what OIDC means so would anybody else reviewing this msg?

2021-11-09 18:59 UTC, wmhopkins commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
You can just say "client ID" or something, but it's for sure not a user. OIDC is fairly commonly understood, though -- it's an acronym for OpenID Connect, which is the authentication standard built on top of Oauth 2.0.

2021-11-09 19:00 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +		cmd := execCommand("kubectl", "exec", "keycloak-0", "-n", "keycloak", "-c", "keycloak", "--",
the username isn't in the secret

2021-11-09 19:00 UTC, ddrechse commented on platform-operator/scripts/install/update-kiali-redirect-uris.sh
> +  local KCADMIN_USERNAME=keycloakadmin
the username isn't in the secret

2021-11-09 19:17 UTC, michael-cico submitted a review, later dismissed
Just a few minor comments

2021-11-09 20:36 UTC, pfmackin commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +func updateKeycloakUris(ctx spi.ComponentContext) error {
keycloak_component should only have implementations of the component interface, but this is ok for now, it can be moved to keycloak.go afterwards.

2021-11-09 20:54 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
Here is what it is
 {
  "id" : "fe7985c2-1221-4fbd-8327-13cdbfe3b000",
  "clientId" : "verrazzano-pkce"
},
That is the json returned from Keycloak

2021-11-09 20:56 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +		cmd := execCommand("kubectl", "exec", "keycloak-0", "-n", "keycloak", "-c", "keycloak", "--",
where would it be logged to?

2021-11-09 21:03 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving Keycloak Clients: %s", err)
do you know the behavior?  u pretty much wrote the infrastructure

2021-11-09 21:23 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Failed updating KeyCloak URIs %s: %s", err, stderr)
removed

2021-11-09 21:23 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving DNS sub domain: %s", err)
removed

2021-11-09 21:23 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			return errors.New("Keycloak Post Upgrade: error retrieving Clients JSON from Keycloak, zero length")
removed

2021-11-09 21:24 UTC, ddrechse commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak_component.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for Keycloak user, zero length")
Done

2021-11-10 01:12 UTC, wmhopkins submitted a review, later dismissed
Had a couple comments on the updated error messages, but they're nitpicks. I approved the PR.

2021-11-10 01:12 UTC, wmhopkins commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
> +			return errors.New("Keycloak Post Upgrade: error retrieving Clients JSON from Keycloak, zero length")
Capitalize "Error", for consistency with other messages?

2021-11-10 01:12 UTC, wmhopkins commented on platform-operator/controllers/verrazzano/component/keycloak/keycloak.go
> +			ctx.Log().Errorf("Keycloak Post Upgrade: Error retrieving ID for client ID, zero length: %s", err)
This probably ought to be more or less the same message as the next error, since it's just noticing a different indicator of the same failure: "Error retrieving clients JSON from Keycloak". You could probably remove the "zero length" from this message, though, since you don't test the length until the next block.

2021-11-10 15:05 UTC, michael-cico approved these changes

2021-11-10 15:05 UTC, merged