VZ-3985 hard restart of WebLogic after Istio upgrade to 1.10 - alternative
verrazzano/verrazzano pull request #1935
Opened 2021-11-08 20:06 UTC by guoyongzhang

# Description

When annotation "verrazzano.io/restart-version" is added to appconfig, and istio-proxy sidecar of WLS domain is 1.7.3, WLS will be forced to hard start by setting "ServerStartPolicy" to "NEVER" and back.

Fixes VZ-3985

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-11-08 21:26 UTC, markxnelson requested changes
i want a discussion about this before it is merged please

2021-11-08 23:45 UTC, mbenmclean commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +	if existingDomain.ObjectMeta.Annotations == nil {
Why are we adding the serverStartPolicy to the annotations?

2021-11-08 23:55 UTC, mbenmclean commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +
Probably don't need two line breaks here

2021-11-08 23:55 UTC, mbenmclean commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +				log.Info(fmt.Sprintf("DeletionTimestamp for pod %s is %s", pod.Name, pod.ObjectMeta.DeletionTimestamp))
This is probably going to spam the logs, particularly because you are looping every second. Maybe 1 log for each loop but probably not a log for each pod in each loop

2021-11-09 12:33 UTC, guoyongzhang commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +	if existingDomain.ObjectMeta.Annotations == nil {
The reconcile will be called twice for domain stop and start.  The first entry to reconcile will set servetStartPolicy to NEVERR.  The current serverStartPolicy needs to be saved somewhere, so the second entry to reconcile will know what servetStartPolicy to set the domain back to.

2021-11-09 12:36 UTC, guoyongzhang commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +
channel and select is a common timeout implementation in go.

2021-11-09 12:40 UTC, guoyongzhang commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +				log.Info(fmt.Sprintf("DeletionTimestamp for pod %s is %s", pod.Name, pod.ObjectMeta.DeletionTimestamp))
In reality, once the domain is marked NEVER, the pods are marked with DeletionTimestamp fairly quickly.  I normally see one or two logs before the code gets out of the loop.  If something went extremely wrong, maybe having 30 logs entries is not that bad.

2021-11-09 14:58 UTC, pfmackin commented
change the title of the PR (put the JIRA)

2021-11-09 15:50 UTC, guoyongzhang commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +	existingDomain.ObjectMeta.Annotations[serverStartPolicyAnnotation] = currentServerStartPolicy
I have tried that.  See this commit, https://github.com/verrazzano/verrazzano/pull/1935/commits/0714773329dcd5f71cff5ae47c5cfa1810ba323d.
With 2 updates in the same reconcile iteration, I consistently saw update conflict ‘the object has been modified; please apply your changes to the latest version and try again’.

2021-11-10 15:53 UTC, closed without merging