VZ-4000 Prevent WebLogic restart during upgrade
verrazzano/verrazzano pull request #1949
Opened 2021-11-09 21:58 UTC by pfmackin

WIP: Still testing

When Verrazzano upgrades the Verrazzano Application Operator, the VAO pod starts, then reconciles the WebLogic workloads.  The fix will prevent the operator from modifying the WebLogic domain, and thus restarting the domain pods, unless the user either modified the WebLogic workload (via OAM component) or the user set the restart-version annotation on the appconfig resource.

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-11-09 22:05 UTC, markxnelson requested changes
i want to talk about this before we move forward- gz set up a meeting already, can we add this please

2021-11-09 23:18 UTC, pfmackin commented
> i want to talk about this before we move forward- gz set up a meeting already, can we add this please

sure we can discuss at the meeting.

2021-11-09 23:26 UTC, mbenmclean approved these changes

2021-11-10 02:33 UTC, michael-cico commented on tests/e2e/upgrade/verify-app/restart/verify_restart_test.go
> +var _ = Describe("verify app restart", func() {
I think the description here is confusing, you're verifying the apps haven't restarted right?

2021-11-10 03:06 UTC, michael-cico approved these changes

2021-11-10 03:06 UTC, michael-cico commented on tests/e2e/pkg/kubernetes.go
> +			if status.RestartCount > 0 {
We can update if needed after this merge.

2021-11-10 03:06 UTC, michael-cico commented on tests/e2e/upgrade/verify-app/restart/verify_restart_test.go
> +var _ = Describe("verify app restart", func() {
non-blocking, we can fix this on the next pass if needed.

2021-11-10 03:41 UTC, michael-cico commented on tests/e2e/pkg/kubernetes.go
> +			if status.RestartCount > 0 {
So, without the fix in this PR, after an upgrade the `todo` AdminServer pod restarted as currently expected.  After the new pod was created, the `RestartCount` is still 0:

```
[c:kind-kind:e2e]$ kubectl  get pod -n todo-list -w
NAME                     READY   STATUS    RESTARTS   AGE
mysql-5c4bd64d4c-j57bl   2/2     Running   0          44m
tododomain-adminserver   4/4     Running   0          84s
```

2021-11-10 18:53 UTC, pfmackin commented on tests/e2e/upgrade/verify-app/restart/verify_restart_test.go
> +var _ = Describe("verify app restart", func() {
yes for now i have to just dump the pods that were restarted since pods can be restarted before upgrade if liveness fails.

2021-11-10 18:54 UTC, pfmackin commented on tests/e2e/pkg/kubernetes.go
> +			if status.RestartCount > 0 {
I see what you are saying.  So really i need a snapshot of the pods pre and post upgrade.

2021-11-10 19:35 UTC, pfmackin commented on tests/e2e/pkg/kubernetes.go
> +			if status.RestartCount > 0 {
these tests are obsolete based on todays meeting regarding auto-app restart on upgrade.  I removed the tests and will do new tests as part of that new JIRA.

2021-11-10 19:51 UTC, markxnelson approved these changes

2021-11-10 20:05 UTC, markxnelson commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +	if _, err := fluentdManager.Apply(logging.NewLogInfo(""), resource, fluentdPod); err != nil {
What's the empty string?

2021-11-10 20:05 UTC, markxnelson commented on application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
> +			//		asserts.NotZero(len(verrazzano.Status.Components), "Status.Components len should not be zero")
Why?

2021-11-10 20:09 UTC, pfmackin commented on application-operator/controllers/wlsworkload/weblogicworkload_controller.go
> +	if _, err := fluentdManager.Apply(logging.NewLogInfo(""), resource, fluentdPod); err != nil {
This is temporary until I fix the Coherence controller, since it uses the same function. Basically, the reconcile used to only update the Fluentd image if the user did some other annotation.  As discussed with Bryan, reconcile should fix everthing, including using the latest Fluentd image

2021-11-10 20:13 UTC, pfmackin commented on application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
> +			//		asserts.NotZero(len(verrazzano.Status.Components), "Status.Components len should not be zero")
removed

2021-11-10 20:13 UTC, pfmackin commented on application-operator/controllers/wlsworkload/weblogicworkload_controller_test.go
> +			//		asserts.NotZero(len(verrazzano.Status.Components), "Status.Components len should not be zero")
removed

2021-11-10 20:29 UTC, michael-cico submitted a review, later dismissed

2021-11-10 23:22 UTC, markxnelson approved these changes

2021-11-12 13:35 UTC, michael-cico approved these changes

2021-11-12 13:35 UTC, merged