fixed wls parse pattern to match more
verrazzano/verrazzano pull request #2014
Opened 2021-11-22 17:56 UTC by shihchang

# Description

Fix a case of 'pattern not matched' errors that the format13 pattern failed if the <message> field contains a ">", greater-than sign, in the message body.

Fixes VZ-3631

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-11-22 19:29 UTC, fredtibbitts commented
I understand that this doesn't fix the original log interleaving issue, but does it change the behavior at all? Do we still report the log interleaving issue the same way and fail the test? I just want to make sure this isn't masking the original problem somehow.

2021-11-22 19:36 UTC, desagar commented on tests/e2e/pkg/elasticsearch.go
> +	for _, hit := range hits.([]interface{}) {
Won't this potentially log a LOT of error messages? Is it better to just count the length of the hits array and print one error msg saying you found n number of of unexpected records?

2021-11-22 19:38 UTC, shihchang commented on tests/e2e/pkg/elasticsearch.go
> +	for _, hit := range hits.([]interface{}) {
The default is 50 or 100; we should not see that many but we may get more than 10.

2021-11-22 19:40 UTC, shihchang commented
@fredtibbitts The  interleaved messages should still fail in matching one of format1 ~ format13, as the message interleaved, and report one or two 'pattern not matched' errors

2021-11-22 19:49 UTC, desagar commented on tests/e2e/pkg/elasticsearch.go
> +	for _, hit := range hits.([]interface{}) {
our tests already print too much cruft. I think it's better to count the number and just print one error msg that says how many we found.

2021-11-22 20:24 UTC, shihchang commented on tests/e2e/pkg/elasticsearch.go
> +	for _, hit := range hits.([]interface{}) {
It did already print the count at line 322. I reduced the unexpected records from 10 to 5 as we will need these records to find out what caused the 'pattern not matched error' in the wls-server.log which could be huge.

2021-11-23 16:37 UTC, kminder commented on tests/e2e/pkg/elasticsearch.go
> +		if i < 5 {
Should this also break instead of spinning through the reminder of the hits?

2021-11-23 19:06 UTC, shihchang commented on tests/e2e/pkg/elasticsearch.go
> +		if i < 5 {
yes, fixed

2021-12-01 17:45 UTC, markxnelson requested changes
magic numbers

2021-12-01 17:50 UTC, shihchang commented on tests/e2e/pkg/elasticsearch.go
> +		if i < 5 {
It is the number of unexpected logs, or the "pattern not matched" logs, it would print out. So that we can locate the corresponding log entries in the huge adminserver.log. Some reviewer suggested we have already print/log too much so reduced from 10 to 5. We usually got 1 or 2; if we got more than 5, then the pattern should have obvious problem.

2021-12-01 20:44 UTC, markxnelson commented on application-operator/controllers/wlsworkload/weblogic_logging_test.go
> +
are these blank lines significant?

2021-12-01 20:45 UTC, markxnelson submitted a review, later dismissed

2021-12-01 20:49 UTC, shihchang commented on application-operator/controllers/wlsworkload/weblogic_logging_test.go
> +
no, removed.

2021-12-02 13:27 UTC, markxnelson approved these changes

2021-12-02 15:59 UTC, merged