VZ-4130: Update Verrazzano Custom Resource Definition for OCI logging configuration
verrazzano/verrazzano pull request #2039
Opened 2021-11-29 13:58 UTC by bhatpmk

# Description

Updates Verrazzano Custom Resource Definition for OCI logging configuration.

Fixes VZ-4130

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-11-29 15:52 UTC, fredtibbitts reviewed
This generally looks good to me, just a couple of minor comments. Also at one point the CRD existed in multiple places in the repo and we had to copy it, but maybe that's all been cleaned up now?

2021-11-29 15:52 UTC, fredtibbitts commented on platform-operator/controllers/verrazzano/installjob/install_config.go
> +	OCI                 OciLoggingConfiguration `json:"oci,omitempty"`
I'm wondering if this should be `*OciLoggingConfiguration` since it's optional? I think it's slightly better to be able to check for `nil` instead of looking for empty strings inside the struct to determine if the data exists.

2021-11-30 16:11 UTC, fredtibbitts approved these changes

2021-11-30 20:19 UTC, michael-cico commented on platform-operator/controllers/verrazzano/installjob/install_config.go
> +	Enabled             string                   `json:"enabled,omitempty"`
after my merge today, the install job no longer installs the Verrazzano chart (or fluentd).  Is this just the configuration/surface area?  Not the implementation to use the configuration?

2021-11-30 20:21 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
The field here seems like it could be ambigous... i.e., if we want to integrate with other OCI services, it seems that we will either have a conflict or inconsistent naming?

2021-11-30 20:27 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
I wonder if we need struct hook for different provider integrations, something like

```
Spec:
  CloudProvider *CloudProviderConfiguration {
     // Only one is valid at any time
     OCI *OCIConfiguration
     AWS *AWSConfiguration // someday
  }
...
}

type OCIConfiguration struct {
   Logging *OCILoggingConfiguration
}
```

or, alternatively, by function


```
Spec:
  Logging *LoggingConfiguration {
     // Only one is valid at any time
     OCI *OCILoggingConfiguration
     AWS *AWSLoggingConfiguration // someday
  }
...
}

type OCIConfiguration struct {
   Logging *OCILoggingConfiguration
}
```

2021-11-30 20:52 UTC, fredtibbitts commented on platform-operator/controllers/verrazzano/installjob/install_config.go
> +	Enabled             string                   `json:"enabled,omitempty"`
We were wondering if we even needed these installjob changes honestly. If we do need them, then we'll have to update to align with your changes Mike. We should chat offline.

2021-11-30 21:22 UTC, michael-cico commented on platform-operator/controllers/verrazzano/installjob/install_config.go
> +	Enabled             string                   `json:"enabled,omitempty"`
Sounds good.  I just merged those, so as long as nothing breaks we can chat tomorrow

2021-12-01 14:49 UTC, bhatpmk commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
After a discussion, we have decided to continue with the present change to support only OCI logging configuration.

2021-12-01 14:52 UTC, bhatpmk commented on platform-operator/helm_config/charts/verrazzano-platform-operator/crds/install.verrazzano.io_verrazzanos.yaml
> +                        - apiSecret
Done

2021-12-01 14:52 UTC, bhatpmk commented on platform-operator/controllers/verrazzano/installjob/install_config.go
> +	OCI                 OciLoggingConfiguration `json:"oci,omitempty"`
Done

2021-12-01 17:37 UTC, markxnelson requested changes

2021-12-01 17:37 UTC, markxnelson commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
that seems like it will just set us up to need to make a breaking change to the public api - what's the rationale for that decision?

2021-12-01 17:37 UTC, michael-cico approved these changes

2021-12-01 17:40 UTC, bobdonat commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
Is a field name of OCI descriptive enough?  Should it  be OCILoggingConfiguration or something like that

2021-12-01 19:15 UTC, fredtibbitts commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
There was some confusion around the placement of this field in the CR. It's under the "fluentd" component; it's not a top-level property. Bhat has implemented the API additions per the feature spec.

2021-12-01 23:35 UTC, fredtibbitts approved these changes

2021-12-01 23:42 UTC, fredtibbitts commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	OCI *OciLoggingConfiguration `json:"oci,omitempty"`
As discussed, the `OCI` field is in the `FluentdComponent`, so the name seems to be sufficient.

2021-12-02 14:44 UTC, markxnelson approved these changes

2021-12-03 12:46 UTC, merged