WIP: VZ-4122 rewrite Istio cert creation in go code
verrazzano/verrazzano pull request #2058
Opened 2021-12-01 15:40 UTC by pfmackin

WIP: Need more unit tests

Remove the bash scripts and openssl calls to create the Istio cert and write the code in go.

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-12-01 16:04 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/istio/istio_cert.go
> +// createCertSecret creates the secret with cert data used by Istio MTLS
Never mind, that's something separate we can try to do later.  I thought it might be easy, but I'm not sure if that'll be more work that what you've already done.

2021-12-02 18:14 UTC, wmhopkins requested changes
Overall, looks good. I think the serial number is being set incorrectly for the intermediate CA, and I'm wondering where newSerialNumber() is defined and what it does. Other than that, had some comments on cosmetic issues, but nothing else substantive.

2021-12-02 18:14 UTC, wmhopkins commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +func CreateSelfSignedCert(rootConfig CertConfig, intermConfig CertConfig) (*CertPemData, error) {
The name of this method is a little misleading -- it's actually creating a self-signed cert and then another, intermediate-CA cert.

2021-12-02 18:14 UTC, wmhopkins commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +		SerialNumber: rootResult.Cert.SerialNumber,
I think this is wrong -- the intermediate CA needs its own serial number, not the root cert's serial number. The serial number for the root cert can probably be random, but the serial number for the intermediate CA should be unique among all certs generated by the self-signed root. And given that the root *is* self-signed, maybe the root serial number should also be unique among all serials generated by that cert. That said, since we'll only ever generate those two certs, as long as the serial numbers are unique and different, that's probably OK. Only possible glitch would be if the intermediate CA expired, and we wanted to regenerate from the root, we'd need another unique serial number.

2021-12-02 18:14 UTC, wmhopkins commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +	privKey, err := rsa.GenerateKey(cryptorand.Reader, 4096)
We only want to do this if the parentPrivKey parameter is nil, correct?

2021-12-02 18:14 UTC, wmhopkins commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +func createCert(partialCert *x509.Certificate, parentCert *x509.Certificate, parentPrivKey *rsa.PrivateKey) (*CertResult, error) {
The partialCert param would be better named "csr", or maybe csrStruct, or tbsCert (To Be Signed) right? Is it not effectively a CSR?

2021-12-02 18:14 UTC, wmhopkins commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +	serialNumber, err := newSerialNumber()
Where is `newSerialNumber()` declared/defined?

2021-12-02 19:15 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +func CreateSelfSignedCert(rootConfig CertConfig, intermConfig CertConfig) (*CertPemData, error) {
I changed it to CreateCertUsingSelfSignedRoot

2021-12-02 19:20 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +	privKey, err := rsa.GenerateKey(cryptorand.Reader, 4096)
no we still need the private key for the intermediate cert so that it can be stored in the secret.  Also, it is needed to get the public key from it.

2021-12-02 19:22 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +func createCert(partialCert *x509.Certificate, parentCert *x509.Certificate, parentPrivKey *rsa.PrivateKey) (*CertResult, error) {
The type is x509.Certificate so it is not exactly a CSR but sort of acting like one.  I can call it CSR if that is clearer

2021-12-02 19:23 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +	serialNumber, err := newSerialNumber()
it is in with certificate.go, which already existed

2021-12-02 19:24 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +		SerialNumber: rootResult.Cert.SerialNumber,
fixed

2021-12-02 19:29 UTC, pfmackin commented on platform-operator/internal/k8s/certificate/selfsigned.go
> +func createCert(partialCert *x509.Certificate, parentCert *x509.Certificate, parentPrivKey *rsa.PrivateKey) (*CertResult, error) {
I am calling it certRequest

2021-12-02 20:29 UTC, wmhopkins approved these changes
lgtm.

2021-12-02 20:36 UTC, merged