VZ-4262: Add MetricsTemplate CRD and supporting generated code
verrazzano/verrazzano pull request #2096
Opened 2021-12-09 19:30 UTC by mbenmclean

This change adds the code to generate the MetricsTemplate CRD for the poko application model. It also includes generated deepcopy and clientset files. It creates poko as a new directory in application-operator/apis alongside clusters, oam, and weblogic. The poko name is likely to change but it is a placeholder for now. 

# Checklist 

As the author of this PR, I have:

- [x] Checked that I included or updated copyright and license notices in all files that I altered
- [x] Added or updated unit tests for any new functions I added
- [x] Added or updated integration tests if appropriate
- [x] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-12-09 19:53 UTC, mbenmclean commented on application-operator/apis/poko/v1alpha1/doc.go
> +// +groupName=poko.verrazzano.io
This is a placeholder since we agree this shouldn't be the final name

2021-12-09 19:57 UTC, mbenmclean commented on application-operator/apis/poko/v1alpha1/metricstemplates_types.go
> +	WorkloadSelector TargetWorkload   `json:"workloadSelector,omitempty"`
change to WorkloadSelector

2021-12-09 20:03 UTC, mbenmclean commented on application-operator/apis/poko/v1alpha1/metricstemplates_types.go
> +	Priority int `json:"priority,omitempty"`
resource.Quantity

2021-12-09 20:11 UTC, mbenmclean commented on application-operator/apis/poko/v1alpha1/doc.go
> +// +groupName=poko.verrazzano.io
Change to app

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	Spec MetricsTemplateSpec `json:"spec,omitempty"`
This field should be required (i.e. drop the omitempty)

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	WorkloadSelector WorkloadSelector `json:"workloadSelector,omitempty"`
I think that both of these fields should be required.

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	TargetConfigMap TargetConfigMap `json:"targetConfigMap,omitempty"`
I think this field should be required

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	ScrapeConfigTemplate string `json:"scrapeConfigTemplate,omitempty"`
If this field value cannot be defaulted, it should be required.

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	Namespace string `json:"namespace,omitempty"`
both these fields should probably be required

2021-12-10 10:33 UTC, mgianatagh commented on application-operator/internal/app/app.verrazzano.io_metricstemplates.yaml
> +
copyright header missing, we have scripts that should have automatically added that

2021-12-10 13:59 UTC, kminder requested changes

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/groupversion_info.go
> +	// SchemeGroupVersion is group version used to register these objects
is the

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/groupversion_info.go
> +	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
Go is trademarked so use Go
https://about.google/brand-resource-center/trademark-list/

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +// +kubebuilder:subresource:status
Status was removed so I don't think there should be a subresource for it.

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	PrometheusConfig PrometheusConfig `json:"prometheusConfig,omitempty"`
I think this should stay optional (i.e. omitempty).  There is a use case where a workload may want to explicitly reference a metrics template that results in opting out of the metrics template behavior.  This may be done so that later that template can be changed but the workload would not.

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	// ObjectSelector scopes the template to an object type
I'd say this scopes the template to specifically labeled object instances or something similar.  Specifically the apiGroups, apiVersions and resources fields are about object type.  This field is about object instances not object types.

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	// Resources scopes the template to listed workload types
I'd say object kinds here to be consistent with the objectSelector above.  I'm not sure we want to use workload in public docs.

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	ScrapeConfigTemplate string `json:"scrapeConfigTemplate,omitempty"`
I agree

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	// ScrapeConfigTemplate is the prometheus scrape target template to be added to the Prometheus Configmap
Suggestion below.  Note the capitalization of the trademarked Prometheus.
ScrapeConfigTemplate is a template for the Prometheus scrape job to be added to the Prometheus Configmap

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	Namespace string `json:"namespace,omitempty"`
+1

2021-12-10 13:59 UTC, kminder commented on application-operator/apis/app/v1alpha1/metricstemplates_types.go
> +	Name string `json:"name,omitempty"`
Make required

2021-12-10 15:07 UTC, mbenmclean commented on application-operator/internal/app/app.verrazzano.io_metricstemplates.yaml
> +
Oh yeah that makes sense

2021-12-10 17:05 UTC, kminder approved these changes
Approved

2021-12-10 17:21 UTC, kminder approved these changes

2021-12-10 17:57 UTC, merged