VZ-4545-update external-dns to 10.2
verrazzano/verrazzano pull request #2324
Opened 2022-01-18 16:10 UTC by theabmitra

# Description

Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another repository, please list those.

Fixes VZ-9999

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-01-18 16:24 UTC, markxnelson requested changes
you can't change master to use an image that is not publicly available

2022-01-24 16:00 UTC, michael-cico approved these changes

2022-01-24 16:12 UTC, desagar approved these changes

2022-01-24 16:45 UTC, markxnelson approved these changes

2022-01-24 16:50 UTC, merged