Private registry tests pipeline should support ephemeral Harbor instance
verrazzano/verrazzano pull request #2332
Opened 2022-01-18 22:57 UTC by pshirodkar-orcl

# Description

Adds support for ephemeral Harbor instance. Removes support for standalone harbor registry.

Fixes VZ-4272

# Checklist 

As the author of this PR, I have:

- [x] Checked that I included or updated copyright and license notices in all files that I altered
- [] Added or updated unit tests for any new functions I added
- [x] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-01-18 23:07 UTC, theabmitra commented on Jenkinsfile
> +def agentLabel = "largeexperimental"
General comment: This needs to be reverted once all tests are successful

2022-01-18 23:13 UTC, pshirodkar-orcl commented on Jenkinsfile
> +def agentLabel = "largeexperimental"
Yes waiting for current set of builds to pass. Once the builds are complete, I will proceed to revert the similar changes from all affected jenkins files.

2022-01-18 23:13 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  helm_zip="helm-v3.7.2-linux-amd64.tar.gz"
convert helm version into a global variable, so we can reuse this for later releases

2022-01-18 23:13 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  echo "Downloading helm 3.7.2 via command: curl -fsSL -o ${helm_zip} https://get.helm.sh/${helm_zip}"
use the variable to reference the version

2022-01-18 23:13 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +    echo "Error downloading helm 3.7.2"
use variable to reference helm version

2022-01-18 23:15 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  ./helm --kubeconfig=${KUBECONFIG} install ephemeral-harbor harbor/harbor \
convert harbor release into a global variable
HARBOR_RELEASE=ephemeral-harbor
helm install  ${HARBOR_RELEASE} ....

2022-01-18 23:15 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +    --set notary.enabled=false \
Remove space

2022-01-18 23:16 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  echo "waiting for contour to show up"
"Wait for contour pods to be up and running"

2022-01-18 23:18 UTC, theabmitra commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  docker login ${REGISTRY} -u ${PRIVATE_REGISTRY_USR} -p ${PRIVATE_REGISTRY_PSW}
This is being repeated before . Please remove

2022-01-18 23:22 UTC, theabmitra commented on tests/e2e/registry/registry_test.go
> +	harborEphemeral     = "Harbor ephemeral"
This should be only Harbor as we decided to remove other forms of Harbor

2022-01-18 23:23 UTC, theabmitra commented on tests/e2e/registry/registry_test.go
> +	if imageRegistrySelection == harborEphemeral {
this needs to be harbor and not harborEphemeral to be in sync with other descriptions

2022-01-18 23:31 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +    --set notary.enabled=false \
sorry which space are you referring to?

2022-01-18 23:36 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  helm_zip="helm-v3.7.2-linux-amd64.tar.gz"
Done

2022-01-18 23:36 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  echo "Downloading helm 3.7.2 via command: curl -fsSL -o ${helm_zip} https://get.helm.sh/${helm_zip}"
Done

2022-01-18 23:36 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +    echo "Error downloading helm 3.7.2"
Done

2022-01-18 23:36 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  ./helm --kubeconfig=${KUBECONFIG} install ephemeral-harbor harbor/harbor \
Done

2022-01-18 23:36 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  echo "waiting for contour to show up"
Done

2022-01-18 23:37 UTC, pshirodkar-orcl commented on ci/scripts/prepare_private_registry_jenkins_at_environment.sh
> +  docker login ${REGISTRY} -u ${PRIVATE_REGISTRY_USR} -p ${PRIVATE_REGISTRY_PSW}
Done. Removed.

2022-01-18 23:37 UTC, pshirodkar-orcl commented on tests/e2e/registry/registry_test.go
> +	harborEphemeral     = "Harbor ephemeral"
Done.

2022-01-20 17:27 UTC, pshirodkar-orcl commented on Jenkinsfile
> +def agentLabel = "largeexperimental"
With the jenkins agent templates configuration in place now, I have reverted the agent label in all the affected jenkinsfiles back to their original.

2022-01-21 13:02 UTC, michael-cico submitted a review, later dismissed

2022-01-21 13:17 UTC, markxnelson requested changes
please see comments in slack

2022-01-21 18:30 UTC, markxnelson requested changes
address unapproved third party items and resubmit please

2022-02-01 19:33 UTC, closed without merging