VZ-4616.  Add webhook validator for the Fluentd OCI config secret
verrazzano/verrazzano pull request #2346
Opened 2022-01-20 19:22 UTC by michael-cico

# Description

Add validation in the VPO validating wehbook for the Fluentd OCI config secret if present in the Verrazzano CR.

Fixes VZ-4616.

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-01-21 13:26 UTC, markxnelson requested changes
@wmhopkins can you please review this pr

2022-01-21 13:26 UTC, markxnelson commented on platform-operator/apis/verrazzano/v1alpha1/validate_test.go
> +	"crypto/rand"
this need security and thirdparty review

2022-01-21 13:51 UTC, fredtibbitts approved these changes
LGTM. It might be nice to have function header comments on some of the new functions, and there's one import grouping issue in the test file but not worth holding this up unless there are other changes required.

2022-01-21 14:13 UTC, pfmackin commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +		return fmt.Errorf("requested version %s does not match BOM version %s", requestedSemVer.ToString(), bomSemVer.ToString())
Messages start with capitalized word per new best practices

2022-01-21 14:13 UTC, pfmackin commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +			return fmt.Errorf("requested profile %s is invalid, valid options are dev, prod, or managed-cluster",
Messages start with capitalized word per new best practices

2022-01-21 14:15 UTC, fredtibbitts commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +		return fmt.Errorf("requested version %s does not match BOM version %s", requestedSemVer.ToString(), bomSemVer.ToString())
I had commented on a preliminary review that errors are supposed to start with lowercase letters, per https://github.com/golang/go/wiki/CodeReviewComments#error-strings. When did the guidance change?

2022-01-21 14:15 UTC, pfmackin commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +		return fmt.Errorf("requested version %s does not match BOM version %s", requestedSemVer.ToString(), bomSemVer.ToString())
Message should be in the form...
"Failed validating version.  Requested version..."

Please fix everywhere

2022-01-21 18:06 UTC, markxnelson approved these changes

2022-01-25 00:08 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/validate_test.go
> +	"crypto/rand"
Reviewed by Will & Mark, and approved

2022-01-25 00:23 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +		return fmt.Errorf("requested version %s does not match BOM version %s", requestedSemVer.ToString(), bomSemVer.ToString())
Fixed and pushed.

2022-01-25 00:23 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +			return fmt.Errorf("requested profile %s is invalid, valid options are dev, prod, or managed-cluster",
Fixed and pushed.

2022-01-25 21:49 UTC, fredtibbitts approved these changes

2022-01-25 22:57 UTC, pfmackin commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +// OCI DNS Secret Auth
Is this secret just for DNS or is used for any OCI access?

2022-01-25 22:59 UTC, pfmackin commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +func validateOCISecrets(client client.Client, spec *VerrazzanoSpec) error {
Is there 2 different secrets in the Verrazzano CR or is there just 1 secret used for 2 purposes?

2022-01-26 12:40 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +func validateOCISecrets(client client.Client, spec *VerrazzanoSpec) error {
2 different ones in different formats, expected by externa-dns/cert-manager and one for fluentd

2022-01-26 12:40 UTC, michael-cico commented on platform-operator/apis/verrazzano/v1alpha1/validate.go
> +// OCI DNS Secret Auth
Just OCI DNS

2022-01-26 12:41 UTC, merged