Stshapir/release 1.2 backport
verrazzano/verrazzano pull request #2701
Opened 2022-03-08 20:16 UTC by stevshap

# Description

Backporting changes from https://github.com/verrazzano/verrazzano/pull/2654 https://github.com/verrazzano/verrazzano/pull/2676 and https://github.com/verrazzano/verrazzano/pull/2689

Fixes VZ-3458

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-03-08 20:25 UTC, desagar requested changes
should not be merged until after 1.2.0 is released

2022-03-15 14:18 UTC, desagar commented on application-operator/controllers/clusters/multiclusterconfigmap/controller.go
> +		log.Infof("Multi-cluster application configuration resource %v should not be reconciled in kube-system namespace, ignoring", req.NamespacedName)
should be "ConfigMap", not "application configuration"

2022-03-15 14:28 UTC, desagar commented on application-operator/controllers/namespace/namespace_controller.go
> +	if req.Namespace == vzconst.KubeSystem {
AFAICT this controller is doing some OCI logging related reconciliation for a kubernetes namespace. Since a namespace cannot be in a namespace, I'm thinking that req.Namespace will always be empty.

What you want here is req.NamespacedName == vzconst.KubeSystem, to make sure the namespace passed in the request is not the kube-system namespace.

2022-03-15 15:11 UTC, bryantidd approved these changes

2022-03-15 16:03 UTC, merged