VZ-1181: Improve OLCNE install documentation
verrazzano/verrazzano pull request #271
Opened 2020-09-11 13:47 UTC by kminder

2020-09-13 23:39 UTC, mark-au requested changes

2020-09-13 23:39 UTC, mark-au commented on install/install-olcne.md
> +  The Verrazzano system requires 5 persistent volumes for itself.
Other sections of the document spell out numbers less than ten, I'd suggest 5, 4, 9 in this paragraph be done the same way

2020-09-13 23:39 UTC, mark-au commented on install/install-olcne.md
> +  The OLCNE operator node is typically used to install Verrazzano.
I'm told we're not allowed to abbreviate Oracle product names in documentation. I'd personally keep using OLCNE in your tables as that'd decrease readability. I'd reduce the number of times you use the term and spell it in its entirety when you need it

2020-09-13 23:39 UTC, mark-au commented on install/install-olcne.md
> +If load balancers are not created the management and application user interfaces will need to be accessed by IP address.
I thought load balancers were now mandatory as the installation procedure makes calls to Rancher

2020-09-14 13:12 UTC, kminder commented on install/install-olcne.md
> +      |No       |10.0.1.0/24|TCP     |All         |8472             |           |Flannel              |
Will fix.

2020-09-14 13:14 UTC, kminder commented on install/install-olcne.md
> +  The Verrazzano system requires 5 persistent volumes for itself.
Will fix.

2020-09-14 13:21 UTC, kminder commented
@mark-au < Made suggested changes.  Please re-review.

2020-09-14 21:53 UTC, mark-au approved these changes

2020-09-16 20:56 UTC, merged