VZ-5683-OS-component
verrazzano/verrazzano pull request #2956
Opened 2022-04-19 18:48 UTC by mbenmclean

This change moves Opensearch and Opensearch Dashboard out of the verrazzano component and into its own top level component. It is not a helm component and instead simply calls a createVMI function that creates or updates the OS and OSD components during install or upgrade.
This change likewise removes OS and OSD from the verrazzano createVMI function. It updates the unit tests in each directory according.
It also adds a change to the the createVMI logic by overwriting changes to the master node storage only when the master node replicas are not zero.

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-04-19 19:56 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func findStorageOverride(effectiveCR *vzapi.Verrazzano) (*verrazzano.ResourceRequestValues, error) {
func is duplicated across packages?

2022-04-19 19:58 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +	if !vzconfig.IsVMOEnabled(ctx.EffectiveCR()) {
a lot of this func is duplicated across the components

2022-04-19 19:59 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +func newVMI() *vmov1.VerrazzanoMonitoringInstance {
duplicated function

2022-04-19 20:00 UTC, anders-swanson requested changes
Looks like it will work, there's just a ton of duplicated code. Please clean up the duplicated code

2022-04-19 20:01 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	if vzconfig.IsElasticsearchEnabled(old) && !vzconfig.IsElasticsearchEnabled(new) {
consider renaming these functions to IsOpenSearchEnabled

2022-04-19 20:26 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func findStorageOverride(effectiveCR *vzapi.Verrazzano) (*verrazzano.ResourceRequestValues, error) {
Yeah I'm going to fix

2022-04-19 21:24 UTC, kminder commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +// ComponentName is the name of the component
Orphaned comment?

2022-04-19 21:54 UTC, kminder commented
Can you confirm that all of these new files are largely code extracted from other existing files?  Basically meaning that the code is already proven and just be relocated?

2022-04-20 14:26 UTC, mbenmclean commented
Yes there's were all taken originally from the verrazzano component. I've made changes since then though mainly deleting stuff or pulling new stuff in

2022-04-20 16:49 UTC, bobdonat commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	// +optional
Why is this change needed and only to the ElasticsearchComponent

2022-04-20 16:50 UTC, bobdonat commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	// +optional
Without this change there is no need for a new version of zz-generated.deepcopy.go

2022-04-20 19:15 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func findStorageOverride(effectiveCR *vzapi.Verrazzano) (*verrazzano.ResourceRequestValues, error) {
fixed

2022-04-20 19:15 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +func newVMI() *vmov1.VerrazzanoMonitoringInstance {
fixed

2022-04-20 19:18 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +// ComponentName is the name of the component
fixed

2022-04-22 15:12 UTC, mbenmclean commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	// +optional
I think we decided we were going to remove the monitoring component all together.

2022-04-22 15:15 UTC, bobdonat commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	// +optional
We decided to leave as and address as a follow up task

2022-04-22 15:18 UTC, bobdonat commented on platform-operator/constants/constants.go
> +const VMIBackupScrtName = "verrazzano-backup"
for consistency should spell out Secret instead of Scrt

2022-04-22 15:18 UTC, bobdonat commented on platform-operator/constants/constants.go
> +const ObjectstoreAccessSecretKey = "object_store_secret_key"
Should these be ObjectStore... instead of Objectstore

2022-04-22 15:25 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
This function looks identical to isOpenSearchInstalled

2022-04-22 15:27 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) PostUpgrade(ctx spi.ComponentContext) error {
This function is identical to previous function

2022-04-22 15:32 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/verrazzano/vmi.go
> +	storage, err := common.FindStorageOverride(ctx.EffectiveCR())
Since this createVMI function is duplicated across the three comopnents with minor changes, can you make a function like:
```
createVMI(ctx spi.ComponentContext, updateFunc func() error) error { ... }
```


The update func would do the body of the createOrUpdate that is different between the components.

2022-04-22 15:33 UTC, mbenmclean commented on platform-operator/constants/constants.go
> +const VMIBackupScrtName = "verrazzano-backup"
fixed

2022-04-22 15:34 UTC, mbenmclean commented on platform-operator/constants/constants.go
> +const ObjectstoreAccessSecretKey = "object_store_secret_key"
fixed

2022-04-22 15:36 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
They're not, they call a DoesExist function vs an IsReady function

2022-04-22 15:36 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) PostUpgrade(ctx spi.ComponentContext) error {
Same as above

2022-04-22 15:40 UTC, bobdonat commented on platform-operator/internal/k8s/status/deployment_ready.go
> +// DoDeploymentsExist check that the named deployments have the minimum number of specified replicas ready and available
What is the purpose of this function?  The description is not accurate and the function above may do what is needed.

2022-04-22 15:41 UTC, bobdonat commented on platform-operator/internal/k8s/status/statefulset_ready.go
> +// DoStatefulSetsExist check that the named statefulsets have the minimum number of specified replicas ready and available
What is the purpose of this function? The description is not accurate and the function above may do what is needed.

2022-04-22 15:41 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
So the difference between these two function calls - could we refactor to pass these functions in as args?

2022-04-22 15:43 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) PostUpgrade(ctx spi.ComponentContext) error {
The common logic can be put in a function

2022-04-22 15:46 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
but the rest of the logic is identical.

2022-04-22 16:48 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName}
OSD needs to be dependent on VMO
the istio and nginx dependencies will need to be removed

2022-04-22 16:49 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName}
OS needs to be dependent on VMO
the istio and nginx dependencies will need to be removed

2022-04-22 17:36 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
Let me double check

2022-04-22 19:17 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchReady(ctx spi.ComponentContext) bool {
Combined code

2022-04-22 19:28 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) PostUpgrade(ctx spi.ComponentContext) error {
fixec

2022-04-22 19:29 UTC, mbenmclean commented on platform-operator/internal/k8s/status/deployment_ready.go
> +// DoDeploymentsExist check that the named deployments have the minimum number of specified replicas ready and available
It checks if the deployment exists. I fixed the comment

2022-04-22 19:29 UTC, mbenmclean commented on platform-operator/internal/k8s/status/statefulset_ready.go
> +// DoStatefulSetsExist check that the named statefulsets have the minimum number of specified replicas ready and available
It checks if the deployment exists. I fixed the comment

2022-04-22 19:34 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch.go
> +func isOpenSearchInstalled(ctx spi.ComponentContext) (bool, error) {
This is normally implemented as part of the HelmComponent interface, but this is not a helm component. So yes we need it it is checked as part of the upgrade loop.

2022-04-22 19:34 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName}
fixed

2022-04-26 20:44 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	ctx.Log().Debugf("OpenSearch component post-upgrade")
still is wrong debug string

2022-04-26 20:46 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/vmi.go
> +var updateFunc common.VMIMutateFunc = func(ctx spi.ComponentContext, storage *common.ResourceRequestValues, vmi *vmov1.VerrazzanoMonitoringInstance, existingVMI *vmov1.VerrazzanoMonitoringInstance) e
Any reason why this is a var?

2022-04-26 20:54 UTC, bobdonat commented on platform-operator/apis/verrazzano/v1alpha1/verrazzano_types.go
> +	// +optional
This is half done this way.  If we are going to remove use of MonitoringComponent then we should remove it all.  This can be done in a follow-up PR.

2022-04-26 20:59 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) GetMinVerrazzanoVersion() string {
This minimum version can be removed

2022-04-26 21:02 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName, vmo.ComponentName}
opensearch needs to work without istio and nginx dependencies

2022-04-26 21:12 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/vmo/vmo.go
> -func reassociateResources(ctx spi.ComponentContext) error {
If this is shared, should it be in the common package?

2022-04-26 21:14 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName, vmo.ComponentName}
followup task

2022-04-26 21:14 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) GetMinVerrazzanoVersion() string {
followup task

2022-04-26 21:17 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	return constants.VerrazzanoVersion1_3_0
same comment as opensearch-component

2022-04-26 21:17 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName, vmo.ComponentName}
same comment as opensearch-component

2022-04-26 21:23 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	if vzconfig.IsKibanaEnabled(ctx.EffectiveCR()) {
This probably doesn't need to be calculated, we did that before when it was part of the VZ component because the set of ingresses could change based on what was enabled.  You can just set the IngressNames field on the component struct most likely.

2022-04-26 21:24 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	if err := common.EnsureBackupSecret(ctx.Client()); err != nil {
Should this just be set up by the VMO?  Or do we want to do it only when a VMI component is enabled?

2022-04-26 21:27 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	if vzconfig.IsElasticsearchEnabled(ctx.EffectiveCR()) {
same comment here as with the dashboards component.

2022-04-26 21:32 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/vmo/vmo_component.go
> +	return c.HelmComponent.Install(context)
why call install here?  I made some changes recently where HelmComponent.Upgrade should be equivalent, plus the call to get the current values if they exist.  If calling the current values returns an "release not found" error we should just not append those to the overrides.

The reason I think we should call Upgrade if possible is that if we don't align the install/upgrade paths before the next release, we'll want to call upgrade at that point.

If it helps, I'm OK with that being a separate PR.

2022-04-26 21:35 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/common/vmi.go
> +func CreateVMI(ctx spi.ComponentContext, updateFunc VMIMutateFunc) error {
Should probably call this `CreateOrUpdateVMI`

2022-04-26 21:36 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/vmi.go
> +var updateFunc common.VMIMutateFunc = func(ctx spi.ComponentContext, storage *common.ResourceRequestValues, vmi *vmov1.VerrazzanoMonitoringInstance, existingVMI *vmov1.VerrazzanoMonitoringInstance) e
I thought that's how you do it to cast the type as VMIMutateFunc.

2022-04-26 21:36 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/common/vmi.go
> +func EnsureVMISecret(cli client.Client) error {
Nit, probably want to add some function comments for this and the others in this file

2022-04-26 21:37 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) GetMinVerrazzanoVersion() string {
The component interface requires that each component defines that function. I suppose we could return empty string. Might be good practice to set though.

2022-04-26 21:38 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	return []string{istio.ComponentName, nginx.ComponentName, vmo.ComponentName}
Yeah that's part of another story. Out of scope for this change

2022-04-26 21:38 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/common/vmi.go
> +func CreateAndLabelVMINamespaces(ctx spi.ComponentContext) error {
What's getting labeled?  Or is that happening in the CreateVerrazzanoSystemNamespace func?

2022-04-26 21:39 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/vmo/vmo.go
> -func reassociateResources(ctx spi.ComponentContext) error {
Yeah this was a quick fix while we were trying to get it working. It requires reworking some unit tests to move to common. I'll probably do as a second pass if that's cool.

2022-04-26 21:39 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	return constants.VerrazzanoVersion1_3_0
Same response

2022-04-26 21:39 UTC, bobdonat commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) GetMinVerrazzanoVersion() string {
I don't think that is true.  Most components do not specify the min version

2022-04-26 21:40 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	if vzconfig.IsKibanaEnabled(ctx.EffectiveCR()) {
Good point, I'll change.

2022-04-26 21:41 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +var updateFunc common.VMIMutateFunc = func(ctx spi.ComponentContext, storage *common.ResourceRequestValues, vmi *vmov1.VerrazzanoMonitoringInstance, existingVMI *vmov1.VerrazzanoMonitoringInstance) e
Probably in line with Anders' comment elsewhere, this probably doesn't need to be a var, it can be passed in as a callback as long as the signature matches the formal parameter signature.

Unless it's a var so it can be overridden during unit testing.

2022-04-26 21:42 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
> +		if err := common.ApplyCRDYaml(ctx, config.GetHelmVmoChartsDir()); err != nil {
should this be happening in the VMO component?

2022-04-26 21:48 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	if err := common.EnsureBackupSecret(ctx.Client()); err != nil {
We only want to do this when there are VMI components that use it I assume. Maybe it should be in the VMO but currently the VPO still does a lot of work setting up the monitoring stack components like this.

2022-04-26 21:50 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +	if vzconfig.IsElasticsearchEnabled(ctx.EffectiveCR()) {
fixed

2022-04-26 21:51 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/common/vmi.go
> +func CreateVMI(ctx spi.ComponentContext, updateFunc VMIMutateFunc) error {
Ok i agree

2022-04-26 21:59 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +var updateFunc common.VMIMutateFunc = func(ctx spi.ComponentContext, storage *common.ResourceRequestValues, vmi *vmov1.VerrazzanoMonitoringInstance, existingVMI *vmov1.VerrazzanoMonitoringInstance) e
So just define in place when I call CreateVMI?

2022-04-26 22:02 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
> +		if err := common.ApplyCRDYaml(ctx, config.GetHelmVmoChartsDir()); err != nil {
No because the Verrazzano component has to upgrade first because it needs to apply its network policies, but it also needs the VMI CRD which is in the VMO component. It's kind of hack but it's what we're going with for now.

2022-04-26 22:13 UTC, anders-swanson submitted a review, later dismissed

2022-04-27 11:35 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearch/vmi.go
> +var updateFunc common.VMIMutateFunc = func(ctx spi.ComponentContext, storage *common.ResourceRequestValues, vmi *vmov1.VerrazzanoMonitoringInstance, existingVMI *vmov1.VerrazzanoMonitoringInstance) e
I think you can define it as a named func, and just pass in the name of the func where needed as an argument.  If the signatures don't match then the compiler will complain.

2022-04-27 11:36 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/opensearchdashboards/opensearchdashboards_component.go
> +	if err := common.EnsureBackupSecret(ctx.Client()); err != nil {
no, this makes sense I think.

2022-04-27 11:37 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/vmo/vmo.go
> -func reassociateResources(ctx spi.ComponentContext) error {
Yup, no worries

2022-04-27 11:38 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/verrazzano/verrazzano_component.go
> +		if err := common.ApplyCRDYaml(ctx, config.GetHelmVmoChartsDir()); err != nil {
Probably need to move those policies to the VMO chart/comp.  But not for this change.

2022-04-28 20:11 UTC, bobdonat approved these changes

2022-04-28 20:14 UTC, merged

2022-04-28 21:26 UTC, mbenmclean commented on platform-operator/controllers/verrazzano/component/opensearch/opensearch_component.go
> +func (o opensearchComponent) GetMinVerrazzanoVersion() string {
Yes because they're helm components so the helm component interface does that for them