VZ-5597 Uptake WebLogic Operator 3.4
verrazzano/verrazzano pull request #2991
Opened 2022-04-22 21:28 UTC by bryantidd

# Description

Uptake WebLogic Operator 3.4

Fixes VZ-5597

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-04-26 12:38 UTC, mgianatagh commented on application-operator/apis/weblogic/v8/fluentd_spec.go
> +// Copyright (c) 2020, 2022, Oracle and/or its affiliates.
Only 2022, is needed for a new file

2022-04-26 12:55 UTC, bobdonat requested changes
Updated helm chart and new operator image is needed

2022-04-27 12:44 UTC, kminder approved these changes
Aapproved.

2022-04-27 12:47 UTC, bobdonat approved these changes

2022-04-27 18:04 UTC, pfmackin approved these changes

2022-04-28 11:27 UTC, merged