VZ-5076 Cleanup errors in AuthProxy log during install
verrazzano/verrazzano pull request #3107
Opened 2022-05-09 14:47 UTC by ayaranga

# Description

Added code to return Service Unavailable error (503) from AuthProxy for 5xx errors from Keycloak. 

Fixes VZ-5076

# Checklist 

As the author of this PR, I have:

- [x] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-05-09 16:06 UTC, wmhopkins requested changes

2022-05-09 16:06 UTC, wmhopkins commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +        if res.status >= 500 then
While this change addresses the specific issue reported in the Jira, what's wanted here is more general error handling. Anything other than a 200 status code indicates a problem getting the token, and therefore a failure of this method and a failure to authenticate the user. So I would change the condition here to `res.status != 200`.

Also, this should return unauthorized, rather than service_unavailable. While 503 may accurately reflect the nature of the problem for some cases (not necessarily everything >= 500), the context here is that we're trying to authenticate a user. If we fail for any reason, we should always return 401. This tells the user what the high-level problem is, from their POV, without leaking any information that could potentially help someone trying to break into the system. The log message will be enough for an admin to see what's going on.

2022-05-09 16:17 UTC, wmhopkins requested changes

2022-05-09 16:17 UTC, wmhopkins commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            me.service_unavailable("Error requesting token: response status code was "..res.status)
Would be good to be consistent in logging both status and body in both places (I think it ends up in the same log with different levels, so may be redundant when debug is enabled, but there's not much point in logging one without the other.)

2022-05-09 17:48 UTC, wmhopkins approved these changes
lgtm.

2022-05-10 03:35 UTC, anajosep approved these changes

2022-05-10 04:40 UTC, merged