VZ-1426: Add error checking for openssl commands in install script
verrazzano/verrazzano pull request #348
Opened 2020-10-29 18:39 UTC by speidelj

Added error checking for openssl commands in v8o install script.
Now if an openssl command fails, the script will fail and provide an error message.
Also, made a change to generate temporary artifacts into a temp directory instead of the previous directory under build.
The temp directory is now cleaned up via a signal trap instead of on the last line of the script to guarantee that the cleanup will occur even in the event of a failure.

2020-10-29 20:03 UTC, markxnelson requested changes
target branch must be develop, not master

2020-10-30 15:09 UTC, jmaron99 commented on install/3-install-verrazzano.sh
> +  if ! openssl genrsa -out $TMP_DIR/ca.key 2048 ; then
why can't lines 88 and 89 be combined?

2020-10-30 15:10 UTC, speidelj commented on install/3-install-verrazzano.sh
> +  if ! openssl genrsa -out $TMP_DIR/ca.key 2048 ; then
good catch Jon, thanks

2020-10-30 15:17 UTC, speidelj commented
> target branch must be develop, not master

Thanks Mark, fixed.

2020-10-30 15:21 UTC, jmaron99 approved these changes

2020-10-30 15:24 UTC, markxnelson approved these changes

2020-10-30 23:03 UTC, merged