VZ-6079 Changes for exposing Jaeger URL as part of VZ CR
verrazzano/verrazzano pull request #3509
Opened 2022-07-07 04:05 UTC by anajosep

VZ-6079 Changes for exposing Jaeger URL

Provide SSO support for Jaeger UI URL and expose it throug VZ CR in the status fields along with the URLs of other components.

2022-07-12 06:20 UTC, ayaranga commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            serverUrl = 'http://jaeger-operator-jaeger-query.verrazzano-monitoring.svc.cluster.local:16686'
For the first cut, this maybe fine. Eventually, it would be better to get query service similar to what we do in our istio component to get collector service https://github.com/verrazzano/verrazzano/blob/master/platform-operator/controllers/verrazzano/component/istio/jaeger.go#L52-L67

2022-07-12 06:20 UTC, ayaranga commented on platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator_component.go
> +// createOrUpdateKialiResources create or update related Kiali resources
nit: Update comment to reflect Jaeger

2022-07-12 07:39 UTC, ayaranga submitted a review, later dismissed

2022-07-12 07:44 UTC, ayaranga commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            serverUrl = 'http://jaeger-operator-jaeger-query.verrazzano-monitoring.svc.cluster.local:16686'
Thinking more, the Jaeger Operator name is used in multiple places (authpolicy, service account name..). It is better we add a validation not to change the name than addressing in all the places.

2022-07-12 15:05 UTC, michael-cico commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            serverUrl = 'http://jaeger-operator-jaeger-query.verrazzano-monitoring.svc.cluster.local:16686'
To @anajosep 's point, it may be hard to do that since this is lua code.  All the other services are hard-coded.  

You'd have to maybe use Go templates and massage the lua script code in the configmap at build time, which is beyond the scope of this PR I think.

2022-07-12 15:07 UTC, michael-cico commented on platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
> +	openSearchURL         = "http://verrazzano-authproxy-elasticsearch.verrazzano-system.svc.cluster.local:8775"
Does Jaeger only run in a cluster with OS?  i.e., will it run in a managed cluster where OS is not present?  Or is this just the Jaeger UI that will only run in admin clusters?

2022-07-12 15:19 UTC, michael-cico submitted a review, later dismissed

2022-07-12 15:30 UTC, wmhopkins requested changes
In general looks fine to me, but would like to see a utility method to generate the backend URL, see my comment to that effect.

2022-07-12 17:12 UTC, pfmackin commented on platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
> +	openSearchURL         = "http://verrazzano-authproxy-elasticsearch.verrazzano-system.svc.cluster.local:8775"
that is a good question, this won't work on managed cluster.  I do think Jaeger should be on the managed cluster

2022-07-13 13:43 UTC, kminder commented on platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
> +		ingress.Annotations["nginx.ingress.kubernetes.io/proxy-body-size"] = "6M"
Hard coding some of these seems like a problem.
Is there no way to source these from Helm values?

2022-07-13 13:46 UTC, kminder commented
Can you please confirm that this Jaeger status and URL information looks ok with the new VZ CLI?

2022-07-13 15:59 UTC, wmhopkins submitted a review, later dismissed

2022-07-13 15:59 UTC, wmhopkins commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            elseif backend == 'jaeger' then
Are we sure we don't have any in-cluster user cases? Don't think the "if in_cluser == true" block above will work for things that aren't running in verrazzano-system namespace.

2022-07-13 16:46 UTC, anajosep commented
> Can you please confirm that this Jaeger status and URL information looks ok with the new VZ CLI?

The Jaeger URL was missing in the template. I fixed that and now the output looks like below:
`
$ vz status
Verrazzano Status
  Name: dev
  Namespace: default
  Version: 1.4.0-local+79fe9cde
  State: Ready
  Profile: dev
  Access Endpoints:
    Console URL: https://verrazzano.default.172.18.0.231.nip.io
    Grafana URL: https://grafana.vmi.system.default.172.18.0.231.nip.io
    Jaeger URL: https://jaeger.default.172.18.0.231.nip.io
    Keycloak URL: https://keycloak.default.172.18.0.231.nip.io
    Kiali URL: https://kiali.vmi.system.default.172.18.0.231.nip.io
    Kibana URL: https://kibana.vmi.system.default.172.18.0.231.nip.io
    OpenSearch URL: https://elasticsearch.vmi.system.default.172.18.0.231.nip.io
    Prometheus URL: https://prometheus.vmi.system.default.172.18.0.231.nip.io
    Rancher URL: https://rancher.default.172.18.0.231.nip.io
`

2022-07-15 12:41 UTC, anajosep commented on platform-operator/helm_config/charts/verrazzano-authproxy/templates/verrazzano-authproxy-configmap.yaml
> +            elseif backend == 'jaeger' then
Only the Jaeger Query/UI component is exposed via the Ingress through Auth proxy. The `jaeger-collector`  component is what other services inside the cluster communicate to and it does not go via the Verrazzano auth proxy. `jaeger-collector` component is protected through appropriate Authorization policy and Network Policy. There aren't any ingresses for the `jaeger-collector`, it receives the spans from services inside the cluster and pushes it to storage (OpenSearch).  `jaeger-query` and `jaeger-ui` reads data from OS and displays it.

2022-07-15 16:09 UTC, anajosep commented on platform-operator/controllers/verrazzano/component/jaeger/operator/jaeger_operator.go
> +		ingress.Annotations["nginx.ingress.kubernetes.io/proxy-body-size"] = "6M"
I followed the approach followed by other ingress resources like prometheus.

2022-07-15 16:15 UTC, ayaranga approved these changes

2022-07-18 02:52 UTC, merged