VZ-6432 Add e2e tests for VPO
verrazzano/verrazzano pull request #3701
Opened 2022-07-26 19:09 UTC by GeorgeAeillo

- End to End Tests for VPO Metrics
-  Changes to Network Policy Configuration for VPO 
Checklist

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered

- [ ] Added or updated unit tests for any new functions I added

- [ ] Added or updated integration tests if appropriate

- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria

- [ ] Does not introduce unrelated or spurious changes

- [ ] Does not introduce any unapproved dependency

- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2022-07-26 19:44 UTC, anders-swanson requested changes
See comments for ideas how to reduce duplication.

2022-07-26 19:44 UTC, anders-swanson commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			Eventually(func() bool {
Can you create a `WhenUsingVZMetrics` function that performs the common logic you have in each spec, something like this: https://github.com/verrazzano/verrazzano/blob/master/tests/e2e/verify-install/kiali/kiali_test.go#L43

It'll help reduce your duplication. Additionally you may also consider a function `EventuallyMetricsContainLabels(key string, labels map[string]string)` that parameterizes these eventually blocks.

2022-07-26 20:38 UTC, zabdulre commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			Eventually(func() bool {
The way my e2e is setup, I set the isMinVersion140 variable in the beforeSuite just once. My tests then look like this,

`			if isMinVersion140 {
				Eventually(...)
			}`

2022-07-26 20:38 UTC, zabdulre commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			Eventually(func() bool {
is this an acceptable alternative?

2022-07-26 20:46 UTC, GeorgeAeillo commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			Eventually(func() bool {
Thanks! I just made these changes and pushed them.

2022-07-26 20:58 UTC, mbenmclean commented on platform-operator/helm_config/charts/verrazzano/templates/networkpolicy.yaml
> +    - from:
Why are you modifying the charts for an e2e testing PR? Is this required for the pipelines?

2022-07-26 20:58 UTC, mbenmclean commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +func WhenUsingVZMetricsIt(description string, f interface{}) {
If all you are checking for is the VZ version, I think we already have MinVersionIt functions. Probably best to use that rather than create your own It just for this test. See the ItMinimumVersion function.

2022-07-26 20:58 UTC, mbenmclean commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +func EventuallyMetricsContainLabels(metricName string) {
Does this need to an exported function? If it's not used outside of this package just make it a local function.

2022-07-26 20:58 UTC, mbenmclean commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			EventuallyMetricsContainLabels("vpo_reconcile_duration_count")
Try to make these It's look like the "Verify sample NGINX metrics can be queried from Prometheus" It above, or change the one above to look like yours. Either way make it consistent.

2022-07-26 21:44 UTC, davisgomes commented on platform-operator/helm_config/charts/verrazzano/templates/networkpolicy.yaml
> +    - from:
This is the application operator network policy. I think these should be included in Raaghav's changes unless it is blocking

2022-07-27 14:27 UTC, GeorgeAeillo commented on platform-operator/helm_config/charts/verrazzano/templates/networkpolicy.yaml
> +    - from:
Thanks! I removed it in my latest commit.

2022-07-27 14:28 UTC, GeorgeAeillo commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +func WhenUsingVZMetricsIt(description string, f interface{}) {
Thanks! I used the itMinimumVersion function in my latest commit.

2022-07-27 14:29 UTC, GeorgeAeillo commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +func EventuallyMetricsContainLabels(metricName string) {
Thanks! I made it a local function in my latest commit.

2022-07-27 14:30 UTC, GeorgeAeillo commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +			EventuallyMetricsContainLabels("vpo_reconcile_duration_count")
Thanks! I edited the two tests above my new tests to look consistent with my new tests.

2022-07-27 15:56 UTC, stevshap approved these changes

2022-07-27 15:57 UTC, davisgomes commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +		t.ItMinimumVersion("Verify VPO summary counter metrics can be queried from Prometheus", "1.4.0", kubeConfig, func() {
Does the `eventuallyMetricsContainLabels` have to be wrapped in the func() or can you pass it in directly?

2022-07-27 16:03 UTC, davisgomes approved these changes

2022-07-27 16:04 UTC, GeorgeAeillo commented on tests/e2e/metrics/syscomponents/metrics_test.go
> +		t.ItMinimumVersion("Verify VPO summary counter metrics can be queried from Prometheus", "1.4.0", kubeConfig, func() {
It does not appear that I can pass it in directly, I tried passing it in directly and was getting errors. In other examples of the itMinimumVersion function used, it is wrapped in the funct()

2022-07-27 16:16 UTC, anders-swanson approved these changes
LGTM

2022-07-27 16:19 UTC, merged