VZ-6572: Update base profiles to use v1beta1 API
verrazzano/verrazzano pull request #3912
Opened 2022-08-22 12:33 UTC by Abhijithang

Provide a summary of the change and which issue (i.e. ticket) is fixed.
If there are any dependencies, for example on a PR in another repository, list those.

2022-08-22 14:33 UTC, anders-swanson commented on platform-operator/internal/config/config.go
> +func GetProfileV1alpha1(profile string) string {
thought, can you write a function that is like
```
func GetProfile(groupVersion schema.GroupVersion, profile string) {
...
}
```
And the profile path is known from the GroupVersion information? Every API has a GroupVersion object exported.

2022-08-22 14:46 UTC, Abhijithang commented on platform-operator/internal/config/config.go
> +func GetProfileV1alpha1(profile string) string {
Makes sense, thanks Anders. Will do that now.

2022-08-22 15:33 UTC, Abhijithang commented on platform-operator/internal/config/config.go
> +func GetProfileV1alpha1(profile string) string {
Done.

2022-08-22 16:06 UTC, anders-swanson commented on platform-operator/manifests/profiles/v1beta1/base.yaml
> +      elasticsearchURL: "http://verrazzano-authproxy-elasticsearch:8775"
This is not v1beta1

2022-08-22 16:06 UTC, anders-swanson commented on platform-operator/manifests/profiles/v1beta1/base.yaml
> +      ingress:
this is not v1beta1

2022-08-22 16:06 UTC, anders-swanson requested changes
Can you evaluate the v1beta1 profiles again with the changes that have been made in the API, and write some tests which validate they are as expected?

2022-08-25 19:55 UTC, Abhijithang commented on platform-operator/manifests/profiles/v1beta1/base.yaml
> +      elasticsearchURL: "http://verrazzano-authproxy-elasticsearch:8775"
Made the changes.

2022-08-25 19:56 UTC, Abhijithang commented on platform-operator/manifests/profiles/v1beta1/base.yaml
> +      ingress:
> Can you evaluate the v1beta1 profiles again with the changes that have been made in the API, and write some tests which validate they are as expected?

Sure, evaluated and added the unit tests. Thanks.

2022-08-25 20:00 UTC, anders-swanson commented on platform-operator/apis/verrazzano/v1alpha1/testdata/base/v1alpha1.yaml
> +# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
`Copyright (c) 2022,`

2022-08-25 20:00 UTC, anders-swanson commented on platform-operator/apis/verrazzano/v1alpha1/testdata/base/v1beta1.yaml
> +# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
fix copyright

2022-08-25 20:13 UTC, anders-swanson commented on platform-operator/manifests/profiles/v1beta1/prod.yaml
> +      installArgs:
these have to be OpenSearch Nodes. I meant not to include the default _empty_ node array created by conversion.

2022-08-25 20:13 UTC, anders-swanson commented on platform-operator/manifests/profiles/v1beta1/dev.yaml
> +      installArgs:
Need to include nodes (can skip empty nodes)

2022-08-25 20:13 UTC, anders-swanson commented on platform-operator/apis/verrazzano/v1alpha1/testdata/prod/v1beta1.yaml
> +      installArgs:
there should be no install args in v1beta1

2022-08-25 20:14 UTC, anders-swanson commented on platform-operator/apis/verrazzano/v1alpha1/testdata/dev/v1beta1.yaml
> +      installArgs:
no install args in v1beta1

2022-08-25 21:03 UTC, Abhijithang commented on platform-operator/apis/verrazzano/v1alpha1/testdata/base/v1beta1.yaml
> +# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
Done.

2022-08-25 21:03 UTC, Abhijithang commented on platform-operator/manifests/profiles/v1beta1/prod.yaml
> +      installArgs:
Include the nodes, need you to verify once again.

2022-08-25 21:03 UTC, Abhijithang commented on platform-operator/manifests/profiles/v1beta1/dev.yaml
> +      installArgs:
Done. Need your review again.

2022-08-25 21:03 UTC, Abhijithang commented on platform-operator/apis/verrazzano/v1alpha1/testdata/prod/v1beta1.yaml
> +      installArgs:
Removed.

2022-08-25 21:04 UTC, Abhijithang commented on platform-operator/apis/verrazzano/v1alpha1/testdata/dev/v1beta1.yaml
> +      installArgs:
Sorry about that, done.

2022-08-30 20:52 UTC, anders-swanson approved these changes

2022-08-30 21:58 UTC, anders-swanson approved these changes

2022-08-30 22:26 UTC, merged