Add OAM support to Platform Installer
verrazzano/verrazzano pull request #402
Opened 2020-12-03 21:35 UTC by ddrechse

2020-12-03 22:33 UTC, pfmackin commented on operator/scripts/install/3-install-verrazzano.sh
> +  log "Add Weblogic Operator helm repository"
Is this going to conflict with the WebLogic operator that is currently deployed per app?

2020-12-03 22:37 UTC, pfmackin commented on operator/scripts/install/chart/crds/oam.verrazzano.io_ingresstraits.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
How are these CRDs getting into the Verrazzano repo if the OAM repo changes them.  Are folks expected to manually copy?

2020-12-03 22:37 UTC, pfmackin commented on operator/scripts/install/chart/templates/05-verrazzano-application-operator.yaml
> +  name: verrazzano-application
all of the OAM App Operator kubernetes resources should be in verrazzano-system

2020-12-03 22:43 UTC, pfmackin commented on operator/scripts/install/chart/templates/05-verrazzano-application-operator.yaml
> +# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
Instead of having all these n-chart.yaml files it might be better to have nested charts.  It certainly would be cleaner.

2020-12-03 22:47 UTC, pfmackin commented on operator/scripts/install/3-install-verrazzano.sh
>  action "Creating admission controller cert" create_admission_controller_cert || exit 1
I don't see where the uninstall of OAM runtime and WebLogic is called

2020-12-17 13:58 UTC, kminder requested changes

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/3-install-verrazzano.sh
> +  helm install oam --namespace oam-system crossplane-master/oam-kubernetes-runtime --devel
We need to switch this to installing a specific version (e.g.   helm install oam --namespace "${NAMESPACE}" crossplane-master/oam-kubernetes-runtime --version 0.3.0)

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/3-install-verrazzano.sh
> +  kubectl create namespace oam-system
There is other work going on to consolidate things into the verrazzano-system namespace.  Therefore this should be removed and verrazzano-system used for the namespace below.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/3-install-verrazzano.sh
> +  kubectl create clusterrolebinding cluster-admin-binding-oam --clusterrole cluster-admin --user system:serviceaccount:oam-system:oam-kubernetes-runtime-oam
I think the oam-system here is a namespace so it will need to be changed to verrazzano-system.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/3-install-verrazzano.sh
> +  log "Add Weblogic Operator helm repository"
In our testing we have not seen it conflict with the "per app" WLS operator.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/3-install-verrazzano.sh
> +  kubectl create namespace weblogic-operator
This should also go into the verrazzano-system namespace.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
> +  kubectl delete ns weblogic-operator
namespace

2020-12-17 13:58 UTC, kminder commented on operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
> +  kubectl delete clusterrole oam-kubernetes-runtime-oam:system:aggregate-to-controller
Should we be doing a `helm delete oam ...` instead of or in addition to these delete?

2020-12-17 13:58 UTC, kminder commented on operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
> +  log "Delete oam-system namespace"
Should use verrazzano-system so don't delete that here.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/chart/crds/oam.verrazzano.io_ingresstraits.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
Copying the CRDs into `operator/scripts/install/chart/crds` seems to be the direction things are heading as the model/binding CRDs are currently being copied here.  I agree that this might need some more thought but for this change we should not break the pattern.

2020-12-17 13:58 UTC, kminder commented on operator/scripts/install/chart/values.yaml
> +  imageVersion: local-e626d89
What is this imageVersion and where does it come from?

2020-12-18 00:33 UTC, pfmackin commented on operator/scripts/install/chart/values.yaml
> +  imageName: iad.ocir.io/weblogicondocker/verrazzano-application-operator-dev
this imageName should be ghcr.io.  We will also need a temp secret to access it.  Check with @mgianatagh

2020-12-18 00:34 UTC, pfmackin commented on operator/scripts/uninstall/uninstall-steps/3-uninstall-verrazzano.sh
> +  kubectl delete clusterrole oam-kubernetes-runtime-oam:system:aggregate-to-controller
helm delete is done at line 81, but it doesn't delete those other resources for some reason.

2021-02-19 20:02 UTC, closed without merging