Add disablefirstlogin method
verrazzano/verrazzano pull request #4337
Opened 2022-10-08 15:47 UTC by rahulsrivastava71

Code is added to disable the first login page for VZ customer because currently the bootstrap admin password which shows on ui is not correct and this setting is created from rancher code itself , so to remove this better remove the first login page .

Provide a summary of the change and which issue (i.e. ticket) is fixed.
If there are any dependencies, for example on a PR in another repository, list those.

2022-10-10 06:17 UTC, lake-of-dreams requested changes
We only need to add logic for calling `disableFirstLogin` , pls remove all Keycloak auth related changes

2022-10-10 06:21 UTC, bhatpmk commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +	if err := configureAuthProviders(ctx); err != nil {
Is this change porting the Rancher-Keycloak integration to release-1.3 ?

2022-10-10 06:30 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +	if err := configureAuthProviders(ctx); err != nil {
yes

2022-10-10 12:59 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +	if err := disableFirstLogin(ctx); err != nil {
This needs to be called from `PostUpgrade` as well..

2022-10-12 11:17 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +	if err := disableFirstLogin(ctx); err != nil {
where is this postupgrade method ? is it in upgrade_component.go

2022-11-01 05:26 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +	KontainerDriverOKE = "oraclecontainerengine"
why these are still here?

2022-11-01 05:26 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +var GVKNodeDriver = common.GetRancherMgmtAPIGVKForKind("NodeDriver")
you don't need GVKs for NodeDriver and KontainerDriver

2022-11-01 05:27 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +		log.Debugf("Rancher IsReaactivateOCIDriverdy: Failed getting config: %v", err)
why is this changed?

2022-11-01 05:30 UTC, lake-of-dreams commented on tests/e2e/pkg/rancher.go
> +func GvkToGvr(gvk schema.GroupVersionKind) schema.GroupVersionResource {
if only your test is using this function, just make it a part of that test file only, no need to separate out here if its nit being used elsewhere

2022-11-01 05:32 UTC, lake-of-dreams commented on tests/e2e/verify-infra/restapi/rancher_url_test.go
> +				verifySettingValue("first-login", "false", k8sClient)
call this after `metrics.emit`

2022-11-01 05:33 UTC, lake-of-dreams commented on tests/e2e/pkg/rancher.go
> +func GvkToGvr(gvk schema.GroupVersionKind) schema.GroupVersionResource {
or just leave it, will be easy to write any further tests if we had to

2022-11-01 05:52 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +func (r rancherComponent) PostUpgrade(ctx spi.ComponentContext) error {
so `PostUpgrade` did not exist at all? I am just wondering if we should add it here at all if there was no `PostUpgrade` before?

2022-11-02 05:23 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +	KontainerDriverOKE = "oraclecontainerengine"
removed

2022-11-02 05:23 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +var GVKNodeDriver = common.GetRancherMgmtAPIGVKForKind("NodeDriver")
removed

2022-11-02 05:24 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher.go
> +		log.Debugf("Rancher IsReaactivateOCIDriverdy: Failed getting config: %v", err)
done

2022-11-02 05:24 UTC, rahulsrivastava71 commented on tests/e2e/pkg/rancher.go
> +func GvkToGvr(gvk schema.GroupVersionKind) schema.GroupVersionResource {
sure

2022-11-02 05:25 UTC, rahulsrivastava71 commented on tests/e2e/verify-infra/restapi/rancher_url_test.go
> +				verifySettingValue("first-login", "false", k8sClient)
done

2022-11-02 05:26 UTC, rahulsrivastava71 commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component.go
> +func (r rancherComponent) PostUpgrade(ctx spi.ComponentContext) error {
no there was no post upgrade in 1.3 , but we can add as rancher setting is added in 1.3 so lets keep this here

2022-11-02 05:29 UTC, lake-of-dreams commented on tests/e2e/verify-infra/restapi/rancher_url_test.go
> +				k8sClient, err := pkg.GetDynamicClientInCluster(kubeconfigPath)
it should fail if error in getting the k8sclient

2022-11-02 05:58 UTC, rahulsrivastava71 commented on tests/e2e/verify-infra/restapi/rancher_url_test.go
> +				k8sClient, err := pkg.GetDynamicClientInCluster(kubeconfigPath)
done

2022-11-02 06:22 UTC, lake-of-dreams submitted a review, later dismissed

2022-11-02 06:24 UTC, lake-of-dreams commented on platform-operator/controllers/verrazzano/component/rancher/rancher_component_test.go
> +	//authConfig := createKeycloakAuthConfig()
remove this commented line

2022-11-02 10:31 UTC, lake-of-dreams commented on tests/e2e/pkg/rancher.go
> +// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
change to `// Copyright (c) 2022, Oracle and/or its affiliates.`

2022-11-02 10:35 UTC, rahulsrivastava71 commented on tests/e2e/pkg/rancher.go
> +// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
done

2022-11-04 07:17 UTC, merged