0 replica case fix for grafana component : t0
verrazzano/verrazzano pull request #4338
Opened 2022-10-10 10:04 UTC by absBitm

Fix : Grafana component never be ready and install/upgrade will never finish during replica count is 0 .

2022-10-10 11:57 UTC, anajosep commented on pkg/k8s/status/deployment_ready.go
> +	if namespacedName.Namespace == constants.VerrazzanoSystemNamespace && namespacedName.Name == constants.GrafanaIngress && *deployment.Spec.Replicas == 0 {
Do we need this check ? since you have already added a check in `isGrafanaReady` method.

2022-10-10 14:07 UTC, anders-swanson commented on pkg/k8s/status/deployment_ready.go
> +	if namespacedName.Namespace == constants.VerrazzanoSystemNamespace && namespacedName.Name == constants.GrafanaIngress && *deployment.Spec.Replicas == 0 {
Should not be changed here

2022-10-10 14:07 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/grafana/grafana.go
> +	if *ctx.EffectiveCR().Spec.Components.Grafana.Replicas == 0 {
nil dereference

2022-10-10 14:18 UTC, anders-swanson requested changes
see comments, also consider we must fix this generically. if 0 replicas are requested for the deployment, it does not make sense to wait for it to be ready. 
We can check the spec of the deployment to find out how many replicas there should be, and wait for at most 1 replica.

2022-10-12 06:25 UTC, absBitm commented on pkg/k8s/status/deployment_ready.go
> +	if namespacedName.Namespace == constants.VerrazzanoSystemNamespace && namespacedName.Name == constants.GrafanaIngress && *deployment.Spec.Replicas == 0 {
this method could be invoked from multiple components, I guess right now we should focus on Grafana fix and make this change generic later on

2022-10-12 07:56 UTC, absBitm commented
@anders-swanson 

Let Say, N no. of replicas is requested from the vz grafana CR

- case-1 : if N<1 ; return true from isGrafanaReady (skip waiting for pods=expected_replica to be ready) 
- case-2 : if N>=1 ; go ahead to check deployments have the minimum number of specified replicas (expectedReplicas) ready and available

Here in case-2, 
A) should we check deployment has expectedReplicas = N no of replicas followed by its number of pods must match N
B) or should we check deployment has expectedReplicas >= 1 replica followed by its number of pods must match 1 atleast

2022-10-12 08:10 UTC, absBitm commented on platform-operator/controllers/verrazzano/component/grafana/grafana.go
> +	if *ctx.EffectiveCR().Spec.Components.Grafana.Replicas == 0 {
corrected

2022-10-14 13:43 UTC, anders-swanson commented on platform-operator/controllers/verrazzano/component/grafana/grafana.go
> +		expectedReplicas = *ctx.EffectiveCR().Spec.Components.Grafana.Replicas
Should use 1 as expected replicas if not nil

2022-10-14 16:35 UTC, absBitm commented on platform-operator/controllers/verrazzano/component/grafana/grafana.go
> +		expectedReplicas = *ctx.EffectiveCR().Spec.Components.Grafana.Replicas
please check now

2022-10-14 17:33 UTC, anders-swanson approved these changes
lgtm

2022-10-17 11:38 UTC, merged