Fix diagnostic URL for bug-report
verrazzano/verrazzano pull request #4747
Opened 2022-11-16 11:07 UTC by saidu941

Provide a summary of the change and which issue (i.e. ticket) is fixed.
If there are any dependencies, for example on a PR in another repository, list those.

2022-11-17 09:14 UTC, bhatpmk commented on Jenkinsfile
> +                    def analysisurl="https://verrazzano.io/" + env.VERRAZZANO_VERSION + "/docs/troubleshooting/diagnostictools/analysisadvice/"
You need to consider only major and minor version with prefix "v" and without dot (.) between major and minor version. The version in .verrazzano-development-version includes the patch as well.

Links to versioned doc is available here https://verrazzano.io/archive/docs/

2022-11-17 09:16 UTC, bhatpmk commented on Jenkinsfile
> +def setEffectiveDocsVersion() {
Move the logic to a shell script, and return true / false from there to set the environment variable in Jenkinsfile.

2022-11-17 20:04 UTC, saidu941 commented on Jenkinsfile
> +def setEffectiveDocsVersion() {
Updated PR with the changes

2022-11-17 20:04 UTC, saidu941 commented on Jenkinsfile
> +                    def analysisurl="https://verrazzano.io/" + env.VERRAZZANO_VERSION + "/docs/troubleshooting/diagnostictools/analysisadvice/"
Updated the PR

2022-11-18 13:08 UTC, agv426 commented on Jenkinsfile
> +                    sh "chmod +x ${WORKSPACE}/ci/scripts/derive_v8o_doc_stage.sh"
set the script as executable and push it into source control that way, then remove this chmod from all the spots you are doing it at runtime

2022-11-18 13:11 UTC, agv426 commented on ci/scripts/derive_v8o_doc_stage.sh
> +if [ -z "$1" ]; then
this could be callable outside of Jenkins as well for user's local builds.

You could have it explicitly check for VERRAZZANO_DEV_VERSION being set and give a usage message that it needs to be set to use this.

Thinking that we should be able to do this for local builds as well

2022-11-18 15:59 UTC, saidu941 commented on ci/scripts/derive_v8o_doc_stage.sh
> +if [ -z "$1" ]; then
Addressed and updated the PR

2022-11-18 16:08 UTC, saidu941 commented on Jenkinsfile
> +                    sh "chmod +x ${WORKSPACE}/ci/scripts/derive_v8o_doc_stage.sh"
Addressed and updated the PR

2022-11-18 16:35 UTC, agv426 commented on ci/kind/Jenkinsfile
> +                    env.VERRAZZANO_VERSION = "${VERRAZZANO_DEV_VERSION}"
Is env.VERRAZZANO_VERSION needed?

2022-11-18 17:22 UTC, agv426 approved these changes

2022-11-29 15:51 UTC, agv426 submitted a review, later dismissed

2022-11-30 07:48 UTC, lake-of-dreams requested changes
Maybe this might have been discussed before but I find it weird and counterintuitive to pass the VERRAZZANO_DEV_VERSION via Jenkins to some shell script which then is executed to  further creates a new environment variable USE_V8O_DOC_STAGE  which are being used in code for tools that should function as standalone cli's? 
I mean why can't the code in cli directly
1. make a http connection to https://raw.githubusercontent.com/verrazzano/verrazzano/master/.verrazzano-development-version and figure out erstwhile VERRAZZANO_DEV_VERSION, and deduce `docsVersion` and then
2. make a http connection to https://verrazzano.io/$docsVersion/docs/troubleshooting/diagnostictools/analysisadvice and see if it returns 404
Do we expect user to set `USE_V8O_DOC_STAGE` before running these cli's ?

2022-11-30 10:30 UTC, agv426 commented on tools/vz/cmd/version/version.go
> -	if os.Getenv("USE_V8O_DOC_STAGE") == "true" || len(cliVersion) == 0 {
When did this get changed, we must NOT rely on the USE_V8O_DOC_STAGE for normal cases, it only exists as an optional override in developer environments on the main line where there is no versioned doc released for it yet so we can form "deve" links

The normal case is that the environment variable does not exist and the CLI here will know the version it was built with and will use the versioned doc links that will exist for the released version

2023-03-03 14:20 UTC, closed without merging