Multi Artifact Build Initial Checkin
verrazzano/verrazzano pull request #490
Opened 2021-01-07 18:14 UTC by ddrechse

2021-01-07 19:31 UTC, markxnelson requested changes

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +# Bob's Books
is this duplicated here? update the existing one, don't duplicate

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +The Coherence YAML file is slightly different from Verrazzano Bob's model.  The YAML file used for OAM has to specify
what is "Verrazzano Bob's model" ????

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +The Bobby application has four components: a WebLogic domain, a Helidon service, a Helidon pod, and a Coherence cluster.
what is "The Bobby application"?

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +The difference is that OAM Bobby places the WebLogic CR YAML file after the `workload` element, whereas Verrazzano demo-model
this whole thing is too colloquial and narrative
@rosemarymarano please review

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +    description: "Robert"
"Robert's Books" ???

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +    - componentName: robert-coh
why abbreviate coherence to coh?

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +                    - "*"
examples should not use * host :(

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +    description: "Bobby front-end"
Bobby's Books front-end web application ???

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +                - hosts:
dont use * host

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +    description: "Bob's order manager wls"
WebLogic is a trademark, we do not abbreviate it
Order Manager should be capitalized too

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +                    - "*"
no * host

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-comp.yaml
> +          image: "container-registry.oracle.com/verrazzano/example-roberts-helidon-stock-application:0.1.10-3-7508985-127"
update to newer 0.1.11-1 image please

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-comp.yaml
> +      image: "container-registry.oracle.com/verrazzano/example-bobs-books-order-manager:0.1.10-3-e5ae893-124"
update to newer 0.1.11-1 image please

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +  echo "ERROR: Github container registry username required as first argument or GHCR_USER environment variable."
GitHub Container Registry - spell product names/trademarks correctly

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +_create_generic_secret bobbys-front-end-runtime-encrypt-secret "--from-literal=password=welcome1" "weblogic.domainUID=bobbys-front-end"
remove hardcoded credentials

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/README.md
> +TODO: This assumes that you have built the Coherence example app image separately, for now we have a pre-built version in OCIR. Move Coherence example image out of OCIR and put source somewhere. Upda
remove todo (i.e. do it...)

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/README.md
> +(TODO:  Note that it is assumed that Istio is already installed through the Verrazzano installation.  Will we install Istio here?)
get rid of all todos - won't repeat this comment

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/README.md
> +    Via: 1.1 10.197.160.116 (McAfee Web Gateway 7.7.2.16.0.26564)
these look like real ip addresses.... need to obfuscate them

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +# Example 3
what's this mean?

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +      image: phx.ocir.io/stevengreenberginc/tvlatas/deployment-example:3.1.1
internal name!

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +      image: phx.ocir.io/stevengreenberginc/tvlatas/deployment-example:3.1.1
internal name

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +      image: phx.ocir.io/stevengreenberginc/tvlatas/deployment-example:3.1.1
internal name

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/hello-helidon/README.md
> +1. Create a Kubernetes cluster. A single node OKE cluster using the VM Standard 1.4 shape is recommended.
spell the name of the shape right, and backtick it

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/hello-helidon/README.md
> +1. Install the [Verrazzano Application Operator](https://gitlab-odx.oracledx.com/verrazzano/verrazzano-application-operator/-/tree/master#installing-the-oam-runtine-and-the-verrazzano-application-ope
internal name

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/examples/hello-helidon/hello-helidon-app.yaml
> +                    - "*"
no * host

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/ignore_copyright_check.txt
> +# Copyright (c) 2020, Oracle and/or its affiliates.
delete this and consolidate content into the top level one

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/1-install-oam-runtime.sh
> +  log "Add OAM helm repository"
Helm is spelled wrong

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/2-install-wls-operator.sh
> +function install_wls_operator {
just use the helm chart, why all this???

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/3-install-coh-operator.sh
> +  log "Update the helm repository"
spelling Helm

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/common.sh
> +#
hashbang line?

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/logging.sh
> +#
hashbang

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/installer/scripts/logging.sh
> +# Function used for EXIT (ie ^C) trap.
is this our original code, or is it copied?  if the latter, from where? needs approval and attribution

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/internal/certificates/certificates.go
> +			CommonName: commonName,
set SANS too

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/test/integ/integ-1-test-result.xml
> +          <failure type="Failure">/Users/ddrechse/go/src/github.com/verrazzano/verrazzano/oam-application-operator/test/integ/integ_test.go:33&#xA;Error creating Kubernetes client to access Verrazzan
internal name

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/test/integ/integ_test.go
> +	It("applicationconfigurations.core.oam.dev exists", func() {
you could use a table here

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/test/templates/containerized_workload_deployment.yaml
> +status:
depending on how this is used .. it is almost certainly overkill, status, timestamps, etc., probably ought not be here

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/test/templates/wls_domain.yaml
> +  image: ghcr.io/verrazzano/example-bobbys-front-end:0.1.10-3-20201016220428-56fb4d4
internal name!!!

2021-01-07 19:31 UTC, markxnelson commented on oam-application-operator/test/templates/wls_pod.yaml
> +      image: ghcr.io/verrazzano/example-bobbys-front-end:0.1.10-3-20201016220428-56fb4d4
internal name

2021-01-07 19:31 UTC, markxnelson commented on operator/THIRD_PARTY_LICENSES.txt
> +-------- Copyrights
needs to be one consolidated one at the root level

2021-01-08 21:14 UTC, ddrechse commented on Jenkinsfile
>                      cd ${GO_REPO_PATH}/verrazzano
done

2021-01-08 22:14 UTC, kminder commented on oam-application-operator/.verrazzano-development-version
> +# Copyright (C) 2020, Oracle and/or its affiliates.
Fixed in kminder/vz1943

2021-01-08 22:15 UTC, kminder commented on oam-application-operator/Makefile
> +GO ?= GO111MODULE=on GOPRIVATE=github.com/verrazzano go
Fixed in kminder/vz1943

2021-01-08 22:15 UTC, kminder commented on oam-application-operator/PROJECT
> +# Copyright (C) 2020, Oracle and/or its affiliates.
Fixed in kminder/vz1943

2021-01-08 22:15 UTC, kminder commented on oam-application-operator/apis/oam/v1alpha1/groupversion_info.go
> +// Copyright (c) 2020, Oracle and/or its affiliates.
Fixed in kminder/vz1943

2021-01-08 22:16 UTC, kminder commented on oam-application-operator/apis/oam/v1alpha1/ingresstrait_webhook.go
> +	// For "exact" hosts such as "foo.oracle.com"
Fixed in kminder/vz1943

2021-01-08 22:16 UTC, kminder commented on oam-application-operator/config/crd/bases/oam.verrazzano.io_ingresstraits.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
We wrote it.

2021-01-08 22:16 UTC, kminder commented on oam-application-operator/config/crd/bases/oam.verrazzano.io_loggingscopes.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
We wrote it.

2021-01-08 22:17 UTC, kminder commented on oam-application-operator/controllers/ingresstrait/ingresstrait_controller.go
> +// Reconcile reconciles a IngressTrait to an Ingress object.
Fixed in kminder/vz1943

2021-01-08 22:17 UTC, kminder commented on oam-application-operator/controllers/webhooks/logging_scope_defaulter_test.go
> +// an error that has a StatusNotFound status
Fixed in kminder/vz1943

2021-01-08 22:18 UTC, kminder commented on oam-application-operator/test/templates/wls_domain.yaml
> +  image: ghcr.io/verrazzano/example-bobbys-front-end:0.1.10-3-20201016220428-56fb4d4
Fixed in kminder/vz1943

2021-01-08 22:18 UTC, kminder commented on oam-application-operator/test/templates/wls_pod.yaml
> +      image: ghcr.io/verrazzano/example-bobbys-front-end:0.1.10-3-20201016220428-56fb4d4
Fixed in kminder/vz1943

2021-01-11 14:41 UTC, kminder commented on oam-application-operator/Makefile
> +	echo 'Load docker image for the fake hello app...'
Fixed in kminder/vz1943

2021-01-11 14:42 UTC, kminder commented on oam-application-operator/README.md
> +export VERRAZZANO_APP_OP_IMAGE=ghcr.io/verrazzano/verrazzano-application-operator-jenkins:0.5.0-20201030125421-f7e021b
Fixed in kminder/vz1943

2021-01-11 14:43 UTC, kminder commented on oam-application-operator/apis/oam/v1alpha1/loggingscope_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
Fixed in kminder/vz1943

2021-01-11 14:48 UTC, kminder commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +  echo "ERROR: Github container registry username required as first argument or GHCR_USER environment variable."
Fixed in kminder/vz1943

2021-01-11 14:50 UTC, kminder commented on oam-application-operator/apis/oam/v1alpha1/ingresstrait_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
Fixed in kminder/vz1943

2021-01-11 14:52 UTC, kminder commented on oam-application-operator/examples/bobs-books/bobs-books-app.yaml
> +    description: "Bob's order manager wls"
Fixed in kminder/vz1943

2021-01-11 15:25 UTC, kminder commented on oam-application-operator/installer/scripts/1-install-oam-runtime.sh
> +  log "Add OAM helm repository"
Fixed in kminder/vz1943

2021-01-11 15:25 UTC, kminder commented on oam-application-operator/installer/scripts/3-install-coh-operator.sh
> +  log "Update the helm repository"
Fixed in kminder/vz1943

2021-01-11 15:29 UTC, kminder commented on oam-application-operator/installer/scripts/common.sh
> +#
The common.sh has never had a hashbang line.  It is always intended to be sourced.

2021-01-11 15:30 UTC, kminder commented on oam-application-operator/installer/scripts/logging.sh
> +#
This has never had a hashbang line as it is intended to be sourced.

2021-01-11 15:31 UTC, kminder commented on oam-application-operator/installer/scripts/logging.sh
> +# Function used for EXIT (ie ^C) trap.
This is our original code.

2021-01-11 15:57 UTC, kminder commented on oam-application-operator/test/integ/integ-1-test-result.xml
> +          <failure type="Failure">/Users/ddrechse/go/src/github.com/verrazzano/verrazzano/oam-application-operator/test/integ/integ_test.go:33&#xA;Error creating Kubernetes client to access Verrazzan
@ddrechse I don't think this file is supposed to be checked in.

2021-01-11 16:09 UTC, kminder commented on oam-application-operator/examples/coherence-app/README.md
> +    Via: 1.1 10.197.160.116 (McAfee Web Gateway 7.7.2.16.0.26564)
Fixed in kminder/vz1943

2021-01-11 16:56 UTC, kminder commented on oam-application-operator/installer/scripts/2-install-wls-operator.sh
> +function install_wls_operator {
This is the way that the WebLogic documentation recommends installing the operator.
https://oracle.github.io/weblogic-kubernetes-operator/quickstart/install/
It is unclear if the explicit creation of the service account is absolutely required.

2021-01-11 16:57 UTC, kminder commented on oam-application-operator/internal/certificates/certificates.go
> +			CommonName: commonName,
Fixed in kminder/vz1943

2021-01-11 17:37 UTC, kminder commented on Jenkinsfile
>                      cd ${GO_REPO_PATH}/verrazzano
Fixed in later commit.

2021-01-12 18:20 UTC, ddrechse commented on oam-application-operator/Dockerfile
> +# Copy the operator binary
done

2021-01-12 18:21 UTC, ddrechse commented on oam-application-operator/Jenkinsfile
> +// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
Done

2021-01-12 18:22 UTC, ddrechse commented on oam-application-operator/LICENSE.txt
> +Copyright (c) 2020 Oracle America, Inc. and its affiliates.
DOne

2021-01-12 20:40 UTC, markxnelson commented on oam-application-operator/.verrazzano-development-version
> +verrazzano-development-version=0.5.0
shouldn't this be 0.8.0?

2021-01-12 20:40 UTC, markxnelson commented on oam-application-operator/Dockerfile
> +# Copy the operator binary
we can leave this as-is for the initial merge and fix it later

2021-01-12 20:43 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-comp.yaml
> +          image: "container-registry.oracle.com/verrazzano/example-roberts-helidon-stock-application:0.1.10-3-7508985-127"
mustfix

2021-01-12 20:44 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/bobs-books-comp.yaml
> +      image: "container-registry.oracle.com/verrazzano/example-bobs-books-order-manager:0.1.10-3-e5ae893-124"
mustfix

2021-01-12 20:44 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +_create_generic_secret bobbys-front-end-runtime-encrypt-secret "--from-literal=password=welcome1" "weblogic.domainUID=bobbys-front-end"
mustfix

2021-01-12 20:44 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +      image: phx.ocir.io/stevengreenberginc/tvlatas/deployment-example:3.1.1
mustfix

2021-01-12 20:44 UTC, markxnelson commented on oam-application-operator/examples/coherence-app/comp-sampleapp-coh.yaml
> +      image: phx.ocir.io/stevengreenberginc/tvlatas/deployment-example:3.1.1
mustfix

2021-01-12 20:46 UTC, markxnelson commented on oam-application-operator/examples/hello-helidon/README.md
> +1. Install the [Verrazzano Application Operator](https://gitlab-odx.oracledx.com/verrazzano/verrazzano-application-operator/-/tree/master#installing-the-oam-runtine-and-the-verrazzano-application-ope
mustfix

2021-01-12 20:46 UTC, markxnelson commented on oam-application-operator/test/integ/integ-1-test-result.xml
> +          <failure type="Failure">/Users/ddrechse/go/src/github.com/verrazzano/verrazzano/oam-application-operator/test/integ/integ_test.go:33&#xA;Error creating Kubernetes client to access Verrazzan
mustfix

2021-01-12 20:46 UTC, markxnelson commented on operator/THIRD_PARTY_LICENSES.txt
> +-------- Copyrights
defer this until after first merge

2021-01-13 21:32 UTC, closed without merging