Remove use of creds in examples scripts
verrazzano/verrazzano pull request #502
Opened 2021-01-12 19:13 UTC by desagar

2021-01-12 19:39 UTC, markxnelson commented on .gitignore
> +build/
update copyright notice

2021-01-12 19:40 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +WEBLOGIC_PASS=welcome1 MYSQL_PASS=WebLogic1234 ./install-bobs-books.sh <ghcr username> <ghcr password> <ocr username> <ocr password>
you need to add a comment in here to say something like "Oracle recommends that you use a more secure password" ping @rosemarymarano

2021-01-12 19:41 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +  echo "ERROR: Oracle container registry password required as MYSQL_PASS environment variable."
`Oracle Container Registry` is a product name and must have the capitals

2021-01-12 19:41 UTC, markxnelson commented on oam-application-operator/examples/todo/install-todo.sh
> -set -u
i don't understand why this change is here?

2021-01-12 19:42 UTC, markxnelson commented on oam-application-operator/examples/todo/install-todo.sh
>  echo "Create weblogic secrets."
please fix this while you are here - WebLogic

2021-01-12 19:42 UTC, markxnelson requested changes
a few updates needed please

2021-01-12 19:44 UTC, rosemarymarano commented on oam-application-operator/examples/bobs-books/README.md
> +WEBLOGIC_PASS=welcome1 MYSQL_PASS=WebLogic1234 ./install-bobs-books.sh <ghcr username> <ghcr password> <ocr username> <ocr password>
For guidance, see the NOTE here, https://verrazzano.io/docs/guides/lift-and-shift/

2021-01-12 20:11 UTC, desagar commented on oam-application-operator/examples/todo/install-todo.sh
> -set -u
This was moved down a few lines to _after_ the -z checks on environment variables

2021-01-12 20:22 UTC, desagar commented on oam-application-operator/examples/todo/install-todo.sh
> -set -u
Otherwise, instead of the error we painstakingly wrote, we get a cryptic "unbound variable"

2021-01-12 20:48 UTC, desagar commented on .gitignore
> +build/
done

2021-01-12 20:48 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> +WEBLOGIC_PASS=welcome1 MYSQL_PASS=WebLogic1234 ./install-bobs-books.sh <ghcr username> <ghcr password> <ocr username> <ocr password>
done

2021-01-12 20:50 UTC, desagar commented on oam-application-operator/examples/bobs-books/install-bobs-books.sh
> +  echo "ERROR: Oracle container registry password required as MYSQL_PASS environment variable."
Oracle Container Registry should not have been in this message at all - it was a mistake. Thanks for catching it - fixed

2021-01-12 20:50 UTC, desagar commented on oam-application-operator/examples/todo/install-todo.sh
>  echo "Create weblogic secrets."
fixed

2021-01-12 20:56 UTC, markxnelson commented on oam-application-operator/examples/bobs-books/README.md
> +WEBLOGIC_PASS=welcome1 MYSQL_PASS=WebLogic1234 ./install-bobs-books.sh <ghcr username> <ghcr password> <ocr username> <ocr password>
@rosemarymarano are you ok with this verbiage? can you approve if so, thanks

2021-01-12 20:56 UTC, markxnelson approved these changes

2021-01-12 21:28 UTC, rosemarymarano reviewed
For some reason, I was able only to put comments in two places. So, the second comment has edits for the rest of the README document. If you have any questions about to which text lines I am referring, please ask me and I'll clarify.

2021-01-12 21:28 UTC, rosemarymarano commented on oam-application-operator/examples/bobs-books/README.md
> -Alternatively, you can specify the credentials in environment variables: `GHCR_USER`, `GHCR_PASS`, `OCR_USER`, and `OCR_PASS`. When the installation completes, the script will output URLs you can use
will output URLs -> will print out URLs that you can use to access the applications.

2021-01-12 21:28 UTC, rosemarymarano commented on oam-application-operator/examples/bobs-books/README.md
> +    **NOTE:** You should use more secure passwords.
Create a secret for Oracle Container Registry -> Create a secret for the Oracle Container Registry
Create a secret for GitHub Container Registry -> Create a secret for the GitHub Container Registry.
Locate the external IP -> Locate the external IP address.
Access the applications. -> Access the applications. In the following examples, replace the IP address with the external IP address assigned to your gateway. (That way, you don't have to repeat this sentence three times.)
Also, the sub-bulleted items should be labeled a. b. and c. (Not i. ii. and iii., as they are now.)
Robert Application Details -> Robert's Books Application Details
The Robert application -> The Robert's Books application (make this change globally)
demonstrates three type of OAM resources -> demonstrates three types of OAM resources
ContainerizedWorkload in the component -> ContainerizedWorkload, (comma) in the component
from Verrazzano Bob's model -> from the Verrazzano Bob's Book model
Bobby Application -> Bobby's Books Application (globally)
Bob's Books demo-model.yaml file -> Bob's Books `demo-model.yaml` file (code font for the file name)

2021-01-12 22:34 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> -Alternatively, you can specify the credentials in environment variables: `GHCR_USER`, `GHCR_PASS`, `OCR_USER`, and `OCR_PASS`. When the installation completes, the script will output URLs you can use
done

2021-01-12 22:35 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> +    **NOTE:** You should use more secure passwords.
I think I addressed all of these as well. The demo-model.yaml filename is incorrect, so I re-wrote parts of that section.

2021-01-13 13:12 UTC, rosemarymarano approved these changes
Minor nits, otherwise fine.

2021-01-13 13:12 UTC, rosemarymarano commented on oam-application-operator/examples/bobs-books/README.md
> +The WebLogic YAML for OAM is essentially identical to that in the Verrazzano model file `bobs-books-model.yaml`, except for the top section.
The WebLogic YAML for OAM -> The WebLogic YAML file for OAM
identical to that in the Verrazzano model file -> identical to the Verrazzano model file

2021-01-13 14:29 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> +The WebLogic YAML for OAM is essentially identical to that in the Verrazzano model file `bobs-books-model.yaml`, except for the top section.
Actually this doesn't refer to a YAML file - there is no WebLogic YAML file - only Weblogic YAML content in  the OAM component file for Bob's Books. Do you want me to change it to say "The WebLogic section in the OAM component file"?

2021-01-13 14:30 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> +The WebLogic YAML for OAM is essentially identical to that in the Verrazzano model file `bobs-books-model.yaml`, except for the top section.
It's comparing the WebLogic related YAML content in one file to the WebLogic related YAML content in another...hope that makes sense. Let me know how you want this worded

2021-01-13 15:07 UTC, merged

2021-01-13 15:17 UTC, rosemarymarano commented on oam-application-operator/examples/bobs-books/README.md
> +The WebLogic YAML for OAM is essentially identical to that in the Verrazzano model file `bobs-books-model.yaml`, except for the top section.
OH. So, the most straight forward text would be, "The WebLogic-related YAML content in the OAM component file for Bob's Books is essentially identical to the WebLogic-related YAML content in the Verrazzano model file,  `bobs-books-model.yaml`, except for the top section. However, this text might be unnecessarily wordy, so, I would ask for input from @markxnelson.

2021-01-13 15:58 UTC, desagar commented on oam-application-operator/examples/bobs-books/README.md
> +The WebLogic YAML for OAM is essentially identical to that in the Verrazzano model file `bobs-books-model.yaml`, except for the top section.
When we hear from Mark I will make the change in another PR