WIP: Istio helm install and upgrade
verrazzano/verrazzano pull request #508
Opened 2021-01-13 15:59 UTC by pfmackin

WIP: Still testing

This PR changes Istio to use helm install and implements the Istio upgrade.  Helm install is needed to use helm upgrade, otherwise helm doesn't know that Istio is installed

1) Change 1-install-istio.sh to do a helm install rather than generate manifests then kubectl apply
2) Change 1-install-istio.sh to use the istio component override yaml
3) Change the docker image build to replace the Istio charts usage kubectl image with istio_kubectl
4) Add the component/istio-values.yaml helm override file
5) Add the istio upgrade component

2021-01-14 18:24 UTC, bobdonat reviewed
A few small comments

2021-01-14 18:24 UTC, bobdonat commented on operator/internal/component/istio.go
> +		log.Error(err, fmt.Sprintf("Unable to get the chart version from %s", chartDir))
nit. should the message say "Unable to get chart info from %s

2021-01-14 18:24 UTC, bobdonat commented on operator/internal/component/registry.go
> +		helmComponent{
should these components be in the same order as the install order

2021-01-14 18:24 UTC, bobdonat commented on operator/scripts/install/1-install-istio.sh
>          --set gateways.istio-ingressgateway.type="${INGRESS_TYPE}" \
this can be included in EXTRA_HELM_ARGUMENTS with the other --set commands

2021-01-14 18:39 UTC, bobdonat commented on operator/controllers/upgrade_reconciler.go
> +			if strings.Contains(cond.Message, fmtGeneration(generation)) {
not clear to me how this code works

2021-01-14 18:41 UTC, pfmackin commented on operator/internal/component/registry.go
> +		helmComponent{
good question, I was actually thinking about that and don't know the answer.  We should discuss with others and decide the best order.

2021-01-14 18:41 UTC, pfmackin commented on operator/controllers/upgrade_reconciler.go
> +			if strings.Contains(cond.Message, fmtGeneration(generation)) {
ok i will add comments.

2021-01-14 19:34 UTC, pfmackin commented on operator/controllers/upgrade_reconciler.go
> +			if strings.Contains(cond.Message, fmtGeneration(generation)) {
fixed, i simplified the code also

2021-01-14 19:34 UTC, pfmackin commented on operator/scripts/install/1-install-istio.sh
>          --set gateways.istio-ingressgateway.type="${INGRESS_TYPE}" \
fixed

2021-01-14 19:34 UTC, pfmackin commented on operator/internal/component/istio.go
> +		log.Error(err, fmt.Sprintf("Unable to get the chart version from %s", chartDir))
fixed

2021-01-14 19:55 UTC, markxnelson requested changes

2021-01-14 19:55 UTC, markxnelson commented on operator/internal/component/istio_test.go
> +func fakeDeletJob(_ clipkg.Client, jobName string, namespace string) error {
typo

2021-01-14 19:55 UTC, markxnelson commented on operator/internal/component/testdata/Chart.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
update copyright notice

2021-01-14 19:55 UTC, markxnelson commented on operator/internal/k8s/job.go
> +package k8s
update copyright notice

2021-01-14 19:55 UTC, markxnelson commented on operator/internal/k8s/job.go
> +package k8s
applies to several of these files, will not repeat comment

2021-01-14 20:08 UTC, pfmackin commented on operator/internal/component/istio_test.go
> +func fakeDeletJob(_ clipkg.Client, jobName string, namespace string) error {
where is the typo?

2021-01-14 20:10 UTC, pfmackin commented on operator/internal/k8s/job.go
> +package k8s
sorry i missed these

2021-01-14 20:16 UTC, pfmackin commented on operator/internal/component/testdata/Chart.yaml
> +# Copyright (c) 2020, Oracle and/or its affiliates.
fixed

2021-01-14 20:25 UTC, pfmackin commented on operator/internal/k8s/job.go
> +package k8s
all fixed

2021-01-14 20:33 UTC, bobdonat commented on operator/internal/component/istio_test.go
> +func fakeDeletJob(_ clipkg.Client, jobName string, namespace string) error {
fakeDeletJob

2021-01-14 20:39 UTC, bobdonat commented on operator/scripts/install/1-install-istio.sh
> +      EXTRA_HELM_ARGUMENTS=" --set global.imagePullSecrets[0]=${GLOBAL_IMAGE_PULL_SECRET}  --set gateways.istio-ingressgateway.type="${INGRESS_TYPE}"
I think this additional set arg needs to be set unconditionally

2021-01-14 22:05 UTC, pfmackin commented on operator/scripts/install/1-install-istio.sh
> +      EXTRA_HELM_ARGUMENTS=" --set global.imagePullSecrets[0]=${GLOBAL_IMAGE_PULL_SECRET}  --set gateways.istio-ingressgateway.type="${INGRESS_TYPE}"
fixed

2021-01-14 22:05 UTC, pfmackin commented on operator/internal/component/istio_test.go
> +func fakeDeletJob(_ clipkg.Client, jobName string, namespace string) error {
ok

2021-01-14 22:07 UTC, pfmackin commented on operator/internal/component/istio_test.go
> +func fakeDeletJob(_ clipkg.Client, jobName string, namespace string) error {
fixed

2021-01-14 22:08 UTC, bobdonat approved these changes

2021-01-15 19:44 UTC, markxnelson approved these changes

2021-01-15 20:38 UTC, merged