VZ-8115: Pod Security and container security for Kiali
verrazzano/verrazzano pull request #5132
Opened 2023-01-13 20:10 UTC by pshirodkar-orcl

Pod Security and container security for Kiali.

2023-01-13 20:14 UTC, pshirodkar-orcl commented on platform-operator/helm_config/overrides/kiali-server-values.yaml
> +  pod_security_context:
Before: Pod security warning entry for kiali can be seen.
![Screenshot 2023-01-12 at 3 49 04 PM](https://user-images.githubusercontent.com/93555077/212410726-dfe6c37c-a5bb-4722-a19a-4aafdf01168c.png)

After: Pod security warning entry for kiali is no longer seen.
<img width="1440" alt="Screenshot 2023-01-13 at 12 13 41 PM" src="https://user-images.githubusercontent.com/93555077/212411061-c18680fa-02b5-412d-ae17-737877fb1dd5.png">

2023-01-13 20:24 UTC, mbenmclean requested changes
modify pod_security_test.go skipPods variable to ensure that kiali gets tested. Make the vmi-system prefix more specific so it doesn't catch Kiali and Kiali gets tested.

2023-01-13 21:12 UTC, pfmackin approved these changes

2023-01-13 22:39 UTC, pshirodkar-orcl commented
> modify pod_security_test.go skipPods variable to ensure that kiali gets tested. Make the vmi-system prefix more specific so it doesn't catch Kiali and Kiali gets tested.

I have addressed your comment now.

2023-01-17 16:45 UTC, mbenmclean approved these changes

2023-01-17 16:52 UTC, merged