Add startup probe to the oam-application-operator container
verrazzano/verrazzano pull request #524
Opened 2021-01-20 12:41 UTC by tbeerbower

Add startup probe to the oam-application-operator container to ensure webhooks are ready.

2021-01-20 22:21 UTC, kminder requested changes

2021-01-20 22:21 UTC, kminder commented on oam-application-operator/deploy/verrazzano.yaml_template
> +          startupProbe:
I think this change now needs to go here.
operator/thirdparty/charts/oam-application-operator/templates/verrazzano-application-operator.yaml
We may need to discuss this.

2021-01-21 02:01 UTC, tbeerbower commented on oam-application-operator/deploy/verrazzano.yaml_template
> +          startupProbe:
Updated to include this.  Acceptance tests https://build.verrazzano.io/blue/organizations/jenkins/verrazzano/detail/tbeerbower%2FVZ-1982/3/pipeline

2021-01-21 18:01 UTC, kminder approved these changes

2021-01-21 18:02 UTC, merged