Topic argocd multicluster integ
verrazzano/verrazzano pull request #5291
Opened 2023-02-02 22:18 UTC by leliyin

PR to support multicluster integration of Argo CD in VZ

The automation is facilitated through Rancher Proxy with creation of the k8s secret in the argocd namespace

2023-02-03 00:06 UTC, kminder commented on pkg/constants/constants.go
> +// ArgoCDClusterRancherUsername is the name of secret used to grant permissions to the Verrazzano argocd user
Are the comments wrong or are the constant names wrong?

2023-02-03 00:09 UTC, kminder commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +	logMsg := fmt.Sprintf("Sending request message: Type: %s, URL: %s, headers: %v, payload %s", http.MethodPost, reqURL, headers, payload)
Could this leak credentials to the logs?

2023-02-03 00:10 UTC, kminder commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed to generate a password for the Verrazzano cluster user: %v", err)
Is the password for the Verrazzano cluster user?

2023-02-03 00:11 UTC, kminder commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed to create the Verrazzano cluster user in Rancher: %v", err)
Verrazzano cluster user?

2023-02-03 00:12 UTC, kminder commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed create or update the Secret for the Verrazzano Cluster User: %v", err)
Use consistent case with other messages.

2023-02-03 00:13 UTC, kminder commented on platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
> +              argocdRegistration:
Should this match how the case ended up being handled in the VZ CR?

2023-02-03 00:14 UTC, kminder commented on platform-operator/helm_config/charts/verrazzano-cluster-operator/values.yaml
> +argocdClusterTokenTTL: 240
Review for case consistency.

2023-02-03 00:16 UTC, kminder commented on pkg/constants/constants.go
> +// ArgoCDClusterRancherName is the username in Rancher used to identify the Verrazzano argocd user for cluster registration
Review case of argocd

2023-02-03 04:21 UTC, leliyin commented on pkg/constants/constants.go
> +// ArgoCDClusterRancherUsername is the name of secret used to grant permissions to the Verrazzano argocd user
Have updated the comments.  We can reference 'vz-argocd-reg' as 'the Verrrazzano Argo CD cluster user' in logs as well as comments.

2023-02-03 04:30 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +	logMsg := fmt.Sprintf("Sending request message: Type: %s, URL: %s, headers: %v, payload %s", http.MethodPost, reqURL, headers, payload)
We are calling a utility function in pkg/security/password to mask password in the log message.

2023-02-03 04:33 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed to generate a password for the Verrazzano cluster user: %v", err)
Have fixed the comment as "Verrazzano Argo CD cluster user"

2023-02-03 04:35 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed to create the Verrazzano cluster user in Rancher: %v", err)
Have fixed the log message as "Verrazzano Argo CD cluster user".

2023-02-03 04:36 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed create or update the Secret for the Verrazzano Cluster User: %v", err)
Have fixed the log message as "Verrazzano Argo CD cluster user".

2023-02-03 04:39 UTC, leliyin commented on platform-operator/helm_config/charts/verrazzano-cluster-operator/crds/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
> +              argocdRegistration:
Good point.  I'll make the change to reflect the vmc CRD:

  status:
    argoCDRegistration:
      lastSetTimestamp: "2023-02-02T08:01:55Z"
      message: Waiting for managed cluster with id c-m-n4qrp6kw to become active before
        registering in Argo CD
      status: PendingRancherClusterRegistration

2023-02-03 04:42 UTC, leliyin commented on platform-operator/helm_config/charts/verrazzano-cluster-operator/values.yaml
> +argocdClusterTokenTTL: 240
Done. Have updated the name as argoCDClusterTokenTTL for consistency.

2023-02-03 04:46 UTC, leliyin commented on pkg/constants/constants.go
> +// ArgoCDClusterRancherName is the username in Rancher used to identify the Verrazzano argocd user for cluster registration
Done. Have updated user name as 'vz-argoCD-reg' and  sercret name as 'verrrazzano-argoCD-registrar'.

2023-02-03 14:31 UTC, davisgomes commented on cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
> +	ArgoCDRegistration ArgoCDRegistration `json:"argocdRegistration,omitempty"`
Should this json be argoCDRegistration?

2023-02-03 14:33 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +	vz, _ := r.getVerrazzanoResource()
Can you handle the error for this function call?

2023-02-03 14:33 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +	vz, _ := r.getVerrazzanoResource()
Handle the error here as well.

2023-02-03 14:41 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr("Unable to find instance information in Verrazzano resource status")
Error messages should start with "Failed ..." (i.e. Failed to find instance information in Verrazzano resource status)

2023-02-03 14:43 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr(msg, err)
The message string does not have a "%v" for this error, so the stack trace will not be included in the error message. You could change it to this:
```
return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr(msg + ": %v", err)
```

2023-02-03 14:44 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		return nil
`return err`?

2023-02-03 14:46 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		Name:      vzconst.ArgoCDClusterRancherName}
Can you put this end curly brace on the next line?

2023-02-03 14:47 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +func GetArgoCDClusterUserSecret(rdr client.Reader) (string, error) {
If you make this a member function (`func (r *VerrazzanoManagedClusterReconciler)`) you won't have to pass in the client reader.

2023-02-03 14:51 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +	return string(secret.Data["password"]), nil
Check that this field exists before you use it. Otherwise, you might get a nil dereference error.
```
if pw, ok := secret.Data["password"]; ok {
    return string(pw), nil
```

2023-02-03 14:54 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +}
Can you rename the struct "`RancherConfig`" to something more unique. It will probably get confusing with two RancherConfigs with different purposes. Maybe "`ArgoCDRancherData`"?

2023-02-03 14:55 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) createOrUpdateSecret(rc *rancherutil.RancherConfig, vmc *clusterapi.VerrazzanoManagedCluster, rancherURL, clusterID string, caData []byte) (controllerutil
You don't need to return the `controllerutil.OperationResult` if you aren't using it in the function call. You can just ignore it and return the error.

2023-02-03 15:06 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +	tokenExpiresAt, okExpires := secret.Annotations["verrazzano.io/expiresAtTimestamp"]
Can you make these annotation strings constants since you use them twice?

2023-02-03 15:07 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		}
Log these errors since we are calling an imported package.

2023-02-03 15:08 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		createNewToken = (timeToCheck.Unix()-timeCreated.Unix())/(timeExpired.Unix()-timeCreated.Unix())*100 > 75
Can you add a comment about what we are doing here? It's a little confusing to try to read through

2023-02-03 15:09 UTC, fredtibbitts commented
Since we do not yet have any end-to-end tests for this feature, can you please update the PR description to include how you tested this locally to make sure all of the changes work as expected? Include information on how you tested token refresh, deploying apps to managed clusters, etc.

2023-02-03 15:11 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr("Unable to find Verrazzano resource on admin cluster: %v", err)
Typically we want to log errors at the source. If we are calling a function that has access to the logger, we defer to the closest we can get to the error. Please log the error in the `r.getVerrazzanoResource` function (or in any lower functions that are called from `r.getVerrazzanoResource`.

2023-02-03 15:14 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		attrs, err := rancherutil.GetTokenByName(rc, r.log, tokenName)
What happens if the token is not updated by the time we try to get it?

2023-02-03 15:24 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +			Insecure: false},
Newline for this closed curly brace.

2023-02-03 15:25 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +		return r.log.ErrorfThrottledNewErr("Failed configuring %s %s: %s", ClusterRoleTemplateBindingKind, nsn.Name, err.Error())
Use a `%v` and pass in the error so that we can get a stack trace.

2023-02-03 15:30 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd.go
> +	if err := r.Delete(context.TODO(), &clusterSec); err != nil {
You can use `client.IgnoreNotFound(err)` i.e.
```
if err := r.Delete(context.TODO(), &clusterSec); client.IgnoreNotFound(err) != nil {
    return r.log.ErrorfNewErr("Failed to delete Argo CD cluster secret", err)
}
```

2023-02-03 15:35 UTC, davisgomes commented on cluster-operator/controllers/vmc/argocd_test.go
> +func TestMutateClusterSecretWithRefresh(t *testing.T) {
There's a lot of copy paste here. I think it's okay for a unit test, but you could consider using the loop testing format: https://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go

2023-02-03 15:46 UTC, davisgomes commented on cluster-operator/controllers/vmc/vmc_controller.go
> +
These nested `if`s are a bit ugly. Here's how I think you could format it:
```
argoCDEnabled := r.isArgoCDEnabled()
rancherEnabled := r.isRancherEnabled()
if argoCDEnabled && rancherEnabled {
    // register ArgoCD
}
if !rancherEnabled && argoCDEnabled {
  // update status
}
```

2023-02-03 15:48 UTC, davisgomes commented on cluster-operator/controllers/vmc/vmc_controller.go
> +				})
I don't think you need to update the status like you have here. You can follow suit from the push manifest block and create a new function `r.setStatusConditionArgoCDRegistered`

2023-02-03 15:48 UTC, davisgomes commented on cluster-operator/controllers/vmc/vmc_controller.go
> +	})
Same comment about the status update. I don't think you need to add this parameter.

2023-02-03 15:50 UTC, davisgomes commented on pkg/rancherutil/rancher_config.go
> +// SetTokenTTL creates a user token with ttl
What granularity is the ttl at. Hours?

2023-02-03 15:52 UTC, davisgomes commented on pkg/rancherutil/rancher_config.go
> +	}
Log these errors

2023-02-03 15:55 UTC, davisgomes commented on pkg/rancherutil/rancher_config.go
> +	jsonString, err := gabs.ParseJSON([]byte(responseBody))
I think you can json unmarshal this into a struct like the ones you defined above

2023-02-03 15:58 UTC, davisgomes commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		}
You can reverse this to remove the nested ifs:
```
if !vzcr.IsArgoCDEnabled(ctx.EffectiveCR()) {
    return nil
}
return := createVZArgoCDUser(ctx)

2023-02-03 16:02 UTC, davisgomes commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		return ctx.Log().ErrorfNewErr("Failed to generate a password for the Verrazzano cluster user: %v", err)
Same comment. Please update when the changes are pushed.

2023-02-03 16:09 UTC, davisgomes commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +	logMsg = vzpassword.MaskFunction("Authorization:Bearer ")(logMsg)
Should you have a space between the colon and Bearer?

2023-02-03 16:27 UTC, leliyin commented on cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
> +	ArgoCDRegistration ArgoCDRegistration `json:"argocdRegistration,omitempty"`
Correct. This is already addressed.

2023-02-03 16:37 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	vz, _ := r.getVerrazzanoResource()
Done.

2023-02-03 16:40 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr("Unable to find instance information in Verrazzano resource status")
Done.

2023-02-03 16:41 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr(msg, err)
Done.

2023-02-03 16:42 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr(msg, err)
Done.

2023-02-03 16:42 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return nil
Done.

2023-02-03 16:44 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		Name:      vzconst.ArgoCDClusterRancherName}
Done.

2023-02-03 17:01 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		}
Done.

2023-02-03 17:03 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		createNewToken = (timeToCheck.Unix()-timeCreated.Unix())/(timeExpired.Unix()-timeCreated.Unix())*100 > 75
Done

2023-02-03 17:05 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +			Insecure: false},
Done

2023-02-03 17:08 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return r.log.ErrorfThrottledNewErr("Failed configuring %s %s: %s", ClusterRoleTemplateBindingKind, nsn.Name, err.Error())
Done

2023-02-03 17:09 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	if err := r.Delete(context.TODO(), &clusterSec); err != nil {
Done.

2023-02-03 17:11 UTC, leliyin commented on pkg/rancherutil/rancher_config.go
> +// SetTokenTTL creates a user token with ttl
Have updated the comment that ttl is in minutes.

2023-02-03 18:38 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +func GetArgoCDClusterUserSecret(rdr client.Reader) (string, error) {
Done

2023-02-03 18:38 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	vz, _ := r.getVerrazzanoResource()
Done

2023-02-03 19:47 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	return string(secret.Data["password"]), nil
Done.

2023-02-03 19:47 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) createOrUpdateSecret(rc *rancherutil.RancherConfig, vmc *clusterapi.VerrazzanoManagedCluster, rancherURL, clusterID string, caData []byte) (controllerutil
Done.

2023-02-03 19:48 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return nil
done.

2023-02-03 19:48 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +}
Done.

2023-02-03 19:51 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr("Unable to find Verrazzano resource on admin cluster: %v", err)
Done.

2023-02-03 19:52 UTC, leliyin commented on cluster-operator/controllers/vmc/vmc_controller.go
> +
Done.

2023-02-03 19:54 UTC, leliyin commented on pkg/rancherutil/rancher_config.go
> +	}
Done.

2023-02-03 19:54 UTC, leliyin commented on pkg/rancherutil/rancher_config.go
> +	jsonString, err := gabs.ParseJSON([]byte(responseBody))
Done.

2023-02-03 19:57 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +		}
Done.

2023-02-03 20:00 UTC, leliyin commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +	logMsg = vzpassword.MaskFunction("Authorization:Bearer ")(logMsg)
I checked the same was done for createVZClusterUser.

2023-02-03 20:01 UTC, leliyin commented on pkg/rancherutil/rancher_config.go
> +	}
Done.

2023-02-03 20:54 UTC, fredtibbitts commented on cluster-operator/controllers/vmc/argocd.go
> +	vz, _ := r.getVerrazzanoResource()
@leliyin you marked a bunch of these conversations resolved but I don't see any updates? The PR shows no commits today, did you not push the commits to your remote branch? Or maybe I'm just somehow looking at stale information?

2023-02-03 22:27 UTC, leliyin commented
> Since we do not yet have any end-to-end tests for this feature, can you please update the PR description to include how you tested this locally to make sure all of the changes work as expected? Include information on how you tested token refresh, deploying apps to managed clusters, etc.

I've updated the PR with tests I performed locally. We are adding e2e/multiclusters tests as we speak, the PR will be shortly followed.

I have just merged first round of review comments from Kevin and Davis. Please review.

2023-02-04 17:11 UTC, fredtibbitts requested changes

2023-02-04 20:46 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		newToken, tokenName, err := rancherutil.SetTokenTTL(rc, r.log, ttl, clusterID)
Correct. The Rancher API to set the token TTL returns create timestamp, not expires timestamp, hence we need to follow up with GET with the token name to get the expires timestamp.

2023-02-04 20:56 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	var rancherURL = *(vz.Status.VerrazzanoInstance.RancherURL) + k8sClustersPath + clusterID
Done.

2023-02-04 20:56 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +// argocdClusterAdd registers cluster using the Rancher Proxy by creating a user in rancher, with api token and cluster roles set, and a secret containing Rancher proxy for the cluster
Done.

2023-02-04 20:57 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) GetArgoCDClusterUserSecret() (string, error) {
Done.

2023-02-04 20:59 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	return "", nil
Good catch. Fixed.

2023-02-04 21:02 UTC, leliyin commented on pkg/constants/constants.go
> +const ArgoCDClusterRancherName = "verrazzano-argoCD-registrar"
Done.

2023-02-04 21:22 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd_test.go
> +			Annotations: map[string]string{"verrazzano.io/createTimestamp": time.Now().Format(time.RFC3339), "verrazzano.io/expiresAtTimestamp": time.Now().Add(4 * time.Second).Format(time.RFC3339)},
Good idea. Have set expiration to +10hr.

2023-02-04 21:22 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +		createNewToken = (timeToCheck.Unix()-timeCreated.Unix())/(timeExpired.Unix()-timeCreated.Unix())*100 > 75
Done.

2023-02-04 22:02 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd_test.go
> +	assert.NoError(t, err)
Good point. Have added an assert to check the token from the secret is same as the token set in the unit-test.

2023-02-04 22:08 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd_test.go
> +	httpMock.EXPECT().
Correct. this mock expectation is from call to NewRancherConfigForUser to get the Rancher Config to pass to mutateClusterSecret. As this test case is to assert token not refreshed, I've added an assert to check the token is not changed after mutateClusterSecret completes. So we still need call to NewRancherConfigForUser, yes?

2023-02-04 22:24 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd_test.go
> +	time.Sleep(4 * time.Second)
Good idea. Updated code per suggestion and removed the sleep.

2023-02-04 22:27 UTC, leliyin commented on cluster-operator/controllers/vmc/argocd.go
> +	createTimestamp                 = "verrazzano.io/createTimestamp"
I've incorporated Fred's suggestion for annotation naming.  We can update further if needed.

2023-02-06 13:46 UTC, fredtibbitts commented on cluster-operator/controllers/vmc/argocd_test.go
> +	httpMock.EXPECT().
I think having `NewRancherConfigForUser` and the associated code isn't needed for this unit test, it just adds unnecessary complexity. I don't feel strongly about removing it so if you want to leave it, that's fine.

2023-02-06 13:49 UTC, fredtibbitts commented on cluster-operator/controllers/vmc/argocd.go
> +	return "", err
`err` is `nil` here (you check for != `nil` above and return so it must be `nil`). You need to create an error here and return it.

2023-02-06 14:45 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +	if err != nil || rc == nil {
this rc == nil check is not needed since if err is nil we will get back an rc. The logging in this case can also be skipped.

2023-02-06 14:47 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr(msg+": %v", err)
any logs with ErrorfNewErr should be formatted as follows rather than using string concatenation.

r.log.ErrorfNewErr("%s: %v", msg, err)

2023-02-06 14:49 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		msg := "Failed to update Argo CD ClusterRoleBindingTemplate"
The called function logs the err so this one does not need a log msg

2023-02-06 14:51 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +	msg := "Successfully registered managed cluster in ArgoCD"
General comment for this function and all functions - any logs with ErrorfNewErr (or anything with an "f" suffix for the logging) should be formatted as follows rather than using string concatenation.

r.log.ErrorfNewErr("%s: %v", msg, err)

2023-02-06 14:51 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		return newArgoCDRegistration(clusterapi.MCRegistrationFailed, msg), r.log.ErrorfNewErr("Unable to create cluster secret on admin cluster: %v", err)
The called function logs the err so this one does not need a log msg

2023-02-06 14:58 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		return err
this err case should log here since the GetRootCA function doesn't take a logger.

2023-02-06 15:02 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) createOrUpdateSecret(rc *rancherutil.RancherConfig, vmc *clusterapi.VerrazzanoManagedCluster, rancherURL, clusterID string, caData []byte) error {
This function should be called createOrUpdateArgoCDSecret, to be more clear. It is declared on the reconciler object and that object is used for both argo and non-argo work.
Also a function comment at the top would be helpful.

2023-02-06 15:02 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) mutateClusterSecret(secret *corev1.Secret, rc *rancherutil.RancherConfig, clusterID, cluserName string, rancherURL string, caData []byte) error {
This function should be called mutateArgoCDSecret, to be more clear. It is declared on the reconciler object and that object is used for both argo and non-argo work.

2023-02-06 15:04 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +func (r *VerrazzanoManagedClusterReconciler) createClusterSecret(vmc *clusterapi.VerrazzanoManagedCluster, clusterID, rancherURL string) error {
This function should be called createArgoCDSecret, to be more clear. It is declared on the reconciler object and that object is used for both argo and non-argo work.

2023-02-06 15:10 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +// createClusterSecret registers cluster using the Rancher Proxy by creating a user in rancher, with api token and cluster roles set, and a secret containing Rancher proxy for the cluster
this comment should be clarified e.g. the rancher user for argoCD must already exist at this point - if that's the case, it's not created by this function.

createArgoCDClusterSecret registers cluster with ArgoCD using the "vz-argoCD-reg" user and the Rancher proxy URL for the cluster.

2023-02-06 15:18 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +	clusterSecretName               = "cluster-secret"
This constant should be named with a prefix indicating it's related to argo. 
Likewise, it would be helpful for the value to have "argoCD" in it (e.g. "argoCD-cluster-secret").

2023-02-06 15:35 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		return err
We should log this error before returning it.

2023-02-06 15:36 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +// updateRancherClusterRoleBindingTemplate creates a new ClusterRoleBindingTemplate for the given VMC
update comment to correct the function name.

2023-02-06 15:44 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +	err := r.Client.List(context.TODO(), &usersList, &client.ListOptions{})
you can just do r.List() instead of r.Client.List here

2023-02-06 15:50 UTC, desagar commented on cluster-operator/controllers/vmc/argocd.go
> +		return r.log.ErrorfNewErr("Failed to delete Argo CD cluster secret", err)
missing %v in the format string to print the error in the log msg

2023-02-06 15:59 UTC, desagar commented on cluster-operator/controllers/vmc/argocd_test.go
> +	httpMock.EXPECT().
this mock expectation can be moved to its own function e.g. expectRancherLoginRequest(), and then shared by both of the test functions.

2023-02-06 16:00 UTC, desagar commented on cluster-operator/controllers/vmc/argocd_test.go
> +func TestMutateClusterSecretWithRefresh(t *testing.T) {
Similar to the TestUpdateArgoCDClusterRoleBindingTemplate below, which has several cases.

2023-02-06 16:03 UTC, desagar commented on cluster-operator/controllers/vmc/vmc_controller.go
> +		vmc.Status.ArgoCDRegistration = *argoCDRegistration
This line should be _after_ the error check. We should not dereference *argoCDRegistration if there was an error.

2023-02-06 16:04 UTC, desagar commented on cluster-operator/controllers/vmc/vmc_controller.go
> +			Message:   "Waiting for Rancher managed cluster to become active"}
This message should say something about Rancher not being enabled, since that is the reason we can't do the argo registration.

2023-02-06 16:10 UTC, desagar commented on pkg/rancherutil/rancher_config.go
> +	headers := map[string]string{"Authorization": "Bearer " + rc.APIAccessToken, "Content-Type": "application/json"}
why is the Content-Type needed for this GET request that doesn't send a body?

2023-02-06 16:22 UTC, desagar commented on platform-operator/controllers/verrazzano/component/clusteroperator/cluster_operator.go
> +func constructVZArgoUserJSON(pass string) ([]byte, error) {
not as big of a deal but this can be combined easily as well with the other construct JSON function

2023-02-06 16:32 UTC, desagar commented on cluster-operator/apis/clusters/v1alpha1/verrazzanomanagedcluster_types.go
>  	// Supporting message related to the Rancher registration status
This comment needs to say ArgoCD registration instead of Rancher registration. This also ends up in the CRD so you'll need to rerun "make manifests"

2023-02-07 06:47 UTC, leliyin commented
@desagar @davis-gomes @fredtibbitts @kminder  I've addressed all the review comments. Please let me know if the review is still pending or we can have a merge to the master branch

2023-02-07 15:35 UTC, davisgomes approved these changes

2023-02-07 15:36 UTC, desagar approved these changes

2023-02-07 15:56 UTC, fredtibbitts approved these changes

2023-02-07 19:00 UTC, merged