VerrazzanoHelidon CRD
verrazzano/verrazzano pull request #576
Opened 2021-02-01 22:37 UTC by arjav-desai

This is change contains CRD and workload related integration along with empty/no-op implementation of controller.

2021-02-02 13:57 UTC, fredtibbitts requested changes

2021-02-02 13:57 UTC, fredtibbitts commented on application-operator/controllers/helidonworkload/helidonworkload_controller.go
> +	// fetch the workload and unwrap the Coherence resource
Copy/paste comment: "Coherence"

2021-02-02 13:57 UTC, fredtibbitts commented on application-operator/deploy/workloaddefinition_vzhelidon.yaml
> +      kind: Service
It's not entirely clear to me how these workload definitions are supposed to be defined. Is your controller going to create both deployments and services, or is the service creation a side effect of the deployment? If it's the latter, then I think "Service" should be removed, but I'm not sure. @kminder?

2021-02-02 13:57 UTC, fredtibbitts commented on application-operator/go.mod
> -	github.com/gordonklaus/ineffassign v0.0.0-20210104184537-8eed68eb605f // indirect
I think you should remove `go.mod` and `go.sum` from your commits. The build has an issue and should not be updating these files (I think there's a ticket to fix this?) The versions of packages are strictly controlled so you should back out these 2 files.

2021-02-02 14:06 UTC, fredtibbitts commented
@arjav-desai looks like you forked the repo, which the jenkins pipeline doesn't like. We create branches instead of forking, so I think you'll need to do the same here.

2021-02-02 14:44 UTC, kminder commented on application-operator/apis/oam/v1alpha1/verrazzanohelidonworkload_types.go
> +// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
Should probably fix this to just have 2021 since it is new.

2021-02-02 14:53 UTC, kminder commented on application-operator/config/crd/patches/cainjection_in_verrazzanohelidonworkloads.yaml
> +# The following patch adds a directive for certmanager to inject CA into the CRD
This will probably get deleted later but for now it needs a copyright.  Same for the other YAML files.

2021-02-02 14:53 UTC, kminder commented on application-operator/controllers/helidonworkload/helidonworkload_controller.go
> +// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
For new files just use 2021.

2021-02-02 14:54 UTC, kminder commented on application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
> +// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
Copyright

2021-02-02 14:56 UTC, kminder commented on application-operator/controllers/helidonworkload/helidonworkload_controller_test.go
> +	// +kubebuilder:scaffold:scheme
What does this annotation do?

2021-02-02 14:59 UTC, kminder commented on application-operator/deploy/workloaddefinition_vzhelidon.yaml
> +      kind: Service
My understanding is that this should match the ownerReference linkage.  So only type childResourcesKinds for things that will created with an ownerReference of the VerrazzanoHelidonWorkload should be listed here.
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

2021-02-02 15:00 UTC, kminder commented on application-operator/go.mod
> +	golang.org/x/sys v0.0.0-20210124154548-22da62e12c0c // indirect
Agree with Fred.  Remove these indirects.

2021-02-02 15:00 UTC, kminder commented on application-operator/go.sum
> +golang.org/x/sys v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
Remove

2021-02-02 16:58 UTC, arjav-desai commented on application-operator/deploy/workloaddefinition_vzhelidon.yaml
> +      kind: Service
Yes, I plan to create both deployment and service resources based on VerrazzanoHelidonWorkload.

2021-02-02 16:58 UTC, arjav-desai commented on application-operator/go.mod
> -	github.com/gordonklaus/ineffassign v0.0.0-20210104184537-8eed68eb605f // indirect
Good to know, I will back them out.

2021-02-03 03:58 UTC, arjav-desai commented
Have created a new PR https://github.com/verrazzano/verrazzano/pull/584 based on branch and not fork so closing this one.

2021-02-03 03:58 UTC, closed without merging