VZ-2044: Update Coherence ES index
verrazzano/verrazzano pull request #591
Opened 2021-02-03 20:55 UTC by fredtibbitts

This PR updates the Coherence ES index to match the work that GZ recently did for WLS. The index uses the pattern `oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}` so that users can more easily search logs for their applications.

The work in the VerrazzanoCoherenceWorkload controller was simply to update the fluentd rules and also to copy the OAM app and component name labels into the Coherence CR that the controller writes out.

I also moved 3 fluentd container environment variables out of `wls.go` into `fluentd.go` as they will be needed by all workload types.

2021-02-03 22:17 UTC, guoyongzhang approved these changes
LGTM

2021-02-03 22:24 UTC, kminder commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
I'm not a fan of exposing oam any more than necessary.  Could this be vz- or verrazzano- instead.  I'm aware that this probably means more work elsewhere too.

2021-02-03 22:26 UTC, fredtibbitts commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
I was following what GZ did. @guoyongzhang can you comment on having "oam" in the index?

2021-02-03 22:28 UTC, fredtibbitts commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
Also we should probably make the index a constant in fluentd.go so we all use the same pattern. I can make that update.

2021-02-03 22:30 UTC, guoyongzhang commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
how aout app-....?

2021-02-03 22:30 UTC, kminder commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
Someone should check with @gilbode for an official opinion.

2021-02-03 22:33 UTC, fredtibbitts commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
I'm not sure the "oam-" adds value, maybe just remove it altogether? I agree with @kminder we should get sign-off on the index pattern.

2021-02-04 08:38 UTC, markxnelson requested changes

2021-02-04 08:38 UTC, markxnelson commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
i see no reason to include `oam` in this name - the fact that we use oam to deploy something is an implementation detail

2021-02-04 08:38 UTC, markxnelson commented on application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
> +			// make sure the oam component and app name labels were copied
OAM is captitalized

2021-02-04 14:02 UTC, fredtibbitts commented on application-operator/controllers/cohworkload/coherenceworkload_controller_test.go
> +			// make sure the oam component and app name labels were copied
Fixed.

2021-02-04 14:03 UTC, fredtibbitts commented on application-operator/controllers/cohworkload/coherenceworkload_controller.go
> +  index_name "oam-#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
I removed `oam-` and moved the index pattern to a shared constant.

2021-02-04 14:11 UTC, gilbode commented on application-operator/controllers/loggingscope/fluentd.go
> +const ElasticSearchIndex = "#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
Is this the same pattern used for other component types?  I'd like this to be consistent.

2021-02-04 14:14 UTC, fredtibbitts commented on application-operator/controllers/loggingscope/fluentd.go
> +const ElasticSearchIndex = "#{ENV['NAMESPACE']}-#{ENV['APP_CONF_NAME']}-#{ENV['COMPONENT_NAME']}"
Yes, I made them all use this constant.

2021-02-04 22:05 UTC, markxnelson approved these changes

2021-02-04 23:32 UTC, merged