VZ-10153 MetricsTrait Converter
verrazzano/verrazzano pull request #6428
Opened 2023-07-10 20:22 UTC by AnshulDalua

Added implementation of MetricsTrait to service monitor conversion

2023-07-11 16:14 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app.yaml
> +  namespace: hello-helidon
Please remove this ns

2023-07-11 16:15 UTC, anders-swanson commented on go.mod
> +)
missing newline at end of file

2023-07-11 16:15 UTC, anders-swanson commented on go.sum
> +sigs.k8s.io/yaml v1.3.0/go.mod h1:GeOyir5tyXNByN85N/dRIT9es5UQNerPYEKK56eTBm8=
missing newline at end of file

2023-07-11 16:26 UTC, anders-swanson commented on tools/oam-converter/main.go
> -	err := app.ConfData()
Can you sync with Vrushali about loading the OAM components, application configurations?

2023-07-11 16:29 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	for _, trait := range metricsTraits {
Similar to Ingress Trait, let's move common logic out of main function to packages

2023-07-11 16:29 UTC, anders-swanson commented on tools/oam-converter/main.go
> +		//createIngressChildResources(trait)
Why is this commented out?

2023-07-11 16:29 UTC, anders-swanson commented on tools/oam-converter/main.go
> +		//Put metricsTrait method
Is a method missing here?

2023-07-11 16:31 UTC, anders-swanson commented on pkg/metrics/service_monitor.go
> +type ScrapeInfo struct {
If these types and methods are copied from application operator, please update application operator to use this new package.

2023-07-11 16:33 UTC, anders-swanson commented on tools/oam-converter/main.go
> +func createIngressChildResources(ingresstrait *vzapi.IngressTrait) {
I thought Vrushali had moved these methods out already?

2023-07-11 16:55 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	workload, err = FetchWorkloadFromTrait(trait)
We need to parse the associated component workload from the input - this is going out to the cluster itself.

2023-07-11 16:58 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	workload, err = FetchWorkloadFromTrait(trait)
I misunderstood this, since the method name is the same as the application operator method name. disregard this comment

2023-07-11 16:59 UTC, anders-swanson commented on tools/oam-converter/main.go
> +		//sClusterName:        clusters.GetClusterName(ctx, r.Client),
Not sure what to use for cluster name, you can use "default" as a placeholder.

2023-07-11 17:26 UTC, anders-swanson commented on tools/oam-converter/main.go
> +
empty?

2023-07-11 17:27 UTC, anders-swanson commented on tools/oam-converter/main.go
> +func createServiceMonitor(trait *vzapi.MetricsTrait) (monitor promoperapi.ServiceMonitor){
This is more appoper code... can it be shared between the two apps somehow?

2023-07-11 17:44 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	u := &unstructured.Unstructured{}
There's no workload here?

2023-07-11 17:45 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	_ = ""
this is leftover from something?

2023-07-11 17:47 UTC, anders-swanson commented on tools/oam-converter/main.go
> +	//secretNamespace, found, err := unstructured.NestedString(workload.Object, "metadata", "namespace")
code is commented

2023-07-11 17:49 UTC, anders-swanson commented on tools/oam-converter/main.go
> +func GetContainedWorkloadVersionKindName(workload *unstructured.Unstructured) (string, string, string, error) {
It's very difficult to tell which code came from app operator, which code is new, and which came from app operator but was modified. Some organization will help here, as well as all possible code reuse between app operator and oam converter if code does need to be shared.

Suggest at least to start with putting app operator code in a different package so it is easier to identify, it is difficult to review currently.

2023-07-14 15:53 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		if strings.Contains(info.Name(), "yaml"){
Can you check for YAML files by verifying that the file ends with ".yaml" or ".yml". Both are valid file extensions for YAML.

2023-07-14 15:54 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			if strings.Contains(info.Name(), "app"){
To find application configuration and components, we need to iterate through the documents in each YAML file. Note that a given directory may have more than one application configuration, and it may not be in a file named "app". Same goes for components, we can discuss.

2023-07-14 17:14 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app.yaml
> -# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
Copyright should be 2020, 2023. Our convention is to keep the earliest copyright year.

2023-07-14 17:19 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		//outputDirectory = os.Args[2]
removed commented line

2023-07-14 17:20 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	if len(os.Args) != 3 {
typically we want to check inputs first thing, would suggest to make a separate function just for validating inputs

2023-07-14 17:20 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	//var outputDirectory string
remove commented line

2023-07-14 17:25 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	var appDataArr[](map[string]interface{})
`appDataArr[] map[string]interface{}` is the appropriate style

2023-07-14 17:28 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		appData, err := ioutil.ReadFile(input)
note that an applciation configuration may not be the only thing in a YAML file. consider the following YAML file:
example.yaml with multiple resources:
```yaml
# example.yaml
kind: ApplicationConfiguration
# ... application configuration definition
---
kind: Component
# ... component definition
---
kind: Service
# ... service definition
```

2023-07-14 17:29 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			log.Fatalf("Failed to unmarshal YAML: %v", err)
why do we return err sometimes, but log.Fatalf other times? I would suggest return err always, and let the caller handle the error. If its main function, then we can log.Fatalf to terminate the program on errors that the program can't handle

2023-07-14 17:32 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		if value, ok := appMap["kind"]; ok {
Kind is not enough to assume ApplicationConfiguration (though this is a major corner case). API Group and Version should be checked as well for a comprehensive verification. I would suggest to create function IsApplicationConfiguration to segment this logic out (you can do similar for Component or any other type).

2023-07-14 17:33 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
>  		log.Fatalf("Failed to unmarshal YAML: %v", err)
indentation is wrong here

2023-07-14 17:34 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	fmt.Print(metricsTraits)
Is this for debugging?

2023-07-14 17:44 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +func iterateDirectory(path string) ([]string, []string) {
I'd like to see a different tack for this method, something along these lines:
1. Walk the directory
2. For each YAML file, split the file into a buffer, and split the bufer into documents based on the `---` delimiter:
  a. For each document, determine whether its an ApplicationConfiguration, Component, or something else
  b. Store the resulting objects in a struct, marshalling application configurations and components into their relevant structs:
```
type InputDocuments struct {
  // the list of input application configurations
  applicationConfigurations []ApplicationConfiguration
  // components is a map of component names to component objects
  components map[string]Component
  // documents is the list of YAML documents that are neither application configurations nor components
  documents []map[string]interface{}
}
```

Now, the next pipeline of the program can begin to process the application configurations and components to generate the metrics traits, ingress traits, and any other converted resources.

2023-07-14 17:46 UTC, anders-swanson commented on tools/oam-converter/pkg/bobs-books-app.yaml
> +apiVersion: core.oam.dev/v1alpha2
Did you mean to commit this file? You can use the path directly to the examples for testing.

2023-07-14 17:46 UTC, anders-swanson commented on tools/oam-converter/pkg/bobs-books-comp.yaml
> +apiVersion: core.oam.dev/v1alpha2
please remove from commit with above file and use examples directory instead

2023-07-14 17:52 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		appMap := make(map[string]interface{})
would recommend to unmarshall to unstructured.Unstructured objects. This has a lot of helpful methods for working with k8s objects. Check this sample codes to unmarshall YAML bytes to an unstructured, using apimachinery:

```go
import (
  "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
  "k8s.io/apimachinery/pkg/runtime"
  apiyaml "k8s.io/apimachinery/pkg/util/yaml"
)

...
func toUnstructured(o []byte) (*unstructured.Unstructured, error) {
  j, err := apiyaml.ToJSON(o)
  if err != nil {
    return nil, err
  }
  obj, err := runtime.Decode(unstructured.UnstructuredJSONScheme, j)
  return obj, err
}
```

2023-07-14 17:52 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		appMap := make(map[string]interface{})
This way you can work with the unstructured object, rather than a raw map

2023-07-14 17:53 UTC, anders-swanson commented on tools/oam-converter/pkg/helidon-config-app.yaml
> +# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
please remove these from the oam-converter, should use examples/hello-helidon instead

2023-07-14 17:53 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/coherenceresources/coherenceresources.go
> +		//Scraper: &r.Scraper
commented, why?

2023-07-14 17:55 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/coherenceresources/coherenceresources.go
> +func fetchCoherenceMetricsSpec(workload *unstructured.Unstructured) (*bool, *int, *string, error) {
when you have more than 2 or 3 return values, suggest to return as a struct, e.g.,
```go
type CoherenceMetricsParams {
  Port *int
  Enabled *bool
  Secret *string
}
```

2023-07-14 17:56 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/metrics/metrics.go
> +	//createService()
commented, why?

2023-07-14 17:58 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +	PrintServiceMonitor(&serviceMonitor)
Is this for debugging?

2023-07-14 17:59 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +	namespace := getNamespaceFromObjectMetaOrDefault(trait.ObjectMeta)
Trait doesn't have the namespace. It should come from application configuration

2023-07-14 18:01 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +type ScrapeInfo struct {
We have this type defined twice, I am confused

2023-07-14 18:02 UTC, anders-swanson commented on pkg/metrics/service_monitor.go
> +func PopulateServiceMonitor(info ScrapeInfo, serviceMonitor *promoperapi.ServiceMonitor) error {
some of this code seems copied twice, can you please clean it up

2023-07-18 19:55 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/weblogicresources/weblogicresources.go
> +		//Scraper: &r.Scraper
copied from above?  also, commented line here

2023-07-18 19:56 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +	// Use the workload namespace for the secret to fetch.
commented code?

2023-07-18 19:57 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +func FetchTraitDefaults(workload *unstructured.Unstructured) (*vzapi.MetricsTraitSpec, bool, error) {
app operator code...?

2023-07-21 17:27 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +				return err
if !found err will be nil. Suggest return custom error here, like `errors.New("apiVersion was not found as a string field")` or similar.

2023-07-21 17:28 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			}
Can you add a TODO here that if the kind is something else, let's put it in another array to write out as-is. This will satisfy the case when the application has K8s resources that are not OAM-specific, which is a valid use case. E.g., the user has an application configuration, a component, and a service. Just put the TODO here so we know to do it later.

2023-07-21 17:34 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	printDirectory(outputDirectory, outputResources)
Is this for logging? Any other reason this would be here?

2023-07-21 17:43 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			log.Fatalf(err.Error())
return error here, let callers handle

2023-07-21 17:43 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +func iterateDirectory(path string) []string {
return `([]string, error)`

2023-07-21 17:44 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	if outputResources.VirtualServices != nil {
why is this stuff commented?

2023-07-21 17:44 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +func printDirectory(directoryPath string, outputResources *types.KubeRecources)(error){
can we call this writeKubeResources or something, and rename `directoryPath` to `outputDirectory` or similar.

2023-07-21 17:45 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	if outputResources.VirtualServices != nil {
not implemented yet?

2023-07-21 17:46 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	defer f.Close()
Place the defer call earlier, right after checking the Open call error

2023-07-21 17:47 UTC, anders-swanson commented on tools/oam-converter/pkg/controllers/metricstrait_utils.go
> +	// Use the workload namespace for the secret to fetch.
Remove or explain commented code

2023-07-21 17:47 UTC, anders-swanson commented on tools/oam-converter/pkg/controllers/workloads.go
> +		//Scraper: &r.Scraper
Why is this commented?

2023-07-21 17:48 UTC, anders-swanson commented on tools/oam-converter/pkg/controllers/workloads.go
> +		//Scraper: &r.Scraper
why is this commented?

2023-07-21 17:48 UTC, anders-swanson commented on tools/oam-converter/pkg/controllers/workloads.go
> +		//Scraper: &r.Scraper
ditto here

2023-07-21 17:49 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/coherenceresources/coherenceresources.go
> +	rules := conversionComponent.IngressTrait.Spec.Rules
IngressTrait can be nil here?

2023-07-21 17:50 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +			//conversionComponent.AppNamespace, conversionComponent.AppName, conversionComponent.ComponentName, conversionComponent.IngressTrait, conversionComponent.WeblogicworkloadMap[conversionComponent.Co
remove or explain commented code

2023-07-21 17:51 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +func CreateResources(conversionComponents []*types.ConversionComponents) (*types.KubeRecources, error) {
CreateKubeResources

2023-07-21 17:51 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +		if conversionComponent.Helidonworkload != nil {
What about ingress trait for generic workload?

2023-07-21 17:52 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +		if conversionComponent.Helidonworkload != nil {
@shahvrushali22

2023-07-21 17:52 UTC, AnshulDalua commented on tools/oam-converter/pkg/app/confdata.go
> +	printDirectory(outputDirectory, outputResources)
This is to print the new resources into the directory the user requests

2023-07-21 17:52 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +			outputResources.ServiceMonitors = append(outputResources.ServiceMonitors, serviceMonitor)
Is there a point to segregating the output resources by type? If we are only writing them out, you can put them all in a `[]runtime.Object`.

2023-07-21 17:53 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/secret.go
> +	// If there are no rules, create a single default rule
Is this supposed to reference a block of code?

2023-07-21 17:54 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/helidonresources/destinationrule.go
> +	//	Spec.DeploymentTemplate.PodSpec.Containers[0].Ports[0].ContainerPort != 0 {
Unsure what is going on here

2023-07-21 17:54 UTC, anders-swanson commented on tools/oam-converter/pkg/types/types.go
> +	VirtualServices  []*vsapi.VirtualService
consider using `[]runtime.Object` if we are only writing these to a file.

2023-07-21 17:55 UTC, anders-swanson commented on tools/oam-converter/pkg/types/types.go
> +	WeblogicworkloadMap map[string]*unstructured.Unstructured
How are generic workloads handled here, e.g., Deployment or other that might have traits?

2023-07-21 17:56 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/helidonresources/helidonresources.go
> +		err = createVirtualServiceFromHelidonWorkload(conversionComponent.IngressTrait, rule, vsHosts, vsName, gateway, conversionComponent.Helidonworkload)
either ingresstrait or helidonworkload can be nil here?

2023-07-21 17:57 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/helidonresources/helidonresources.go
> +		err = createVirtualServiceFromHelidonWorkload(conversionComponent.IngressTrait, rule, vsHosts, vsName, gateway, conversionComponent.Helidonworkload)
consider patterns like making `createVirtualServiceFromHelidonWorkload` a member function a ConversionComponent. You don't have to do this, but it's an organizational thing.

2023-07-21 17:57 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/helidonresources/helidonresources.go
> +		err = azp.CreateAuthorizationPolicies(conversionComponent.IngressTrait, rule, authzPolicyName, allHostsForTrait)
What about generic workloads?

2023-07-21 17:58 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +	if conversionComponent.Helidonworkload != nil {
I thought we were moving to using unstrcutured for handling generic workloads, if we are still splitting by type I am not understanding the purpose.

2023-07-21 18:01 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +			return nil, errors.New("app metadata doesn't exist")
doesn't exist, or may exist but be wrong type

2023-07-21 18:02 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +		//name = comp["metadata"].(map[string]interface{})["name"].(string)
remove commented line

2023-07-21 18:03 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +				case "VerrazzanoCoherenceWorkload":
1. JSON unmarshalling is not case specific, and should be moved up.
2. There is no handling for generic components here

2023-07-21 18:04 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +			if conversionComponents[i].ComponentName == name {
nested loop may not be necessary here, if you store component information from apps differently.

2023-07-21 18:04 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +			return nil, errors.New("spec key in a component doesn't exist")
similar notice about error handling as mentioned earlier

2023-07-21 18:05 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +					//weblogicWorkload := &vzapi.VerrazzanoWebLogicWorkload{}
commented code

2023-07-21 18:05 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +					weblogicMap[name] = weblogicWorkload
why are we doing this for weblogic, but no other workload type?

2023-07-21 18:07 UTC, anders-swanson requested changes
Please see comments, and look for ways to make the code more generic.

2023-07-31 17:18 UTC, davisgomes commented on examples/hello-helidon/hello-helidon-app-custom-port.yaml
> -  name: hello-helidon
Is this example meant to be deleted?

2023-07-31 17:18 UTC, davisgomes commented on examples/hello-helidon/hello-helidon-app-scaler-trait.yaml
> -apiVersion: core.oam.dev/v1alpha2
Same here. Should this be deleted?

2023-07-31 17:20 UTC, davisgomes commented on examples/hello-helidon/hello-helidon-app.yaml
> +# Copyright (c) 2023, Oracle and/or its affiliates.
This should remain in this format (first year is the creation year and second year is the last updated year):
`# Copyright (c) 2020, 2023, Oracle and/or its affiliates.`

2023-07-31 17:30 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app-custom-port.yaml
> -  name: hello-helidon
please restore changes to examples directory

2023-07-31 17:35 UTC, AnshulDalua commented on examples/hello-helidon/hello-helidon-app-custom-port.yaml
> -  name: hello-helidon
yes this was meant to be deleted, not sure why its here again

2023-07-31 17:37 UTC, AnshulDalua commented on examples/hello-helidon/hello-helidon-app-custom-port.yaml
> -  name: hello-helidon
no not sure why this got deleted, will fix

2023-07-31 17:47 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +	if len(os.Args) != 3 {
Even better if you are able to use flags. I think it would help make it more obvious how the tool is used: https://pkg.go.dev/flag

2023-07-31 17:47 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +		return errors.New("Not enough args to run tool")
This error message is too vauge. What args? What is the tool expecting from the user?

2023-07-31 17:48 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +		data, _ := ioutil.ReadFile(input)
Handle this error if that is the second argument.

2023-07-31 17:51 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +	_, err = f.WriteString(string(output))
Does this support multiple objects per file? I.e. two Gateways or two Service Monitors.

2023-07-31 17:51 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +	_, err = f.WriteString(string(output))
This seems like it will just append the objects together without splitting them. Can you test this scenario?

2023-07-31 17:53 UTC, davisgomes commented on tools/oam-converter/pkg/app/confdata.go
> +		return fmt.Errorf("Wrong data type%v", val)
Check output formatting on this error message, and maybe "Unsupported data type" would be more clear?

2023-07-31 17:59 UTC, davisgomes commented on tools/oam-converter/pkg/controllers/metricstrait_utils.go
> +	vznav "github.com/verrazzano/verrazzano/application-operator/controllers/navigation"
A lot of this code seems copied from the application operator. Can you extract the code in a way that both can use the shared code?

2023-07-31 18:32 UTC, anders-swanson commented on tools/oam-converter/pkg/controllers/metricstrait_utils.go
> +	vznav "github.com/verrazzano/verrazzano/application-operator/controllers/navigation"
I'd previously asked Anshul to try to do this, and it was it was not possible to share the code, to identify the app operator copied code somehow so we know where it was sourced from. Maybe Anshul can clarify why this code needed to be copied rather than shared

2023-07-31 18:36 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +	_, ok := trait.Labels[oam.LabelAppName]
I don't think the trait will have these labels? This is OAM specific?

2023-07-31 18:39 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	case map[string]interface{}:
would like to see this handled a little differently, something like this:
1. for each object, get its name and gvk. Since its a list of any, you might need to turn it to an unstructured.Unstructured first.
2. construct a filename based on the gvk and name. 
3. convert the object to bytes, and write it out to the file.

this will handle any type of resource

2023-07-31 18:40 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	case []*vsapi.VirtualService:
why do we have a nested list of virtual service? Since its a list of any in the outer loop, something is going wrong in the append

2023-07-31 18:42 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +			kubeResources = append(kubeResources, virtualService)
Please keep the append calls the way they were. This is appending a slice to a slice, such that the appended slice becomes an element of the outer slice. We want the _elements_ of the slice to be appended.

2023-07-31 20:27 UTC, AnshulDalua commented on tools/oam-converter/pkg/controllers/metricstrait_utils.go
> +	vznav "github.com/verrazzano/verrazzano/application-operator/controllers/navigation"
I had to copy this code because some functions I needed to modify to work with the converter. For example in createJobOrServiceMonitorName I changed the inputs so I can get the app name and component name which we already have while in application operator this function accesses this by doing app, found := trait.Labels[oam.LabelAppName]. For the functions that are copied verbatim from app operator, should I call those from app operator instead?

2023-07-31 20:39 UTC, davisgomes commented on tools/oam-converter/pkg/controllers/metricstrait_utils.go
> +	vznav "github.com/verrazzano/verrazzano/application-operator/controllers/navigation"
It sounds like you could write a wrapper function for the createJobOrServiceMonitorName that collects the app and component name to then call the underlying function in the app operator. This isn't always feasible but if you can find a way to tweak the function to support both, it could help.

To share the code, I'd suggest extracting the functions that are shared to an outer level package (i.e. one that does not live in the `application-operator/` or `tools/` directory; something like `/pkg/metricstrait/metricstrait.go`). Then you can import these functions in both the app operator and your oam tool.

2023-07-31 20:39 UTC, AnshulDalua commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +	_, ok := trait.Labels[oam.LabelAppName]
I believe it is like this in app operator

2023-07-31 20:40 UTC, AnshulDalua commented on tools/oam-converter/pkg/app/confdata.go
> +	case []*vsapi.VirtualService:
I think Vrushali needed It to be in a list of virtual services as she said multiple objects may be created

2023-07-31 20:42 UTC, AnshulDalua commented on tools/oam-converter/pkg/app/confdata.go
> +	case map[string]interface{}:
sounds good, thank you!

2023-08-01 18:13 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +	_, ok := trait.Labels[oam.LabelAppName]
Yes, but is it applicable to OAM Converter? I don't think so, since app operator adds these labels for OAM

2023-08-01 19:49 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	case []*vsapi.VirtualService:
This is depending on how you append to the slice. If you append a slice to slice, then yes. If you append the elements of a slice to a slice, then no.

2023-08-01 19:50 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +	}
Are there any trait defaults for generic workloads?

2023-08-01 19:50 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor.go
> +	//useHTTPS, err := operator.UseHTTPSForScrapeTarget(context.TODO(), cli, trait)
remove commented code

2023-08-01 19:53 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +							fmt.Printf("Failed to marshal trait: %v", err)
return err

2023-08-01 19:53 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +							fmt.Printf("Failed to unmarshal trait: %v", err)
return err

2023-08-08 14:46 UTC, anders-swanson commented on application-operator/controllers/metricsbinding/metricsbinding_update.go
> +// Copyright (c) 2023, Oracle and/or its affiliates.
Copyright (c) 2022, 2023,

2023-08-16 14:56 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			print("Null obj")
should return an error here

2023-08-16 14:57 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	if u, ok := obj.(*unstructured.Unstructured); ok {
Is the slice wrapping behavior necessary here - I don't think the any should ever be a slice?

2023-08-16 14:58 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	defer f.Close()
This comment still needs to be addressed

2023-08-16 16:30 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +func addResourcesToKubeResources(virtualService []*vsapi.VirtualService, destinationRule []*istioclient.DestinationRule, authzPolicy []*clisecurity.AuthorizationPolicy) {
why are we not using the `...` operator on the slice like why were before?

2023-08-16 16:35 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources_test.go
> +	for _, resource := range kubeResources {
I'm not sure this is working the way you think: we want to assert that a virtual service and a gateway are present in the array. This code is asserting that if a virtual service and a gateway are in the array, they're NotEmpty.

Also, since the gateway is a map[string]interface{}, we should be asserting that the Kind is gateway.

2023-08-16 16:37 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor_test.go
> +				AppName:       "test-appconf",
suggest to create a helper method for generating your test input. Most of the ConvertionComponents structs are the same, excepting the workload

2023-08-16 16:38 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor_test.go
> +			assert.Nil(t, err, "Unexpected error returned from CreateServiceMonitor")
use assert.NoError

2023-08-16 16:41 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/servicemonitor/servicemonitor_test.go
> +	types.InputArgs.IstioEnabled = false
This use of mutable, global state can cause confusion, especially if other tests/parts of the program are using it. Suggest to make this parameterized, or at least use `defer` to reset `types.InputArgs.IstioEnabled` once the test method returns.
In the case of tests, they may be run in random orders or be parallelized, so we cannot guarantee mutable global state is consistent between runs. In general this kind of construct should also be avoided.

2023-08-16 16:42 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +							fmt.Printf("Failed to unmarshal trait: %v", err)
the print can be removed now

2023-08-16 16:42 UTC, anders-swanson requested changes
See comments

2023-10-25 22:36 UTC, closed without merging