Vrushah/oam converter
verrazzano/verrazzano pull request #6480
Opened 2023-07-13 14:45 UTC by shahvrushali22

Provide a summary of the change and which issue (i.e. ticket) is fixed.
If there are any dependencies, for example on a PR in another repository, list those.

2023-07-13 14:55 UTC, anders-swanson commented
@shahvrushali22 please fix the conflicts and re-request review

2023-07-13 21:34 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	appData, err := ioutil.ReadFile("/Users/vrushah/GolandProjects/verrazzano/tools/oam-converter/pkg/app/hello-helidon-app.yaml")
This will get fixed in next pass to read from an input directory?

2023-07-13 21:35 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +func ExtractTrait(appMap map[string]interface{}) ([]*types.ConversionComponents, error) {
should be  named ExtractConversionComponents or similar

2023-07-13 21:37 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +func ExtractWorkload(components []map[string]interface{}, conversionComponents []*types.ConversionComponents) ([]*types.ConversionComponents, error) {
would like to see if you could add the workloads and traits to the conversion components in a single pass, i think this is doable. it could be in a follow up pr

2023-07-13 21:38 UTC, anders-swanson requested changes
please add a descriptive title to your PR

2023-07-17 14:41 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		if strings.Contains(info.Name(), "yaml") || strings.Contains(info.Name(), "yml") {
minor: filename should end with `.yaml` or `.yml`

2023-07-17 14:54 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +			//conversionComponent.AppNamespace, conversionComponent.AppName, conversionComponent.ComponentName, conversionComponent.IngressTrait, conversionComponent.WeblogicworkloadMap[conversionComponent.Co
remove comment

2023-07-24 21:47 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		fileName := "output.yaml"
should be called `servicemonitor.yaml`

2023-07-24 21:51 UTC, anders-swanson approved these changes
good to merge this once the branch is passing, please resolve minor comments in a follow-up

2023-07-24 21:53 UTC, anders-swanson requested changes
Please restore deleted examples

2023-07-25 14:01 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +				f, err := os.Create(filePath)
FYI you'll want to close any files you open, once you're done with them

2023-07-25 14:03 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +				defer f.Close()
defer is likely not working as you think it would, since this is in a loop

2023-07-25 14:04 UTC, anders-swanson commented on tools/oam-converter/pkg/types/types.go
> +	VirtualServices  [][]*vsapi.VirtualService
why'd these become 2-dimensional arrays?

2023-07-25 14:27 UTC, shahvrushali22 commented on tools/oam-converter/pkg/types/types.go
> +	VirtualServices  [][]*vsapi.VirtualService
A rule in the trait creates different virtual service for each component

2023-07-25 14:57 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app.yaml
> +        - trait:
Please remove changes to examples YAML

2023-07-25 15:03 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app.yaml
> +  namespace: hello-helidon
should not have namespace in examples

2023-07-25 15:04 UTC, anders-swanson commented on examples/hello-helidon/hello-helidon-app.yaml
> +
restore this directory, should not have changes

2023-07-25 15:22 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		fmt.Println("Not enough args to run tool")
we should return an error here

2023-07-25 15:23 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	var K8sResources []map[string]interface{}
style: variable names should begin with a lowercase letter

2023-07-25 15:24 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	var data []byte
should be a loop variable only

2023-07-25 15:24 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +		fmt.Println("Error in iterating over directory", err)
should return an error here

2023-07-25 15:25 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			if compKind == "Component" && compVersion == consts.CompAPIVersion {
These three if statements looks like it should be if, else if, else if instead.

2023-07-25 15:26 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +				//TODO for K8s resources that are not OAM-specific
is this TODO still?

2023-07-25 15:28 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	conversionComponents, err = traits.ExtractWorkload(components, conversionComponents)
having this extractWorkload function be in traits package is odd. typically would have something like:
```
traits.extract(appdata)
...
workload.extract(components)
```

or similar. just a style thing

2023-07-25 15:29 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +	if outputResources.VirtualServices != nil {
would like to see this not be a 2-d slice

2023-07-25 15:53 UTC, anders-swanson commented on tools/oam-converter/pkg/app/confdata.go
> +			return errors.New("failed to marshal YAML: %w")
should be using `fmt.Errorf("failed to marshal YAML: %w", err)` in these cases. errors.New wont do any formatting.

2023-07-25 16:48 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/createresources.go
> +	return nil, nil, nil, errors.New("ingress Trait is empty")
Why is it an error if there's no ingress trait?

2023-07-25 16:49 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +			print(err)
should be returning an error

2023-07-25 16:49 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +			print(err)
return err

2023-07-25 16:49 UTC, anders-swanson commented on tools/oam-converter/pkg/resources/gateway/gateway.go
> +			print(err)
return err

2023-07-25 17:18 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +							fmt.Printf("Failed to marshal trait: %v", err)
return errors here

2023-07-25 17:19 UTC, anders-swanson commented on tools/oam-converter/pkg/traits/extracttrait.go
> +		appNamespace, found, err := unstructured.NestedString(appMetadata, "namespace")
namespace might not exist. If it doesn't use `default`

2023-07-27 20:49 UTC, anders-swanson approved these changes
approved with expectation that comments will get resolved in follow up

2023-07-27 20:58 UTC, merged