resolve xip.io ourselves in the acceptance test
verrazzano/verrazzano pull request #668
Opened 2021-02-12 21:04 UTC by guoyongzhang

# Description

resolve xip.io ourselves in the acceptance test.

# Checklist 

As the author of this PR, I have:

- [x] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [x] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-02-12 22:27 UTC, markxnelson requested changes

2021-02-12 22:27 UTC, markxnelson commented on tests/e2e/pkg/web.go
> +			} else if strings.Contains(addr, "xip.io") && strings.Contains(addr, ":443")  {
i suspect this code makes incorrect assumptions, or at the very least is brittle

2021-02-13 00:18 UTC, guoyongzhang commented on tests/e2e/pkg/web.go
> +			} else if strings.Contains(addr, "xip.io") && strings.Contains(addr, ":443")  {
I agree it is brittle.  
Before finding a better solution, I wanted to get something quick and dirty in to work around the xip.io problem, which has been causing many red in develop branch this afternoon.  While xip.io at its worst, https://build.verrazzano.io/view/Component%20Builds/job/verrazzano/job/gz%252Fself_resove_xipio/ seems to be doing ok.  I am starting multiple runs to get bigger sample size.

2021-02-13 00:41 UTC, gilbode approved these changes

2021-02-13 00:41 UTC, markxnelson approved these changes

2021-02-13 00:45 UTC, merged