Add Acceptance Test to verify https scrape targets
verrazzano/verrazzano pull request #794
Opened 2021-03-09 18:15 UTC by ddrechse

# Description

Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another repository, please list those.

Fixes VZ-9999

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-03-10 21:59 UTC, bobdonat commented on tests/e2e/istio/authz/authpolicy_test.go
> +	ginkgo.Context("Deployment.", func() {
this looks like a repeat of the previous check for pos running

2021-03-10 22:10 UTC, bobdonat commented on tests/e2e/istio/authz/authpolicy_test.go
> +						if strings.Contains(innerString, prometheusHTTPSScheme) {
Shouldn't this be checking prometheusHTTPScheme

2021-03-10 22:34 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +	ginkgo.Context("Deployment.", func() {
yes because which suite runs first is indeterminate, its a resiliency thing

2021-03-10 22:35 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +						if strings.Contains(innerString, prometheusHTTPSScheme) {
http is the default and doesn't get explicitly added to out scrape targets
its https ot not (which is http )

2021-03-10 22:38 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +	ginkgo.Context("Deployment.", func() {
why 2 "suites" for lack of the proper word
1 just tests access between components
var _ = ginkgo.Describe("Verify AuthPolicy Applications", func() {
1 tests that scrape targets have been generated properly.
var _ = ginkgo.Describe("Verify Auth Policy Prometheus Scrape Targets", func() {
They seemed diff enough to be grouped separately

2021-03-10 22:46 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +	ginkgo.Context("Deployment.", func() {
I remember, don't know if they would ever run in parallel

2021-03-10 22:59 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +	ginkgo.Context("Deployment.", func() {
So i thought you were talking about a repeat of the test that were in the diff suite
I didn't groc it was an actual repeat  
Anyhow fixed it up, also removed host consts now that they are retrieved from the gw

2021-03-10 23:54 UTC, bobdonat commented on tests/e2e/istio/authz/authpolicy_test.go
> +						if strings.Contains(innerString, prometheusHTTPSScheme) {
I did not realize that

2021-03-10 23:57 UTC, bobdonat approved these changes

2021-03-11 13:59 UTC, markxnelson requested changes

2021-03-11 13:59 UTC, markxnelson commented on tests/e2e/istio/authz/authpolicy_test.go
> +const prometheusNoistioScrapeName string = "authpolicy-appconf_default_noistio_springboot-frontend"
Istio should have a capital I

2021-03-11 13:59 UTC, markxnelson commented on tests/e2e/istio/authz/authpolicy_test.go
> +var _ = ginkgo.Describe("Verify Auth Policy Prometheus Scrape Targets", func() {
Auth is ambiguous - authentication or authorization?  May as well spell it out

2021-03-11 13:59 UTC, markxnelson commented on tests/e2e/istio/authz/authpolicy_test.go
> +const prometheusFooScrapeName string = "authpolicy-appconf_default_foo_springboot-frontend"
can we use a meaningful name instead of 'foo' and 'bar'

2021-03-11 14:01 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +const prometheusNoistioScrapeName string = "authpolicy-appconf_default_noistio_springboot-frontend"
In the identifier?

2021-03-11 14:53 UTC, ddrechse commented on tests/e2e/istio/authz/authpolicy_test.go
> +const prometheusFooScrapeName string = "authpolicy-appconf_default_foo_springboot-frontend"
fixed

2021-03-11 16:08 UTC, markxnelson approved these changes

2021-03-11 16:10 UTC, merged