RBAC Acceptance Tests for new verrazzano cluster roles
verrazzano/verrazzano pull request #885
Opened 2021-03-25 21:07 UTC by ddrechse

# Description

Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another repository, please list those.

Create an Acceptance Test suite for RBAC based on new roles, verrazzano-project-admin and verrazzano-project-monitor.
Add helper functions CanI, CanIGroup where the api group is specified and CreateClusterRoleBinding
Verify that users with these rules can and cannot do what the roles grant

# Checklist 

As the author of this PR, I have:

- [ x] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ x] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-03-26 13:10 UTC, markxnelson requested changes
each comment applies to all cases, not just the one it is on

2021-03-26 13:10 UTC, markxnelson commented on tests/e2e/pkg/kubernetes.go
> +	clientset, err := kubernetes.NewForConfig(config)
can you use the functions we already have in kubernetes.go, like GetClientSet?

2021-03-26 13:10 UTC, markxnelson commented on tests/e2e/security/rbac/rbac_test.go
> +	gomega.Eventually(func() bool {
you should not assert in the afterSuite

2021-03-26 13:10 UTC, markxnelson commented on tests/e2e/security/rbac/rbac_test.go
> +			if allowed, reason := pkg.CanI(v80ProjectAdmin, rbacTestNamespace, "list", "pods"); allowed != false {
its better to use an assert than to do this and manually call Fail()

2021-03-26 13:10 UTC, markxnelson commented on tests/e2e/security/rbac/rbac_test.go
> +		time.Sleep(sleepDuration)
better to use k8s wait forCondition than to do an arbitrary sleep

2021-03-26 13:12 UTC, ddrechse commented on tests/e2e/pkg/kubernetes.go
> +	clientset, err := kubernetes.NewForConfig(config)
Unless you want to embed the code that adds headers to the rouundtripper but that seemed something particular to the CanI functionality

What happens in the code above is that after getting the config object, the rountripper needs to be modified for the http headers prior to building out the clientset

Like i said, this seemed really specific to the CanI use-case

2021-03-26 13:14 UTC, ddrechse commented on tests/e2e/security/rbac/rbac_test.go
> +		time.Sleep(sleepDuration)
The condition returns immediately.  What would I wait for?  This only happens on Kind when the full test suite runs under 500 ms

2021-03-26 13:16 UTC, ddrechse commented on tests/e2e/security/rbac/rbac_test.go
> +	gomega.Eventually(func() bool {
That code was copied from the SpringBoot test.  It appears there and the Auth tests. So the paradigm is embedded in the test suites

2021-03-26 13:19 UTC, ddrechse commented on tests/e2e/security/rbac/rbac_test.go
> +			if allowed, reason := pkg.CanI(v80ProjectAdmin, rbacTestNamespace, "list", "pods"); allowed != false {
why?

2021-03-26 13:23 UTC, kminder commented on tests/e2e/pkg/kubernetes.go
> +	"k8s.io/api/authorization/v1beta1"
Reorder

2021-03-26 13:24 UTC, kminder commented on tests/e2e/pkg/kubernetes.go
> +func (h *headerAdder) RoundTrip(req *http.Request) (*http.Response, error) {
How about a comment on this one as it isn't totally clear what it does.

2021-03-26 13:26 UTC, kminder commented on tests/e2e/security/rbac/rbac_test.go
> +	"github.com/onsi/gomega"
reorder

2021-03-26 16:18 UTC, ddrechse commented on tests/e2e/pkg/kubernetes.go
> +	"k8s.io/api/authorization/v1beta1"
Done

2021-03-26 16:19 UTC, ddrechse commented on tests/e2e/security/rbac/rbac_test.go
> +	"github.com/onsi/gomega"
Done

2021-03-26 16:39 UTC, ddrechse commented on tests/e2e/pkg/kubernetes.go
> +func (h *headerAdder) RoundTrip(req *http.Request) (*http.Response, error) {
Added
The following code adds http headers to the kubernetes client invocations.  This is done to emulate the functionality of
kubectl auth can-i ...

WrapTransport is configured to point to the function
WrapTransport will be invoked for custom HTTP behavior after the underlying transport is initialized
(either the transport created from TLSClientConfig, Transport, or http.DefaultTransport).
The config may layer other RoundTrippers on top of the returned RoundTripper.

WrapperFunc wraps an http.RoundTripper when a new transport is created for a client, allowing per connection behavior to be injected.

RoundTripper is an interface representing the ability to execute a single HTTP transaction, obtaining the Response for a given Request.

2021-03-26 18:42 UTC, markxnelson commented on tests/e2e/security/rbac/rbac_test.go
> +			if allowed, reason := pkg.CanI(v80ProjectAdmin, rbacTestNamespace, "list", "pods"); allowed != false {
gomega.Expect(pkg.CanI(whatever)).To(gomega.BeTrue(), "message if its not")

2021-03-26 19:34 UTC, ddrechse commented on tests/e2e/security/rbac/rbac_test.go
> +			if allowed, reason := pkg.CanI(v80ProjectAdmin, rbacTestNamespace, "list", "pods"); allowed != false {
Done

2021-03-26 21:17 UTC, markxnelson submitted a review, later dismissed

2021-03-27 00:30 UTC, markxnelson approved these changes

2021-03-29 12:54 UTC, merged