WIP: MC Test for Change Placement Example
verrazzano/verrazzano pull request #919
Opened 2021-04-05 17:46 UTC by desagar

# Description

Write an acceptance test for the change-placement multicluster example

Fixes VZ-2338

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-04-05 19:15 UTC, markxnelson requested changes
didn't read the whole thing, but found enough fairly substantial issues already

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_suite_test.go
> +package mchelidon
package name does not match directory name?

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +var _ = ginkgo.Describe("Multi-cluster Verify Hello Helidon", func() {
please fix capitalization

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +		// verify deletion from admin cluster where the app was placed
didn't you just move it back to the managed cluster?

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +	cleanUp()
why do you need to call this again, you just called it in the last test?

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +		ginkgo.Fail(fmt.Sprintf("Failed to delete multi-cluster change-placement application resource: %v", err))
you really should not call Fail() in a utility func that you call from a test, you should have the util func return status/results and an error, and then inspect the error and call Fail() if needed in the test itself.  
the pattern you have implemented here was done in several existing tests and anecdotally is the cause of 90% of the test failures we have looked at

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/example_utils.go
> +import (
i'm not a fan of creating more and more of these magical util files all over the place

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/example_utils.go
> +	gomega.Eventually(func() bool {
as per the comment about Fail() earlier, you really should avoid calling Eventually() down in some util func too - same reasons, assertions (like Eventually) belong in the tests, not hidden in random funcs all over the place

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the MultiClusterApplicationConfiguration exists", func() {
same issue - don't hide tests away in util funcs like this

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It(fmt.Sprintf("Verify the MultiClusterApplicationConfiguration %s on this managed cluster", existString), func() {
not a fan of sprintf'ing the test name!  use a parameterized test instead - look at ginkgoext.DescribeTable

2021-04-05 19:15 UTC, markxnelson commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the project exists", func() {
again, putting tests or assertions in funcs 2, 3, or more layers down, like this, has been a source of many issues, and i want to eliminate that pattern

2021-04-05 19:47 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the MultiClusterApplicationConfiguration exists", func() {
So, regarding the whole tests in util funcs and ginkgo.Fail in utils funcs - the new test I added does very nearly the same thing as an existing test, so rather than repeat the cases in the 2 places, I changed it to share the set of cases that check "everything is good on this cluster given the app is placed here" and "everything is good on this cluster given the app is NOT placed here" 

I can take these out of the function and move it back to the tests, but the same exact cases would be repeated in 2 different tests.

2021-04-05 19:48 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the project exists", func() {
See my reply above on related comment

2021-04-05 19:49 UTC, desagar commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +	cleanUp()
that's an oversight - will remove

2021-04-05 19:49 UTC, desagar commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +		// verify deletion from admin cluster where the app was placed
right but the multiclusterxxx stuff is still on the admin cluster. This is "final cleanup".

2021-04-05 19:50 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	gomega.Eventually(func() bool {
see my reply in the other related comment. If you prefer the duplication to this indirection, that's fine with me

2021-04-05 20:12 UTC, desagar commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_suite_test.go
> +package mchelidon
fixed

2021-04-05 20:13 UTC, desagar commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +	cleanUp()
removed the duplicate call to cleanup()

2021-04-06 18:51 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	gomega.Eventually(func() bool {
fixed

2021-04-06 18:51 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It(fmt.Sprintf("Verify the MultiClusterApplicationConfiguration %s on this managed cluster", existString), func() {
fixed

2021-04-06 18:52 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the project exists", func() {
fixed

2021-04-06 18:52 UTC, desagar commented on tests/e2e/multicluster/examples/example_utils.go
> +	ginkgo.It("Verify the MultiClusterApplicationConfiguration exists", func() {
fixed - took all ginkgo/gomega test references from the utility funcs and moved them back up to the test methods themselves.

2021-04-06 20:25 UTC, desagar commented on tests/e2e/multicluster/examples/change-placement/change_placement_example_test.go
> +var _ = ginkgo.Describe("Multi-cluster Verify Hello Helidon", func() {
done

2021-04-06 21:51 UTC, mgianatagh submitted a review, later dismissed

2021-04-07 13:30 UTC, markxnelson approved these changes

2021-04-07 14:06 UTC, merged