WIP: OKE With Private Endpoints
verrazzano/verrazzano pull request #971
Opened 2021-04-14 02:28 UTC by tbeerbower

# Description

Please include a summary of the change and which issue is fixed.  If there are any dependencies, for example on a PR in another repository, please list those.

Fixes VZ-9999

# Checklist 

As the author of this PR, I have:

- [ ] Checked that I included or updated copyright and license notices in all files that I altered
- [ ] Added or updated unit tests for any new functions I added
- [ ] Added or updated integration tests if appropriate
- [ ] Added or updated acceptance tests if appropriate

Code reviewer, please confirm this PR:

- [ ] Addressed the requirement and meets the acceptance criteria
- [ ] Does not introduce unrelated or spurious changes
- [ ] Does not introduce any unapproved dependency
- [ ] Makes sense and it easy to understand, and/or difficult areas of code are clearly documented so that they can be understood

2021-04-19 18:51 UTC, markxnelson requested changes
any new external dependency needs approval

2021-04-19 18:53 UTC, markxnelson requested changes

2021-04-19 18:53 UTC, markxnelson commented on tests/e2e/config/scripts/use_bastion_host.sh
> +wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
use yum.oracle.com (epel repo) not fedora

2021-04-23 02:05 UTC, tbeerbower commented on tests/e2e/config/scripts/use_bastion_host.sh
> +wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
done

2021-04-23 19:19 UTC, markxnelson approved these changes

2021-04-23 19:46 UTC, merged